import type { LocalizedText } from './i18n.ts'

function localized(ja: string, en: string): LocalizedText {
  return Object.freeze({ ja, en })
}

export const APP_TEXT = Object.freeze({
  grid: localized('グリッド', 'Grid'),
  vertex: localized('頂点', 'Vertex'),
  intersection: localized('交点', 'Intersection'),
  edge: localized('辺', 'Edge'),
  midpoint: localized('中点', 'Midpoint'),
  horizontal: localized('水平', 'Horizontal'),
  vertical: localized('垂直', 'Vertical'),
  parallel: localized('平行', 'Parallel'),
  angle: localized('角度', 'Angle'),
  foldTechniqueFileOperationsAreAvailableInTheDesktopApp: localized(
    '折り技法ファイルの操作はデスクトップ版で利用できます。',
    'Fold-technique file operations are available in the desktop app.',
  ),
  anotherFoldTechniqueFileOperationIsInProgressTryAgain: localized(
    '別の折り技法ファイル操作が進行中です。完了後にもう一度お試しください。',
    'Another fold-technique file operation is in progress. Try again after it finishes.',
  ),
  theSelectionWasNotProcessedBecauseItIsNotA: localized(
    '通常ファイルではないため、安全のため処理しませんでした。',
    'The selection was not processed because it is not a regular file.',
  ),
  theFoldTechniqueFileExceedsThe1MiBLimit: localized(
    '折り技法ファイルが1 MiBの上限を超えています。',
    'The fold-technique file exceeds the 1 MiB limit.',
  ),
  theFoldTechniqueFileDoesNotSatisfyTheStrictV1: localized(
    '折り技法ファイルが厳格なV1形式を満たしていません。',
    'The fold-technique file does not satisfy the strict V1 format.',
  ),
  theFoldTechniqueFileCouldNotBeReadSafely: localized(
    '折り技法ファイルを安全に読み込めませんでした。',
    'The fold-technique file could not be read safely.',
  ),
  theFoldTechniqueFileCouldNotBeSavedAtomically: localized(
    '折り技法ファイルを原子的に保存できませんでした。',
    'The fold-technique file could not be saved atomically.',
  ),
  theFoldTechniqueFileOperationResponseCouldNotBeVerified: localized(
    '折り技法ファイル操作の応答を検証できませんでした。',
    'The fold-technique file operation response could not be verified.',
  ),
  notRun: localized('未実行', 'Not run'),
  waitingForFaceAndHingeAnalysis: localized('面・ヒンジ解析待ち', 'Waiting for face and hinge analysis'),
  text3dAnalysisIsAvailableInTheDesktopApp: localized(
    '3D解析はデスクトップ版で利用できます',
    '3D analysis is available in the desktop app',
  ),
  connectingToCore: localized('コア接続中…', 'Connecting to core…'),
  browserPrototypeMode: localized('ブラウザ試作モード', 'Browser prototype mode'),
  undoRedoHistoryLimitChangedToLimit: localized(
    'Undo・Redo履歴の上限を{limit}件に変更しました。',
    'Undo/redo history limit changed to {limit}.',
  ),
  showingRestoredEdits: localized('復元した編集内容を表示しています', 'Showing restored edits'),
  checkingRecoveryData: localized('復旧データを確認しています…', 'Checking recovery data…'),
  rustCoreRevisionRevision: localized(
    'Rustコア revision {revision}',
    'Rust core revision {revision}',
  ),
  chooseHowToHandleTheUnsavedRecoveryData: localized(
    '未保存の復旧データについて判断してください。',
    'Choose how to handle the unsaved recovery data.',
  ),
  recoveryDataCouldNotBeCheckedPleaseTryAgain: localized(
    '復旧データを確認できませんでした。再試行してください。',
    'Recovery data could not be checked. Please try again.',
  ),
  unsavedEditsWereRestoredChooseALocationAndSaveThem: localized(
    '未保存の編集内容を復元しました。保存先を選んで保存してください。',
    'Unsaved edits were restored. Choose a location and save them.',
  ),
  recoveryDataCouldNotBeRestoredPleaseTryAgain: localized(
    '復旧データを復元できませんでした。もう一度お試しください。',
    'Recovery data could not be restored. Please try again.',
  ),
  recoveryDataWasDiscarded: localized('復旧データを破棄しました。', 'Recovery data was discarded.'),
  recoveryDataCouldNotBeDiscardedPleaseTryAgain: localized(
    '復旧データを破棄できませんでした。もう一度お試しください。',
    'Recovery data could not be discarded. Please try again.',
  ),
  faceIndex: localized('面 {index}', 'Face {index}'),
  blockedBy3DInputConsistencyValidation: localized(
    '3D入力の整合性検証で遮断',
    'Blocked by 3D input consistency validation',
  ),
  unknownDimensions: localized('寸法不明', 'Unknown dimensions'),
  message0036: localized('・', ', '),
  none: localized('なし', 'None'),
  analyzingFacesAndHinges: localized('面・ヒンジ解析中…', 'Analyzing faces and hinges…'),
  facesFacesHingesHinges: localized('{faces}面・{hinges}ヒンジ', '{faces} faces · {hinges} hinges'),
  text3dAnalysisBlockedCountIssues: localized(
    '3D解析で遮断（{count}件）',
    '3D analysis blocked ({count} issues)',
  ),
  theQuitCheckCouldNotStartKeepTheAppOpen: localized(
    '終了確認を開始できませんでした。アプリを開いたまま、もう一度お試しください。',
    'The quit check could not start. Keep the app open and try again.',
  ),
  coreErrorTheEditResultCouldNotBeMergedInto: localized(
    'コアエラー: 編集結果を現在のプロジェクトへ結合できませんでした',
    'Core error: the edit result could not be merged into the current project',
  ),
  intersectionsRepairedUndoAndRedoAreAvailable: localized(
    '交差を一括修復しました。元に戻す／やり直すを利用できます。',
    'Intersections repaired. Undo and redo are available.',
  ),
  chooseAMirrorSelectionAndAFiniteTwoPointAxis: localized(
    '対称選択と有限な2点の対称軸を指定してください。',
    'Choose a mirror selection and a finite two-point axis.',
  ),
  mirrorPreflightFailed: localized('対称編集の事前検証に失敗しました。', 'Mirror preflight failed.'),
  choose116CopiesAndAFiniteNonZeroOffset: localized(
    'コピー数は1〜16、移動量は0以外の有限値で指定してください。',
    'Choose 1–16 copies and a finite, non-zero offset.',
  ),
  theLinearArrayPreviewCouldNotBeCreated: localized(
    '線形配列のプレビューを作成できませんでした。',
    'The linear-array preview could not be created.',
  ),
  theMirrorAxisIsInvalid: localized('対称軸が無効です。', 'The mirror axis is invalid.'),
  theSelectionIsEmpty: localized('選択が空です。', 'The selection is empty.'),
  thisEditIsUnsafeForTheCurrentGeometryOrLayers: localized(
    '現在の形状またはレイヤーでは安全に適用できません。',
    'This edit is unsafe for the current geometry or layers.',
  ),
  theMirrorEditCannotBeApplied: localized('対称編集を適用できません。', 'The mirror edit cannot be applied.'),
  theBenchmarkPatternIsReadOnlyReturnToTheNormal: localized(
    '性能テストの図は読み取り専用です。通常図へ戻ると編集できます',
    'The benchmark pattern is read-only. Return to the normal pattern to edit.',
  ),
  thisGeometryBelongsToALockedLayerUnlockTheLayer: localized(
    'ロック中のレイヤーに属する図形は編集できません。レイヤーの編集ロックを解除してください。',
    'This geometry belongs to a locked layer. Unlock the layer before editing it.',
  ),
  addOrRemoveBoundaryEdgesThroughPaperShapeEditing: localized(
    '輪郭線の追加・削除は紙形状編集から行います',
    'Add or remove boundary edges through paper shape editing.',
  ),
  thisBoundaryVertexCannotBeDeletedBecauseABoundaryNeeds: localized(
    '輪郭は最低3点必要なため、この輪郭頂点は削除できません',
    'This boundary vertex cannot be deleted because a boundary needs at least three points.',
  ),
  deletedTheBoundaryVertexAndMergedItsAdjacentEdgesUndo: localized(
    '輪郭頂点を削除し、隣接する輪郭辺を統合しました（元に戻すで復元できます）',
    'Deleted the boundary vertex and merged its adjacent edges (Undo can restore it).',
  ),
  deletedTheVertexUndoCanRestoreIt: localized(
    '頂点を削除しました（元に戻すで復元できます）',
    'Deleted the vertex (Undo can restore it).',
  ),
  theBoundaryEdgeWasSplitButTheNewVertexCould: localized(
    '輪郭辺を分割しましたが、新しい頂点を特定できませんでした',
    'The boundary edge was split, but the new vertex could not be identified.',
  ),
  splitTheBoundaryEdgeAtItsMidpointAndSelectedThe: localized(
    '輪郭辺を中点で分割し、新しい頂点を選択しました',
    'Split the boundary edge at its midpoint and selected the new vertex.',
  ),
  creasesAndVerticesOnALockedLayerCannotBeEdited: localized(
    'ロック中のレイヤーにある折り線または頂点は編集できません。',
    'Creases and vertices on a locked layer cannot be edited.',
  ),
  theEdgeToSplitWasNotFoundEdgeId: localized(
    '分割対象の辺が見つかりません: {edgeId}',
    'The edge to split was not found: {edgeId}',
  ),
  theEdgesSelectedForIntersectionConnectionAreInvalid: localized(
    '交点接続の対象辺が不正です',
    'The edges selected for intersection connection are invalid.',
  ),
  theIntersectionWasConnectedButTheConnectedVertexCouldNot: localized(
    '交点を接続しましたが、接続頂点を確認できませんでした',
    'The intersection was connected, but the connected vertex could not be verified.',
  ),
  connectedTheTJunctionOneUndoRestoresIt: localized(
    'T字交点を接続しました（元に戻す1回で復元できます）',
    'Connected the T-junction (one Undo restores it).',
  ),
  connectedCountEdgesAsAnIntersectionClusterOneUndoRestores: localized(
    '{count}本の辺を交点クラスタとして接続しました（元に戻す1回で復元できます）',
    'Connected {count} edges as an intersection cluster (one Undo restores it).',
  ),
  atomicallySplitTwoEdgesAtTheirIntersectionOneUndoRestores: localized(
    '交点で2本の辺を原子的に分割しました（元に戻す1回で復元できます）',
    'Atomically split two edges at their intersection (one Undo restores it).',
  ),
  aVertexWasCreatedButItCouldNotBeUniquely: localized(
    '頂点を作成しましたが、新しい頂点を一意に特定できませんでした',
    'A vertex was created, but it could not be uniquely identified.',
  ),
  splitTheEdgeAndSelectedTheNewVertexUndoCan: localized(
    '辺を分割し、新しい頂点を選択しました（元に戻すで復元できます）',
    'Split the edge and selected the new vertex (Undo can restore it).',
  ),
  addedAndSelectedAVertexUndoCanRestoreIt: localized(
    '頂点を追加して選択しました（元に戻すで復元できます）',
    'Added and selected a vertex (Undo can restore it).',
  ),
  theDefaultLayerIsLockedSoANewLineCannot: localized(
    '既定レイヤーがロックされているため、新しい線を追加できません。',
    'The default layer is locked, so a new line cannot be added.',
  ),
  selectTheLineEndpoint: localized('線の終点を選択してください', 'Select the line endpoint.'),
  selectAVertexDifferentFromTheStartPoint: localized(
    '始点とは異なる頂点を選択してください',
    'Select a vertex different from the start point.',
  ),
  enterAnAngleFrom0UpTo360ExclusiveWith: localized(
    '0度以上360度未満の角度を小数6桁以内で入力し、利用可能な線種を選択してください。',
    'Enter an angle from 0° up to 360° (exclusive) with at most six decimal places and choose an available line type.',
  ),
  drewALineToTheFirstTargetIntersectedAtThe: localized(
    '指定角度で最初に交差する対象まで線を作図しました。',
    'Drew a line to the first target intersected at the specified angle.',
  ),
  enterAPositiveFiniteLengthAFiniteAngleAndAn: localized(
    '正の有限な長さ、有限な角度、利用可能な線種を入力してください。',
    'Enter a positive finite length, a finite angle, and an available line type.',
  ),
  theSpecifiedLengthAndAngleDoNotProduceFiniteCoordinates: localized(
    '指定した長さと角度から有限な座標を作成できません。',
    'The specified length and angle do not produce finite coordinates.',
  ),
  addedAnEndpointAndLineFromTheSpecifiedLengthAnd: localized(
    '指定した長さと角度から終点と線を追加しました。',
    'Added an endpoint and line from the specified length and angle.',
  ),
  enterFiniteNumericCoordinates: localized(
    '座標には有限の数値を入力してください',
    'Enter finite numeric coordinates.',
  ),
  enterFiniteNumericCoordinates2: localized(
    '有限な数値座標を入力してください。',
    'Enter finite numeric coordinates.',
  ),
  addedAVertexAtTheSpecifiedCoordinates: localized(
    '指定座標に頂点を追加しました。',
    'Added a vertex at the specified coordinates.',
  ),
  enterFiniteExpressionsForTheLineTranslation: localized(
    '線の移動量には有限な数式を入力してください。',
    'Enter finite expressions for the line translation.',
  ),
  enterFiniteExpressionsForTheFaceTranslation: localized(
    '面の移動量には有限な数式を入力してください。',
    'Enter finite expressions for the face translation.',
  ),
  chooseTwoNonAdjacentFaceVerticesAndAnAvailableLine: localized(
    '面を分割する非隣接の2頂点と利用可能な線種を選択してください。',
    'Choose two non-adjacent face vertices and an available line type.',
  ),
  enterAFinitePaperThicknessOf0OrGreater: localized(
    '紙厚には0以上の有限の数値を入力してください',
    'Enter a finite paper thickness of 0 or greater.',
  ),
  chooseValidFrontAndBackColors: localized(
    '表色と裏色には有効な色を指定してください',
    'Choose valid front and back colors.',
  ),
  reviewTheElementNameColorAndMemo: localized(
    '要素の名前、色、メモを確認してください。',
    'Review the element name, color, and memo.',
  ),
  keepTheProjectMemoWithin16000Characters: localized(
    'プロジェクトメモは16000文字以内で入力してください。',
    'Keep the project memo within 16,000 characters.',
  ),
  applyThisMeasuredCandidateBoundingBoxAreaAndNormalsProvide: localized(
    '境界箱・面積・法線だけから算出した範囲候補を適用しますか？',
    'Apply this measured candidate? Bounding box, area, and normals provide geometry evidence only; part meanings come from the parts you confirmed.',
  ),
  bridgesBetweenDisconnected3DComponentsAreEstimatedCopyToA: localized(
    '切断された3D成分間のbridgeは推定です。理由を確認してカスタム対象へコピーしますか？',
    'Bridges between disconnected 3D components are estimated. Copy to a custom target after reviewing the reason?',
  ),
  selectAReferenceImageToRecognize: localized(
    '認識する参照画像を選択してください。',
    'Select a reference image to recognize.',
  ),
  copyThisOutlineIntoTheEditableTargetSkeletonThisDoes: localized(
    'この輪郭候補を編集可能な目標骨格へコピーしますか？生成は開始しません。',
    'Copy this outline into the editable target skeleton? This does not start generation.',
  ),
  applyTheExplicitPartAssignmentsToTargetPartsThisDoes: localized(
    '明示した部位割当を目標部位へ反映しますか？生成は開始しません。',
    'Apply the explicit part assignments to target parts? This does not start generation.',
  ),
  saveTheAdjustedSymmetricParametersThisDoesNotStartGeneration: localized(
    '調整した対称パラメータを保存しますか？生成は開始しません。',
    'Save the adjusted symmetric parameters? This does not start generation.',
  ),
  copyThisRecognitionProposalIntoTheEditorTheProjectStays: localized(
    '認識候補を編集欄へコピーしますか？保存するまでprojectは変更されません。',
    'Copy this recognition proposal into the editor? The project stays unchanged until saved.',
  ),
  thisContourProposalHasLowConfidenceOverrideAfterReviewingIts: localized(
    '低信頼の輪郭提案です。理由を確認したうえで上書きしますか？',
    'This contour proposal has low confidence. Override after reviewing its reasons?',
  ),
  copiedTheProposalIntoTheEditorSaveItToAdd: localized(
    '認識案を編集欄へコピーしました。保存すると履歴に追加されます。',
    'Copied the proposal into the editor. Save it to add it to history.',
  ),
  revalidateThisDesignSGridGeometryAndGlobalProofThen: localized(
    'この案の格子・形状・大域証明を再検証して適用しますか？変更全体は1回のUndoで戻せます。',
    'Revalidate this design’s grid, geometry, and global proof, then apply it? One Undo reverts the whole change.',
  ),
  appendThisReviewedReadOnlyProposalToTheInstructionsIt: localized(
    'この読み取り専用案を確認済みとして折り手順へ追加しますか？物理動作の証明ではありません。',
    'Append this reviewed read-only proposal to the instructions? It is not physical-motion proof.',
  ),
  applyThisCandidateToTheCreasePatternAndInstructionsYou: localized(
    'この候補を展開図と折り手順へ適用します。適用後もUndoで元に戻せます。続行しますか？',
    'Apply this candidate to the crease pattern and instructions? You can undo the whole change.',
  ),
  theCurrentPaperIsNotAnAxisAlignedRectangleSo: localized(
    '現在の紙は軸平行な長方形ではないため、サイズを変更できません',
    'The current paper is not an axis-aligned rectangle, so it cannot be resized here.',
  ),
  enterAFinitePaperWidthGreaterThan0: localized(
    '用紙の幅には0より大きい有限の数値を入力してください',
    'Enter a finite paper width greater than 0.',
  ),
  enterAFinitePaperHeightGreaterThan0: localized(
    '用紙の高さには0より大きい有限の数値を入力してください',
    'Enter a finite paper height greater than 0.',
  ),
  revisionRevisionValidating: localized(
    'revision {revision}: 検証中…',
    'revision {revision}: validating…',
  ),
  theProjectChangedDuringValidationPleaseValidateAgain: localized(
    '検証中に内容が変更されたため、再度検証してください',
    'The project changed during validation. Please validate again.',
  ),
  message0105: localized('revision {revision}: {geometry}・{local}', ''),
  message0106: localized('幾何問題{count}件', ''),
  revisionRevisionGeometryLocal: localized('', 'revision {revision}: {geometry} · {local}'),
  countGeometryIssues: localized('', '{count} geometry issues'),
  enterAProjectName: localized('作品名を入力してください。', 'Enter a project name.'),
  useAtMost120CharactersAndDoNotIncludeControl: localized(
    '作品名は制御文字を含まない120文字以内にしてください。',
    'Use at most 120 characters and do not include control characters.',
  ),
  enterAWidthExpression: localized('幅の式を入力してください。', 'Enter a width expression.'),
  enterAHeightExpression: localized('高さの式を入力してください。', 'Enter a height expression.'),
  enterAFinitePaperThicknessOf0OrGreater2: localized(
    '紙厚には0以上の有限の数値を入力してください。',
    'Enter a finite paper thickness of 0 or greater.',
  ),
  chooseFrontAndBackColors: localized('表色と裏色を選択してください。', 'Choose front and back colors.'),
  createdNameASaveLocationHasNotBeenSetYet: localized(
    '「{name}」を作成しました。保存先はまだ設定されていません。',
    'Created “{name}”. A save location has not been set yet.',
  ),
  message0116: localized('作成できませんでした: {message}', ''),
  couldNotCreateTheProjectMessage: localized('', 'Could not create the project: {message}'),
  message0118: localized('新規作成エラー: {message}', ''),
  newProjectErrorMessage: localized('', 'New project error: {message}'),
  fileOperationCancelled: localized('ファイル操作をキャンセルしました', 'File operation cancelled'),
  openedName: localized('「{name}」を開きました', 'Opened “{name}”'),
  savedName: localized('「{name}」を保存しました', 'Saved “{name}”'),
  expandedFolderOperationCancelled: localized(
    '展開フォルダー操作をキャンセルしました',
    'Expanded-folder operation cancelled',
  ),
  openedNameFromAnExpandedFolder: localized(
    '展開フォルダーから「{name}」を開きました',
    'Opened “{name}” from an expanded folder',
  ),
  savedNameToANewExpandedFolder: localized(
    '「{name}」を新しい展開フォルダーへ保存しました',
    'Saved “{name}” to a new expanded folder',
  ),
  foldTechniqueFileImportWasCancelled: localized(
    '折り技法ファイルの取込をキャンセルしました。',
    'Fold-technique file import was cancelled.',
  ),
  importedTheFoldTechniqueFileYouCanReviewAndEdit: localized(
    '折り技法ファイルを取り込みました。内容を確認して編集できます。',
    'Imported the fold-technique file. You can review and edit it.',
  ),
  keptTheFoldTechniqueChangesChooseSaveAsToShare: localized(
    '折り技法の変更を保持しました。共有するには「別名保存」を実行してください。',
    'Kept the fold-technique changes. Choose “Save as” to share them.',
  ),
  savingTheNewFoldTechniqueWasCancelledTheEditedContent: localized(
    '新しい折り技法の保存をキャンセルしました。編集内容は画面に残っています。',
    'Saving the new fold technique was cancelled. The edited content remains open.',
  ),
  createdTheFoldTechniqueAndSavedItToAShared: localized(
    '新しい折り技法を作成し、共有ファイルへ保存しました。',
    'Created the fold technique and saved it to a shared file.',
  ),
  savingTheFoldTechniqueFileAsAnotherFileWasCancelled: localized(
    '折り技法ファイルの別名保存をキャンセルしました。内容は変更していません。',
    'Saving the fold-technique file as another file was cancelled. No content changed.',
  ),
  savedTheFoldTechniqueToAnotherSharedFile: localized(
    '折り技法を別名の共有ファイルへ保存しました。',
    'Saved the fold technique to another shared file.',
  ),
  foldImportCancelled: localized('FOLD取込をキャンセルしました', 'FOLD import cancelled'),
  noImportPreviewWasReturned: localized('取込プレビューが返されませんでした', 'No import preview was returned.'),
  reviewTheFOLDLineTypesAndScale: localized(
    'FOLDの線種・縮尺を確認してください',
    'Review the FOLD line types and scale.',
  ),
  returnedToTheNormalCreasePatternAfterFOLDImport: localized(
    'FOLD取込により通常の展開図へ戻りました',
    'Returned to the normal crease pattern after FOLD import',
  ),
  importedNameFromFOLDASaveLocationHasNotBeen: localized(
    'FOLDから「{name}」を取り込みました。保存先はまだ設定されていません。',
    'Imported “{name}” from FOLD. A save location has not been set yet.',
  ),
  svgImportCancelled: localized('SVG取込をキャンセルしました', 'SVG import cancelled'),
  reviewTheSVGBoundaryLineTypesAndScale: localized(
    'SVGの外周・線種・縮尺を確認してください',
    'Review the SVG boundary, line types, and scale.',
  ),
  message0140: localized('SVG外周を検証しました: {width} × {height} mm', ''),
  validatedSVGBoundaryWidthHeightMm: localized('', 'Validated SVG boundary: {width} × {height} mm'),
  returnedToTheNormalCreasePatternAfterSVGImport: localized(
    'SVG取込により通常の展開図へ戻りました',
    'Returned to the normal crease pattern after SVG import',
  ),
  importedNameFromSVGASaveLocationHasNotBeen: localized(
    'SVGから「{name}」を取り込みました。保存先はまだ設定されていません。',
    'Imported “{name}” from SVG. A save location has not been set yet.',
  ),
  rejectedAnExportPreviewThatDoesNotMatchTheCurrent: localized(
    '編集中のプロジェクトと一致しない書き出しプレビューを拒否しました',
    'Rejected an export preview that does not match the current project.',
  ),
  message0145: localized('{format}書き出しの情報損失を確認してください', ''),
  reviewInformationLossForTheFormatExport: localized(
    '',
    'Review information loss for the {format} export.',
  ),
  creasePatternExportCancelled: localized('展開図書き出しをキャンセルしました', 'Crease-pattern export cancelled'),
  theProjectChangedRebuildTheExportData: localized(
    '編集内容が変わったため、書き出しデータを作り直してください。',
    'The project changed. Rebuild the export data.',
  ),
  saveLocationSelectionWasCancelledYouCanRetryFromThe: localized(
    '保存先の選択をキャンセルしました。確認画面から再試行できます。',
    'Save location selection was cancelled. You can retry from the review screen.',
  ),
  creasePatternSaveLocationSelectionCancelled: localized(
    '展開図の保存先選択をキャンセルしました',
    'Crease-pattern save location selection cancelled',
  ),
  exportedFileName: localized('{fileName}を書き出しました', 'Exported {fileName}'),
  reviewTheCurrentPoseMidSurfaceMeshAndInformationLoss: localized(
    '現在の3D姿勢の中央面メッシュと情報損失を確認してください',
    'Review the current-pose mid-surface mesh and information loss.',
  ),
  couldNotGenerateAMeshFromTheAuthenticatedPoseCurrently: localized(
    '現在表示中の認証済み3D姿勢からメッシュを生成できませんでした。3D表示の更新完了後に再試行してください。',
    'Could not generate a mesh from the authenticated pose currently displayed. Wait for the 3D view to finish updating, then retry.',
  ),
  currentPose3DMeshExportCancelled: localized(
    '現在姿勢の3Dメッシュ書き出しをキャンセルしました',
    'Current-pose 3D mesh export cancelled.',
  ),
  couldNotDiscardThe3DMeshExportPreview: localized(
    '3Dメッシュの書き出しプレビューを破棄できませんでした。',
    'Could not discard the 3D mesh export preview.',
  ),
  theProjectChangedRebuildTheExportFromTheCurrentPose: localized(
    '編集内容が変わったため、現在姿勢から書き出しデータを作り直してください。',
    'The project changed. Rebuild the export from the current pose.',
  ),
  saveLocationSelectionWasCancelledYouCanRetryWithThe: localized(
    '保存先の選択をキャンセルしました。同じ不変データで再試行できます。',
    'Save location selection was cancelled. You can retry with the same immutable data.',
  ),
  text3dMeshSaveLocationSelectionCancelled: localized(
    '3Dメッシュの保存先選択をキャンセルしました',
    '3D mesh save location selection cancelled.',
  ),
  the3DPoseOrProjectChangedOrTheFileCould: localized(
    '3D姿勢または編集内容が変わったか、ファイルを保存できませんでした。現在姿勢から作り直して再試行してください。',
    'The 3D pose or project changed, or the file could not be saved. Rebuild from the current pose and retry.',
  ),
  message0160: localized('{format}の内容と注意事項を確認してください。', ''),
  reviewTheFormatContentAndNotices: localized('', 'Review the {format} content and notices.'),
  couldNotPrepareTheInstructionsError: localized(
    '折り図を準備できませんでした: {error}',
    'Could not prepare the instructions: {error}',
  ),
  instructionExportErrorError: localized(
    '折り図書き出しエラー: {error}',
    'Instruction export error: {error}',
  ),
  couldNotBuildAnAnimationFromTheCurrentInstructionsReview: localized(
    '現在の手順からアニメーションを作成できませんでした。手順を確認して再試行してください。',
    'Could not build an animation from the current instructions. Review them and retry.',
  ),
  couldNotSafelyDiscardTheAnimationExport: localized(
    'アニメーション書き出しを安全に破棄できませんでした。',
    'Could not safely discard the animation export.',
  ),
  theProjectChangedRebuildFromTheCurrentInstructions: localized(
    'プロジェクトが変更されました。現在の手順から再作成してください。',
    'The project changed. Rebuild from the current instructions.',
  ),
  saveLocationSelectionWasCancelledYouCanRetryWithThe2: localized(
    '保存先の選択をキャンセルしました。同じ生成データで再試行できます。',
    'Save location selection was cancelled. You can retry with the same generated data.',
  ),
  exportedFileName2: localized('{fileName} を保存しました', 'Exported {fileName}'),
  theInstructionsChangedOrTheFileCouldNotBeSaved: localized(
    '手順が変更されたか、ファイルを保存できませんでした。再作成してから再試行してください。',
    'The instructions changed or the file could not be saved. Rebuild and retry.',
  ),
  progressCouldNotBeUpdatedErrorWaitingForTheGenerated: localized(
    '進捗表示を更新できませんでした: {error} 生成結果を待っています。',
    'Progress could not be updated: {error} Waiting for the generated result.',
  ),
  stoppingInstructionGeneration: localized('折り図の生成を中止しています。', 'Stopping instruction generation…'),
  instructionGenerationStopped: localized('折り図の生成を中止しました。', 'Instruction generation stopped.'),
  instructionGenerationHasAlreadyFinished: localized(
    '折り図の生成は終了済みです。',
    'Instruction generation has already finished.',
  ),
  instructionExportCancelled: localized('折り図の書き出しをキャンセルしました。', 'Instruction export cancelled.'),
  couldNotCancelError: localized('キャンセルを完了できませんでした: {error}', 'Could not cancel: {error}'),
  instructionCancellationErrorError: localized(
    '折り図キャンセルエラー: {error}',
    'Instruction cancellation error: {error}',
  ),
  theProjectChangedRebuildTheInstructionData: localized(
    '編集内容が変わったため、折り図データを作り直してください。',
    'The project changed. Rebuild the instruction data.',
  ),
  saveLocationSelectionWasCancelledYouCanSaveAgainFrom: localized(
    '保存先の選択をキャンセルしました。この画面からもう一度保存できます。',
    'Save location selection was cancelled. You can save again from this screen.',
  ),
  instructionSaveLocationSelectionCancelled: localized(
    '折り図の保存先選択をキャンセルしました。',
    'Instruction save location selection cancelled.',
  ),
  exportedFileName3: localized('{fileName}を書き出しました。', 'Exported {fileName}.'),
  couldNotExportTheInstructionsError: localized(
    '折り図を書き出せませんでした: {error}',
    'Could not export the instructions: {error}',
  ),
  returnedToTheNormalCreasePattern: localized(
    '通常の展開図に戻りました',
    'Returned to the normal crease pattern',
  ),
  generatingAndTransferring10000RealEdges: localized(
    '10,000本の実データを生成・転送中…',
    'Generating and transferring 10,000 real edges…',
  ),
  countEdgesBytesGenerationTransferResponseMsMsMeasuringCanvas: localized(
    '{count}本 · {bytes} · 生成+転送 {responseMs}ms · Canvas計測中…',
    '{count} edges · {bytes} · generation + transfer {responseMs} ms · measuring canvas…',
  ),
  countEdgesBytesGenerationTransferResponseMsMsConversionPreparationMsMs: localized(
    '{count}本 · {bytes} · 生成+転送 {responseMs}ms · 変換 {preparationMs}ms · UI準備 {uiMs}ms · 初描画 {drawMs}ms · {frames}f {fps} FPS · p95 {p95}ms',
    '{count} edges · {bytes} · generation + transfer {responseMs} ms · conversion {preparationMs} ms · UI preparation {uiMs} ms · initial draw {drawMs} ms · {frames}f {fps} FPS · p95 {p95} ms',
  ),
  untitledProject: localized('無題のプロジェクト', 'Untitled project'),
  projectActions: localized('プロジェクト操作', 'Project actions'),
  newShortcut: localized('新規 ({shortcut})', 'New ({shortcut})'),
  new: localized('新規', 'New'),
  undoShortcut: localized('元に戻す ({shortcut})', 'Undo ({shortcut})'),
  undo: localized('元に戻す', 'Undo'),
  redoShortcut: localized('やり直す ({shortcut})', 'Redo ({shortcut})'),
  redo: localized('やり直す', 'Redo'),
  vertexAtCenter: localized('中央に頂点', 'Vertex at center'),
  openShortcut: localized('開く ({shortcut})', 'Open ({shortcut})'),
  opening: localized('開いています…', 'Opening…'),
  open: localized('開く', 'Open'),
  openAnExpandedProjectFolderAfterValidatingItsManifestAnd: localized(
    'manifestとハッシュを検証して、展開済みプロジェクトフォルダーを開きます',
    'Open an expanded project folder after validating its manifest and hashes',
  ),
  checkingFolder: localized('フォルダー確認中…', 'Checking folder…'),
  openExpandedFolder: localized('展開フォルダーを開く', 'Open expanded folder'),
  analyzing: localized('解析中…', 'Analyzing…'),
  importFOLD: localized('FOLD取込', 'Import FOLD'),
  importSVG: localized('SVG取込', 'Import SVG'),
  generating: localized('生成中…', 'Generating…'),
  export: localized('書出し', 'Export'),
  exportTheCurrentlyDisplayed3DPoseAsAMidSurface: localized(
    '現在表示中の3D姿勢を中央面メッシュとして書き出します',
    'Export the currently displayed 3D pose as a mid-surface mesh',
  ),
  generating3D: localized('3D生成中…', 'Generating 3D…'),
  export3D: localized('3D書出し', 'Export 3D'),
  saveShortcut: localized('保存 ({shortcut})', 'Save ({shortcut})'),
  saving: localized('保存中…', 'Saving…'),
  save: localized('保存', 'Save'),
  saveAsShortcut: localized('別名保存 ({shortcut})', 'Save as ({shortcut})'),
  saveAs: localized('別名保存', 'Save as'),
  saveAnExpandedFolderInsideTheSelectedParentOnLocal: localized(
    '選択した親フォルダーへ展開形式で保存します。ローカルNTFS/ReFSでは同じプロジェクトの既存フォルダーを安全に置き換え、それ以外の保存先では新規保存だけを行います。別のプロジェクトは上書きしません',
    'Save an expanded folder inside the selected parent. On local NTFS/ReFS, an existing folder for the same project is replaced safely; other destinations allow only a new save. A different project is never overwritten',
  ),
  savingFolder: localized('展開保存中…', 'Saving folder…'),
  saveExpandedFolder: localized('展開フォルダー保存', 'Save expanded folder'),
  validate: localized('検証', 'Validate'),
  drawingTools: localized('作図ツール', 'Drawing tools'),
  select: localized('選択', 'Select'),
  mountainFold: localized('山折り', 'Mountain fold'),
  valleyFold: localized('谷折り', 'Valley fold'),
  auxiliaryLine: localized('補助線', 'Auxiliary line'),
  cut: localized('切断', 'Cut'),
  measure: localized('計測', 'Measure'),
  text2dCreasePattern: localized('2D 展開図', '2D crease pattern'),
  benchmarkCountEdges: localized('性能テスト · {count}本', 'Benchmark · {count} edges'),
  sizeCountEdges: localized('{size} · {count}本', '{size} · {count} edges'),
  tooManyIntersectionCandidatesZoomInAndTryAgain: localized(
    '交点候補が過密なため配置できません。拡大して再試行してください',
    'Too many intersection candidates. Zoom in and try again.',
  ),
  thisIntersectionClusterIsUnsupportedOrAmbiguousCheckForOverlapping: localized(
    '未対応または曖昧な交点クラスタのため配置できません。辺や頂点の重複を確認してください',
    'This intersection cluster is unsupported or ambiguous. Check for overlapping edges or vertices.',
  ),
  text3dPreview: localized('3D プレビュー', '3D preview'),
  autoRecord3DEdits: localized('3D操作を自動記録', 'Auto-record 3D edits'),
  issuesBlocking3D: localized('3D移行を妨げている問題', 'Issues blocking 3D'),
  resolveTheseCountIssuesBeforeEntering3DFolding: localized(
    '{count}件の問題を解消するまで3D折り操作へ移行できません。',
    'Resolve these {count} issues before entering 3D folding.',
  ),
  line: localized('線', 'Line'),
  fixedFace: localized('固定面', 'Fixed face'),
  unavailable: localized('選択不可', 'Unavailable'),
  blueOutlineFixed: localized('青枠・固定', 'Blue outline · fixed'),
  allHinges: localized('全ヒンジ', 'All hinges'),
  targetFold: localized('指定折り量', 'Target fold'),
  targetFoldForAllHingesDegrees: localized('全ヒンジの指定折り量（度）', 'Target fold for all hinges (degrees)'),
  targetFoldDegrees: localized('指定折り量（度）', 'Target fold (degrees)'),
  foldAmountByHinge: localized('ヒンジ別の折り量', 'Fold amount by hinge'),
  orangeOutlineDependentFaceCollisionUnchecked: localized(
    '橙枠=従属面・衝突未検証',
    'Orange outline = dependent face; collision unchecked',
  ),
  mountainFold2: localized('山折り', 'mountain fold'),
  valleyFold2: localized('谷折り', 'valley fold'),
  actionLabelIndexIn2DAnd3D: localized(
    '{index}番目の{label}を2D・3Dで{action}',
    '{action} {label} {index} in 2D and 3D',
  ),
  deselect: localized('選択解除', 'Deselect'),
  selectIn2DAnd3DEdgeId: localized('2D・3Dで選択: {edgeId}', 'Select in 2D and 3D: {edgeId}'),
  foldAmountForLabelIndex: localized('{index}番目の{label}の折り量', 'Fold amount for {label} {index}'),
  angleForLabelIndex: localized('{index}番目の{label}の角度', 'Angle for {label} {index}'),
  properties: localized('プロパティ', 'Properties'),
  selection: localized('選択要素', 'Selection'),
  mirrorSelection: localized('選択を対称編集', 'Mirror selection'),
  verticesVerticesEdgesEdges: localized(
    '頂点 {vertices}件・辺 {edges}件',
    '{vertices} vertices · {edges} edges',
  ),
  addCurrentSelection: localized('現在の選択を追加', 'Add current selection'),
  cancelCandidateGeneration: localized('候補生成をキャンセル', 'Cancel candidate generation'),
  cancel: localized('取消', 'Cancel'),
  operation: localized('処理', 'Operation'),
  duplicate: localized('複製', 'Duplicate'),
  move: localized('移動', 'Move'),
  twoPointMirrorAxis: localized('対称軸の2点', 'Two-point mirror axis'),
  checking: localized('検証中…', 'Checking…'),
  preflight: localized('事前検証', 'Preflight'),
  applyMirrorEdit: localized('対称編集を適用', 'Apply mirror edit'),
  readyReviewAndExplicitlyApplyTheEdit: localized(
    '適用できます。内容を確認して明示的に適用してください。',
    'Ready. Review and explicitly apply the edit.',
  ),
  name: localized('名前', 'Name'),
  memo: localized('メモ', 'Memo'),
  useCustomColor: localized('個別色を使用', 'Use custom color'),
  color: localized('色', 'Color'),
  saveElementDetails: localized('要素情報を保存', 'Save element details'),
  type: localized('種類', 'Type'),
  start: localized('始点', 'Start'),
  end: localized('終点', 'End'),
  length: localized('長さ', 'Length'),
  deleteBenchmarkLine: localized('性能データの線を削除', 'Delete benchmark line'),
  selectionMeasurementVertexMovementAndLineDeletionAreAvailableOn: localized(
    '1万本データ上で選択・計測・頂点移動・線削除を検証できます。',
    'Selection, measurement, vertex movement, and line deletion are available on the 10,000-edge data.',
  ),
  moveEntireLine: localized('線全体を移動', 'Move entire line'),
  horizontalOffsetUnit: localized('横移動量 ({unit})', 'Horizontal offset ({unit})'),
  verticalOffsetUnit: localized('縦移動量 ({unit})', 'Vertical offset ({unit})'),
  leftRightSymmetry: localized('左右対称編集', 'Left-right symmetry'),
  mirrorAxisXUnit: localized('対称軸 X ({unit})', 'Mirror axis X ({unit})'),
  applyLeftRightReflection: localized('左右反転を適用', 'Apply left-right reflection'),
  rotationalSymmetry: localized('回転対称編集', 'Rotational symmetry'),
  centerXUnit: localized('中心 X ({unit})', 'Center X ({unit})'),
  centerYUnit: localized('中心 Y ({unit})', 'Center Y ({unit})'),
  rotationAngle: localized('回転角度 (°)', 'Rotation angle (°)'),
  applyRotation: localized('回転を適用', 'Apply rotation'),
  linearArray: localized('線形配列', 'Linear array'),
  additionalCopies: localized('追加コピー数', 'Additional copies'),
  xOffsetMm: localized('X移動量 (mm)', 'X offset (mm)'),
  yOffsetMm: localized('Y移動量 (mm)', 'Y offset (mm)'),
  previewArray: localized('配列をプレビュー', 'Preview array'),
  verticesVerticesAndEdgesEdgeSeedsWillBeAddedThe: localized(
    '追加頂点 {vertices}、追加線分シード {edges}。確認するまで図面は変更されません。',
    '{vertices} vertices and {edges} edge seeds will be added. The drawing remains unchanged until confirmation.',
  ),
  confirmArray: localized('配列を確定', 'Confirm array'),
  cancel2: localized('キャンセル', 'Cancel'),
  radialArray: localized('放射配列', 'Radial array'),
  onlyNonBoundaryEndpointsOfTheSelectedLineCanBeUsedAsRotationCenter: localized(
    '選択線の非境界端点を回転中心として選択できます。候補がない場合は利用できません。',
    'Select a non-boundary endpoint of the selected line as the rotation center. This is unavailable when neither endpoint qualifies.',
  ),
  rotationAngle2: localized('回転角度', 'Rotation angle'),
  previewRadialArray: localized('放射配列をプレビュー', 'Preview radial array'),
  copiesCopiesWillBeAddedAfterConfirmation: localized(
    '{copies}個のコピーを確認後に追加します。',
    '{copies} copies will be added after confirmation.',
  ),
  confirmRadialArray: localized('放射配列を確定', 'Confirm radial array'),
  clearDirectionReference: localized('方向参照を解除', 'Clear direction reference'),
  setAsDirectionReference: localized('方向参照に設定', 'Set as direction reference'),
  splitBoundaryEdgeAtMidpoint: localized('輪郭辺を中点で分割', 'Split boundary edge at midpoint'),
  deleteLine: localized('線を削除', 'Delete line'),
  thisLineLayerIsLockedSelectionMeasurementAndReferencesRemain: localized(
    'この線のレイヤーは編集ロック中です。選択・計測・参照はできますが、図形は変更できません。',
    'This line layer is locked. Selection, measurement, and references remain available, but geometry cannot be changed.',
  ),
  moveTheNewlySelectedVertexAfterSplittingToEditThe: localized(
    '分割後に選択される新しい頂点を移動して、紙の輪郭を編集できます。',
    'Move the newly selected vertex after splitting to edit the paper boundary.',
  ),
  boundaryVertices: localized('境界頂点', 'Boundary vertices'),
  boundaryLines: localized('境界線', 'Boundary lines'),
  moveEntireFace: localized('面全体を移動', 'Move entire face'),
  addOrSplitAFace: localized('面を追加・分割', 'Add or split a face'),
  startVertex: localized('始点', 'Start vertex'),
  vertexIndexId: localized('頂点 {index}: {id}', 'Vertex {index}: {id}'),
  endVertex: localized('終点', 'End vertex'),
  splitLineType: localized('分割線種', 'Split line type'),
  cut2: localized('切断線', 'Cut'),
  splitAndAddFace: localized('分割して面を追加', 'Split and add face'),
  deleteOrMergeFace: localized('面を削除・統合', 'Delete or merge face'),
  sharedLineToRemove: localized('削除する共有線', 'Shared line to remove'),
  removeLineAndMergeFace: localized('共有線を削除して面を統合', 'Remove line and merge face'),
  thisFaceCannotMoveBecauseItsBoundaryIncludesALocked: localized(
    '面の境界にロック中のレイヤーが含まれるため移動できません。',
    'This face cannot move because its boundary includes a locked layer.',
  ),
  benchmarkVertex: localized('性能テスト頂点', 'Benchmark vertex'),
  dragTheBenchmarkVertexIn2DToMoveItAnd: localized(
    '性能データの頂点は2D上でドラッグして移動できます。',
    'Drag the benchmark vertex in 2D to move it and its incident lines.',
  ),
  vertexXCoordinateUnit: localized('頂点のX座標 ({unit})', 'Vertex X coordinate ({unit})'),
  vertexYCoordinateUnit: localized('頂点のY座標 ({unit})', 'Vertex Y coordinate ({unit})'),
  updateCoordinates: localized('座標を更新', 'Update coordinates'),
  legacyV1EdgeGeometryReferenceIsUnverified: localized(
    '旧V1の辺形状参照式は未検証です。保存済み座標を正本として表示していますが、現在の辺形状から再評価していません。座標の更新またはV2への昇格には、ユーザーによる明示的な座標再評価が必要です。この表示は変更権限を与えません。',
    'This legacy V1 edge-geometry reference is unverified. The saved coordinates remain canonical for display and have not been reevaluated from the current edge geometry. Updating the coordinates or upgrading to V2 requires explicit coordinate reevaluation by the user. This notice grants no mutation authority.',
  ),
  legacyV1PolarConstructionIsUnverified: localized(
    '旧V1の極座標作図式は、この実行環境では再検証されていません。保存済みの端点座標を正本として表示しています。決定論モデルへ昇格するには、長さと角度から端点を再作成してください。',
    'This legacy V1 polar construction has not been reverified in this runtime. Its saved endpoint coordinates remain canonical for display. Recreate the endpoint from its length and angle to upgrade it to the deterministic model.',
  ),
  deleteBoundaryVertexAndMergeEdges: localized(
    '輪郭頂点を削除して辺を統合',
    'Delete boundary vertex and merge edges',
  ),
  deleteVertex: localized('頂点を削除', 'Delete vertex'),
  constructionExpressionLengthLengthMmAngleAngleEvaluatedLengthValueMm: localized(
    '作図式: 長さ {length} mm / 角度 {angle}°（評価値 {lengthValue} mm / {angleValue}°）',
    'Construction expression: length {length} mm / angle {angle}° (evaluated {lengthValue} mm / {angleValue}°)',
  ),
  endpointByLengthAndAngle: localized('長さ・角度指定の終点', 'Endpoint by length and angle'),
  lengthFromTheStartVertexUnit: localized(
    '始点からの長さ ({unit})',
    'Length from the start vertex ({unit})',
  ),
  angleDegrees: localized('角度 (度)', 'Angle (degrees)'),
  angleFromTheStartVertexDegrees: localized('始点からの角度 (度)', 'Angle from the start vertex (degrees)'),
  lineType: localized('線種', 'Line type'),
  lineTypeForLengthAndAngleDrawing: localized(
    '長さ・角度指定作図の線種',
    'Line type for length and angle drawing',
  ),
  drawLineByLengthAndAngle: localized('長さと角度から線を作図', 'Draw line by length and angle'),
  drawToFirstTargetByAngle: localized('角度から最初の対象まで作図', 'Draw to first target by angle'),
  compassCircle: localized('コンパス円', 'Compass circle'),
  radius: localized('半径', 'Radius'),
  addCircleAtSelectedVertex: localized('選択頂点を中心に円を追加', 'Add circle at selected vertex'),
  clearCompassCircles: localized('コンパス円を消去', 'Clear compass circles'),
  countConstructionCirclesTheVertexToolSnapsToCircleLine: localized(
    '補助円 {count} 個。頂点ツールで円と線、または円同士の交点へスナップできます。',
    '{count} construction circles. The vertex tool snaps to circle-line and circle-circle intersections.',
  ),
  thisVertexIsConnectedToALineOnALocked: localized(
    'この頂点にはロック中のレイヤーの線が接続されているため、移動・削除できません。',
    'This vertex is connected to a line on a locked layer and cannot be moved or deleted.',
  ),
  aBoundaryNeedsAtLeastThreePointsCountCurrentlyThis: localized(
    '輪郭は最低3点必要です（現在{count}点）。この操作は元に戻せます。接続線がある場合など、安全に統合できない削除は拒否されます。',
    'A boundary needs at least three points ({count} currently). This action can be undone. Unsafe deletion, such as a vertex with connected lines, is rejected.',
  ),
  deleteConnectedLinesBeforeDeletingTheirVertex: localized(
    '接続線がある頂点は、線を削除してから削除します。',
    'Delete connected lines before deleting their vertex.',
  ),
  selectALineOrVertexOrAddAVertexBy: localized(
    '線または頂点を選択するか、座標を指定して頂点を追加します。',
    'Select a line or vertex, or add a vertex by coordinates.',
  ),
  newVertexXCoordinateUnit: localized('新しい頂点のX座標 ({unit})', 'New vertex X coordinate ({unit})'),
  newVertexYCoordinateUnit: localized('新しい頂点のY座標 ({unit})', 'New vertex Y coordinate ({unit})'),
  addVertexByCoordinates: localized('座標から頂点を追加', 'Add vertex by coordinates'),
  unlockTheDefaultLayerBeforeAddingAVertex: localized(
    '既定レイヤーがロックされているため頂点を追加できません。',
    'Unlock the default layer before adding a vertex.',
  ),
  selectALineOrVertex: localized('線または頂点を選択してください。', 'Select a line or vertex.'),
  projectMemo: localized('プロジェクトメモ', 'Project memo'),
  notes: localized('メモ', 'Notes'),
  saveMemo: localized('メモを保存', 'Save memo'),
  compareDesignCandidates: localized('設計候補の比較', 'Compare design candidates'),
  scoresUpToThreeCandidatesOnThisDeviceUsingThe: localized(
    '端末内で最大3件を同じ基準で評価します。これは候補の比較だけを行い、展開図を変更しません。',
    'Scores up to three candidates on this device using the same criteria. This comparison does not change the crease pattern.',
  ),
  estimateSymmetricParameters: localized('対称パラメータを推定', 'Estimate symmetric parameters'),
  adjustReadOnlyEstimate: localized('読み取り専用の推定値を調整', 'Adjust read-only estimate'),
  countCountScaleScaleSpacingSpacing: localized(
    '数 {count}・尺度 {scale}%・間隔 {spacing}%',
    'Count {count} · scale {scale}% · spacing {spacing}%',
  ),
  scaleScaleSpacingSpacingApproximationScoreComplexityComplexityRequiredCo: localized(
    '尺度 {scale}%・間隔 {spacing}%・近似 {score}・複雑度 {complexity}・必要数 {count}',
    'Scale {scale}% · spacing {spacing}% · approximation {score} · complexity {complexity} · required count {count}',
  ),
  selectThisCandidate: localized('この候補を選択', 'Select this candidate'),
  scale1045: localized('尺度（10–45%）', 'Scale (10–45%)'),
  spacing2080: localized('間隔（20–80%）', 'Spacing (20–80%)'),
  confirmDesignParameters: localized('確認して設計条件へ保存', 'Confirm design parameters'),
  scoringCandidates: localized('候補を評価中…', 'Scoring candidates…'),
  scoreCandidates: localized('候補を評価', 'Score candidates'),
  evaluating27Designs: localized('27案を評価中…', 'Evaluating 27 designs…'),
  evaluateTop3Of27Designs: localized('27案から上位3案を評価', 'Evaluate top 3 of 27 designs'),
  top3FromThe27DesignSearch: localized('27案探索の上位3案', 'Top 3 from the 27-design search'),
  countDesignsEvaluatedGridHashHash: localized(
    '{count}案を評価・格子ハッシュ {hash}',
    '{count} designs evaluated · grid hash {hash}',
  ),
  strictCandidateAuthorityComparison: localized(
    '候補適用権限の厳密比較',
    'Strict candidate authority comparison',
  ),
  creases: localized('折り線', 'Creases'),
  steps: localized('手順', 'Steps'),
  localProof: localized('局所証明', 'Local proof'),
  globalProof: localized('大域証明', 'Global proof'),
  pathProof: localized('経路証明', 'Path proof'),
  text3dShape: localized('3D形状', '3D shape'),
  paperEfficiency: localized('紙効率', 'Paper efficiency'),
  selectExactCandidateId: localized('厳密候補 {id} を選択', 'Select exact candidate {id}'),
  certifiedOnApply: localized('適用時に認証', 'Certified on apply'),
  blocked: localized('ブロック', 'Blocked'),
  notMeasured: localized('未計測', 'Not measured'),
  revalidateAndApplySelectedCandidate: localized(
    '選択候補を再検証して適用',
    'Revalidate and apply selected candidate',
  ),
  designIdPrimaryScoreScore1000: localized(
    '案 {id}・一次評価 {score}/1000',
    'Design {id} · primary score {score}/1000',
  ),
  strictLocalImprovementsImprovementsIterationsFromStartsStarts: localized(
    '局所改善 {improvements}/{iterations}',
    'Strict local improvements {improvements}/{iterations} from {starts} starts',
  ),
  scaleScaleSpacingSpacingDetailDetail: localized(
    '尺度 {scale}%・間隔 {spacing}%・詳細度 {detail}',
    'Scale {scale}% · spacing {spacing}% · detail {detail}',
  ),
  localLocalGlobalGlobalComplexityComplexity100: localized(
    '局所 {local}・大域 {global}・複雑度 {complexity}/100',
    'Local {local} · global {global} · complexity {complexity}/100',
  ),
  paperEfficiencyPaper100: localized('紙効率 {paper}/100', 'Paper efficiency {paper}/100'),
  penaltiesScaleScaleSpacingSpacingDetailDetail: localized(
    '減点: 尺度 {scale}・間隔 {spacing}・詳細度 {detail}',
    'Penalties: scale {scale} · spacing {spacing} · detail {detail}',
  ),
  outcomeReasonShapeDifferenceShape: localized(
    '判定理由 {reason}・形状差 {shape}',
    'Outcome {reason} · shape difference {shape}',
  ),
  contourPlacementWitnessBodyBodyPointsLocalLocalVerticesVertices: localized(
    '輪郭配置証明: 胴体 {body}点・局所 {local}・頂点 {vertices}・折線 {creases}',
    'Contour placement witness: body {body} points · local {local} · vertices {vertices} · creases {creases} · Hausdorff-like error {error}/1000000',
  ),
  genericFeatureTopologyWitnessFeatures: localized(
    '汎用部位topology証明: {features}',
    'Generic feature topology witness: {features}',
  ),
  confirmedTreeSkeletonBranchesAuthorityDigest: localized(
    '確認済みtree skeleton: {branches}・authority {digest}',
    'Confirmed tree skeleton: {branches}; authority {digest}',
  ),
  revalidateAndApplyThisDesign: localized('再検証してこの案を適用', 'Revalidate and apply this design'),
  initialDesignTreatsBulgesAsTargetShapeApproximationsAndDoes: localized(
    '初期設計では膨らみを目標形状への近似として扱い、紙の弾性は計算しません。',
    'Initial design treats bulges as target-shape approximations and does not compute paper elasticity.',
  ),
  designCandidatesInScoreOrder: localized('評価順の設計候補', 'Design candidates in score order'),
  recommended: localized('推奨案', 'Recommended'),
  shapeFocused: localized('完成形重視案', 'Shape-focused'),
  foldabilityFocused: localized('折りやすさ重視案', 'Foldability-focused'),
  shapeShapeFoldabilityFoldabilityStepsStepsPaperEfficiencyPaper: localized(
    '完成形 {shape}・折りやすさ {foldability}・工程数 {steps}・紙効率 {paper}',
    'Shape {shape} · foldability {foldability} · steps {steps} · paper efficiency {paper}',
  ),
  weightedContributionsShapeShapeFoldabilityFoldabilityStepsStepsPaperEffi: localized(
    '重み付き寄与: 形状 {shape}・折りやすさ {foldability}・工程 {steps}・紙効率 {paper}',
    'Weighted contributions: shape {shape} · foldability {foldability} · steps {steps} · paper efficiency {paper}',
  ),
  targetShapeApproximationTarget100: localized(
    '目標形状への近似 {target}/100',
    'Target-shape approximation {target}/100',
  ),
  generateOneAdditionalCandidate: localized('追加候補を1件生成', 'Generate one additional candidate'),
  generateAndCompareAnotherCandidate: localized(
    '追加候補を生成して比較',
    'Generate and compare another candidate',
  ),
  generatedCreasePatternAndInstructionCandidates: localized(
    '生成された展開図と手順の候補',
    'Generated crease-pattern and instruction candidates',
  ),
  image3DAgreementAgreement100ExtentErrorError100Result: localized(
    '画像/3D一致度 {agreement}/100・範囲誤差 {error}/100・{result}',
    'Image/3D agreement {agreement}/100; extent error {error}/100; {result}',
  ),
  theBoundedTwoSourceComparisonAgrees: localized(
    '2資料の上限付き比較は一致しました。',
    'The bounded two-source comparison agrees.',
  ),
  imageAndGLBDisagreeCandidateApplyIsBlocked: localized(
    '画像とGLBが不一致のため候補適用をブロックしました。',
    'Image and GLB disagree; candidate apply is blocked.',
  ),
  referenceConsensus: localized('参照資料の合意', 'Reference consensus'),
  referenceConsensusScore100PairsPairComparisonsDisagreementsDisagreements: localized(
    '参照資料の合意度 {score}/100・{pairs}組を比較・不一致 {disagreements}件。',
    'Reference consensus {score}/100; {pairs} pair comparisons; {disagreements} disagreements.',
  ),
  componentAwareReferenceComparisons: localized(
    '部品別の参照資料比較',
    'Component-aware reference comparisons',
  ),
  references: localized('参照資料', 'References'),
  components: localized('部品', 'Components'),
  extent: localized('範囲', 'Extent'),
  branches: localized('分岐', 'Branches'),
  result: localized('結果', 'Result'),
  componentMismatch: localized('部品不一致', 'component mismatch'),
  extentMismatch: localized('範囲不一致', 'extent mismatch'),
  branchMismatch: localized('分岐不一致', 'branch mismatch'),
  withinAllThresholds: localized('全しきい値内', 'within all thresholds'),
  referenceLeftReferenceRight: localized(
    '参照 {left} / 参照 {right}',
    'Reference {left} / Reference {right}',
  ),
  readOnlyComponentHighlightALeftExtentLeftBranchesBranchesBRightExtent: localized(
    '読み取り専用部品強調: A {leftExtent}・{leftBranches}分岐、B {rightExtent}・{rightBranches}分岐。',
    'Read-only component highlight: A {leftExtent}, {leftBranches} branches; B {rightExtent}, {rightBranches} branches.',
  ),
  oneExplicitlyExcludedReferenceIsOmittedFromThisTable: localized(
    '明示的に除外した参照資料1件は表に含まれません。',
    'One explicitly excluded reference is omitted from this table.',
  ),
  excludeOneOutlier: localized('外れ値を1件除外', 'Exclude one outlier'),
  excludeReferenceIndex: localized('参照 {index} を除外', 'Exclude reference {index}'),
  includeAllReferences: localized('すべての参照資料を含める', 'Include all references'),
  geometryValidationFailed: localized('形状検証に失敗しました。', 'Geometry validation failed.'),
  globalFlatFoldabilityIsProven: localized(
    '大域平坦折り可能性が証明されました。',
    'Global flat foldability is proven.',
  ),
  globalFlatFoldabilityIsProvenImpossible: localized(
    '大域平坦折りが不可能と証明されました。',
    'Global flat foldability is proven impossible.',
  ),
  globalValidationIsIndeterminateBecauseItsResourceLimitWasReached: localized(
    '大域検証は資源上限に達したため未確定です。',
    'Global validation is indeterminate because its resource limit was reached.',
  ),
  globalValidationIsIndeterminateBecauseItsTimeLimitWasReached: localized(
    '大域検証は時間上限に達したため未確定です。',
    'Global validation is indeterminate because its time limit was reached.',
  ),
  globalFlatFoldabilityValidationWasIndeterminate: localized(
    '大域平坦折り検証では結論を確定できませんでした。',
    'Global flat-foldability validation was indeterminate.',
  ),
  localFlatFoldabilityNecessaryConditionsAreViolated: localized(
    '局所平坦折りの必要条件に違反しています。',
    'Local flat-foldability necessary conditions are violated.',
  ),
  localFlatFoldabilityAnalysisWasBlocked: localized(
    '局所平坦折り解析を実行できませんでした。',
    'Local flat-foldability analysis was blocked.',
  ),
  localFlatFoldabilityNecessaryConditionsAreSatisfied: localized(
    '局所平坦折りの必要条件を満たしています。',
    'Local flat-foldability necessary conditions are satisfied.',
  ),
  localFlatFoldabilityIsIndeterminateForThisCandidate: localized(
    'この候補の局所平坦折り可否は未確定です。',
    'Local flat-foldability is indeterminate for this candidate.',
  ),
  candidate: localized('候補', 'Candidate'),
  candidateCreasePatternPreview: localized('候補の展開図プレビュー', 'Candidate crease-pattern preview'),
  candidateFoldingInstructions: localized('候補の折り手順', 'Candidate folding instructions'),
  createTheSymmetricFourLegBaseFromTheSharedCenter: localized(
    '対称4本脚の基本線を中央から作成します。',
    'Create the symmetric four-leg base from the shared center.',
  ),
  createTheBilateralWingBaseFromTheSharedCenter: localized(
    '左右対称の翼の基本線を中央から作成します。',
    'Create the bilateral wing base from the shared center.',
  ),
  createTheBilateralBirdWingBase: localized(
    '左右対称の鳥の翼ベースを作ります。',
    'Create the bilateral bird-wing base.',
  ),
  createTheAsymmetricBirdBaseBoundToIndividualLandmarks: localized(
    '個別ランドマークに結合した非対称の鳥ベースを作ります。',
    'Create the asymmetric bird base bound to individual landmarks.',
  ),
  createTheAsymmetricFourLegBaseBoundToFourIndividual: localized(
    '4本の個別ランドマークに結合した非対称の脚ベースを作ります。',
    'Create the asymmetric four-leg base bound to four individual landmarks.',
  ),
  bindTenOrderedInsectLandmarksToTheCertifiedFourRay: localized(
    '10個の意味ランドマークを証明済み4放射へ結合します。',
    'Bind ten ordered insect landmarks to the certified four-ray base.',
  ),
  bindTheHeadTailAndLeftRightFinsToThe: localized(
    '頭・尾・左右のひれを証明済み4放射へ結合します。',
    'Bind the head, tail, and left/right fins to the certified four-ray base.',
  ),
  createTheBilateralFishFinBase: localized(
    '左右対称の魚のひれベースを作ります。',
    'Create the bilateral fish-fin base.',
  ),
  createTheBilateralLongEarBase: localized(
    '左右対称の長い耳のベースを作ります。',
    'Create the bilateral long-ear base.',
  ),
  createTheBilateralHornBase: localized('左右対称の角のベースを作ります。', 'Create the bilateral horn base.'),
  createTheBilateralInsectAntennaBase: localized(
    '左右対称の昆虫の触角ベースを作ります。',
    'Create the bilateral insect-antenna base.',
  ),
  createOneBilateralInsectLegPairBase: localized(
    '昆虫の左右対称な脚1組のベースを作ります。',
    'Create one bilateral insect leg-pair base.',
  ),
  foldInHalfOnTheVerticalCenterLine: localized(
    '縦の中心線で二つ折りします。',
    'Fold in half on the vertical center line.',
  ),
  foldInHalfOnTheHorizontalCenterLine: localized(
    '横の中心線で二つ折りします。',
    'Fold in half on the horizontal center line.',
  ),
  foldOnTheDiagonal: localized('対角線で折ります。', 'Fold on the diagonal.'),
  targetPartsUsedByThisCandidate: localized('候補に使用した目標部品', 'Target parts used by this candidate'),
  head: localized('頭', 'head'),
  torso: localized('胴体', 'torso'),
  leg: localized('脚', 'leg'),
  horn: localized('角', 'horn'),
  ear: localized('耳', 'ear'),
  wing: localized('翼', 'wing'),
  fin: localized('ひれ', 'fin'),
  antenna: localized('触角', 'antenna'),
  tail: localized('尾', 'tail'),
  stickSkeletonUsedByThisCandidate: localized(
    '候補に使用した棒状骨格',
    'Stick skeleton used by this candidate',
  ),
  thisCandidateUsesTheSelectedProjectReferenceImageAsTarget: localized(
    'この候補は選択したプロジェクト内の参照画像を目標入力として使用しています。',
    'This candidate uses the selected project reference image as target input.',
  ),
  thisIsAReadOnlyCandidateItDoesNotBecome: localized(
    'これは読取専用の候補です。確認・適用操作を行うまでプロジェクト権限にはなりません。',
    'This is a read-only candidate. It does not become project authority without a separate review and apply action.',
  ),
  candidateValidationResult: localized('候補の検証結果', 'Candidate validation result'),
  sufficientProof: localized('十分条件の証明', 'Sufficient proof'),
  necessaryConditionValidation: localized('必要条件の検証', 'Necessary-condition validation'),
  indeterminate: localized('判定未確定', 'Indeterminate'),
  warningApplyingItDoesNotGuaranteeFlatFoldability: localized(
    '警告: 適用しても平坦に折れることは保証されません。',
    'Warning: applying it does not guarantee flat foldability.',
  ),
  readOnlyShapeApproximationToReferenceGLBScore100: localized(
    '参照GLBへの読み取り専用形状近似: {score}/100',
    'Read-only shape approximation to reference GLB: {score}/100',
  ),
  usesActualBboxAreaAndPrincipalAxisFromTheCertified: localized(
    '証明済みflat surfaceの実bbox・面積・主軸を使用しています。',
    'Uses actual bbox, area, and principal axis from the certified flat surface.',
  ),
  differenceTheCreaseCandidateHasNoSurfaceMeshSoOnly: localized(
    '差分理由: 折り線候補には表面メッシュがないため、同じ量子化bbox・面積比・主軸のうち比較可能な特徴だけを使用しています。',
    'Difference: the crease candidate has no surface mesh, so only comparable features from the same quantized bbox, area ratio, and principal-axis method are used.',
  ),
  componentAwareShapeScoreBreakdown: localized(
    '部品別の形状スコア内訳',
    'Component-aware shape score breakdown',
  ),
  reviewAndApplyThisBoundedGeneratedCandidate: localized(
    '対角折り候補を確認して適用',
    'Review and apply this bounded generated candidate',
  ),
  reviewAndApplyThisCandidate: localized('この候補を確認して適用', 'Review and apply this candidate'),
  saveAnAnimalOrInsectTargetCategoryFirst: localized(
    '先に動物または昆虫の目標カテゴリを保存してください。',
    'Save an animal or insect target category first.',
  ),
  saveOneHeadAndOneTorsoAsRequiredTargetParts: localized(
    '頭1個と胴体1個を目標部品として保存してください。',
    'Save one head and one torso as required target parts.',
  ),
  theAnimalTemplateRequiresOneHeadOneTorsoFourLegs: localized(
    '動物テンプレートには頭1・胴体1・脚4・棒状骨格・左右対称の4突起目標が必要です。',
    'The animal template requires one head, one torso, four legs, a saved stick skeleton, and a bilateral four-part protrusion target.',
  ),
  theInsectTemplateRequiresOneHeadOneTorsoTwoWings: localized(
    '昆虫テンプレートには頭1・胴体1・翼2・棒状骨格・左右対称の2突起目標が必要です。',
    'The insect template requires one head, one torso, two wings, a saved stick skeleton, and a bilateral two-part protrusion target.',
  ),
  theReferenceImageWasRemovedOrChangedSelectAnotherUnderlay: localized(
    '参照画像が削除または変更されています。別の配置画像を選択してください。',
    'The reference image was removed or changed. Select another underlay image.',
  ),
  allowValleyOrMountainFoldsToGeneratePlans: localized(
    '谷折りまたは山折りを許可してください。',
    'Allow valley or mountain folds to generate plans.',
  ),
  theInputExceedsTheGenerationWorkLimit: localized(
    '入力が生成処理の上限を超えています。',
    'The input exceeds the generation work limit.',
  ),
  theInitialGeneratorSupportsRectangularSingleSheetPaperOnly: localized(
    '初版の生成器は長方形の一枚紙だけに対応します。',
    'The initial generator supports rectangular single-sheet paper only.',
  ),
  beginnerDesignPriorities: localized('かんたん設計の評価方針', 'Beginner design priorities'),
  setsHowFutureOnDeviceDesignCandidatesAreScoredIt: localized(
    '将来の端末内自動設計で候補を評価する方針です。現在の展開図は変更しません。',
    'Sets how future on-device design candidates are scored. It does not change the current crease pattern.',
  ),
  savedOutlineEditAuthorityCountEditsImageDigestDigest: localized(
    '保存済み輪郭編集権限: {count}件・画像digest {digest}',
    'Saved outline edit authority: {count} edits; image digest {digest}',
  ),
  savedGenericTreeNameOriginSourceOrientationOrientationGeneratorV: localized(
    '保存済み一般木候補「{name}」の由来: {source}・{orientation}向き・generator v{version}・表示専用（再適用権限なし）',
    'Saved generic-tree “{name}” origin: {source} · {orientation} orientation · generator v{version} · display only; no apply authority',
  ),
  readOnlyFoldingInstructionProposal: localized(
    '読み取り専用の折り手順案',
    'Read-only folding instruction proposal',
  ),
  confirmAndAppendToInstructions: localized('確認して折り手順へ追加', 'Confirm and append to instructions'),
  evaluationPreset: localized('評価プリセット', 'Evaluation preset'),
  balanced: localized('バランス', 'Balanced'),
  shapeFidelityPriority: localized('完成形への近さ優先', 'Shape fidelity priority'),
  foldabilityPriority: localized('折りやすさ優先', 'Foldability priority'),
  currentWeightsShapeShapeFoldabilityFoldabilityStepsStepsPaperEfficiency: localized(
    '現在の重み: 完成形 {shape}%・折りやすさ {foldability}%・工程数 {steps}%・紙効率 {paper}%',
    'Current weights: shape {shape}% · foldability {foldability}% · steps {steps}% · paper efficiency {paper}%',
  ),
  targetShapeCategory: localized('目標形状カテゴリ', 'Target shape category'),
  selectACategory: localized('カテゴリを選択', 'Select a category'),
  animal: localized('動物', 'Animal'),
  insect: localized('昆虫', 'Insect'),
  customObject: localized('カスタム対象', 'Custom object'),
  customObjectDisplayName: localized('カスタム対象の表示名', 'Custom object display name'),
  displayMetadataOnlyItDoesNotAffectGeneratorAuthorityOr: localized(
    '表示専用です。生成権限や候補スコアには影響しません。1〜64文字で入力してください。',
    'Display metadata only; it does not affect generator authority or candidate scoring. Enter 1–64 characters.',
  ),
  animalAndInsectUseNamedTemplatesCustomObjectIsRouted: localized(
    '初版で対応する目標形状は動物と昆虫だけです。未対応カテゴリは推測しません。',
    'Animal and insect use named templates. Custom object is routed only to the bounded generic-tree candidate.',
  ),
  referenceImage: localized('参照画像', 'Reference image'),
  none2: localized('使用しない', 'None'),
  underlayImageIndex: localized('配置画像 {index}', 'Underlay image {index}'),
  onlyPNGJPEGImagesAlreadyPlacedInThisProjectCan: localized(
    '既にプロジェクトへ配置したPNG/JPEGだけを参照できます。参照を解除するまで画像の削除・差し替えはできません。画像内容を自動推測しません。3Dモデルの目標入力は初版では未対応です。',
    'Only PNG/JPEG images already placed in this project can be referenced. Clear the reference before removing or replacing that image. Image contents are not inferred. 3D model targets are not supported in the initial release.',
  ),
  import3DReferenceModel: localized('3D参照モデルを読み込む', 'Import 3D reference model'),
  cancelImageRecognition: localized('画像認識をキャンセル', 'Cancel image recognition'),
  aGLB20ModelIsAReadOnlyVisual: localized(
    'GLB 2.0モデルは読み取り専用の視覚参照です。形状の自動認識や折り設計の生成権限は与えません。',
    'A GLB 2.0 model is a read-only visual reference. It grants no automatic recognition or fold-generation authority.',
  ),
  project3DReferenceAssets: localized('プロジェクトの3D参照資料', 'Project 3D reference assets'),
  aValidated3DReferenceModelIsAttached: localized(
    '安全性を検証した3D参照モデルが設定されています。',
    'A validated 3D reference model is attached.',
  ),
  hide3DReferencePreview: localized('3D参照表示を隠す', 'Hide 3D reference preview'),
  show3DReferencePreview: localized('3D参照表示を開く', 'Show 3D reference preview'),
  suggestRangesFromSafeGeometryFeatures: localized(
    '安全特徴から範囲候補を作成',
    'Suggest ranges from safe geometry features',
  ),
  thisIsNot3DRecognitionItIsAReadOnly: localized(
    'これは3D自動認識ではありません。境界箱・三角形面積・集約法線だけを使う読み取り専用候補です。',
    'This is not 3D recognition. It is a read-only suggestion using only the bounding box, triangle area, and aggregate normals.',
  ),
  countProtrusionsLengthLengthMmThicknessThicknessMm: localized(
    '突起数 {count}、長さ {length} mm、太さ {thickness} mm',
    '{count} protrusions, length {length} mm, thickness {thickness} mm',
  ),
  general3DProposalQualityScore100PrincipalExtentsXY: localized(
    '一般3D候補: 品質 {score}/100・主軸 {x}/{y}/{z}・突起候補 {protrusions}/32・簡略骨格 {bars} 本',
    'General 3D proposal: quality {score}/100 · principal extents {x}/{y}/{z} · {protrusions}/32 protrusion candidates · {bars} simplified bars',
  ),
  general3DProposalInsufficiencyReasons: localized(
    '一般3D候補の不足理由: {reasons}',
    'General 3D proposal insufficiency: {reasons}',
  ),
  explicitlyAssignMeasuredSurfaceRangesTo28Parts: localized(
    '測定済みsurface範囲を2〜8部位へ明示割当',
    'Explicitly assign measured surface ranges to 2–8 parts',
  ),
  assignSurfaceRangeRangeIdToPartPartId: localized(
    'surface範囲 {rangeId} を部位 {partId} に割り当てる',
    'Assign surface range {rangeId} to part {partId}',
  ),
  surfaceRangeIdCenterXYZLengthLengthMm: localized(
    'surface範囲 {id}: 中心 ({x},{y},{z})・長さ {length} mm',
    'Surface range {id}: center ({x},{y},{z}), length {length} mm',
  ),
  partId: localized(' → 部位 {id}', ' → Part {id}'),
  triangleIndicesAddRemoveAdjacentFacesOnly: localized(
    ' 三角形番号（隣接面のみ追加・除外）',
    ' Triangle indices (add/remove adjacent faces only)',
  ),
  surfaceRangeRangeIdTriangleIndices: localized(
    'surface範囲 {rangeId} の三角形番号',
    'Surface range {rangeId} triangle indices',
  ),
  bulgeAmountMm: localized('膨らみ量 (mm)', 'Bulge amount (mm)'),
  onlyGLBMeasuredRangesAreShownDuplicateUnconfirmedOrTampered: localized(
    'GLBから測定された範囲だけを表示します。重複・未確認・改ざんされた範囲はネイティブ側で拒否されます。',
    'Only GLB-measured ranges are shown. Duplicate, unconfirmed, or tampered ranges are rejected natively.',
  ),
  confirmAndApplySuggestedRanges: localized('確認して範囲候補を適用', 'Confirm and apply suggested ranges'),
  editableBodyContourBodyPointsLocalContoursLocal: localized(
    '編集可能な胴体輪郭 {body} 点・局所輪郭 {local} 件',
    'Editable body contour: {body} points; local contours: {local}',
  ),
  reviewAndCopyContoursToEditor: localized('確認して輪郭を編集欄へコピー', 'Review and copy contours to editor'),
  reviewAndCopyGeneral3DProposalToEditor: localized(
    '確認して一般3D候補を編集欄へコピー',
    'Review and copy general 3D proposal to editor',
  ),
  reviewedComponentBridgeOverrides: localized(
    '確認済み部品ブリッジの上書き',
    'Reviewed component bridge overrides',
  ),
  readOnly3DReferenceModel: localized('読み取り専用3D参照モデル', 'Read-only 3D reference model'),
  recognizing: localized('認識中…', 'Recognizing…'),
  recognizeMarkerPNG: localized('マーカーPNGを認識', 'Recognize marker PNG'),
  recognizeOutlineFromImage: localized('一般画像から輪郭を認識', 'Recognize outline from image'),
  silhouetteAlphaThreshold: localized('輪郭アルファしきい値', 'Silhouette alpha threshold'),
  silhouetteLumaThreshold: localized('輪郭輝度しきい値', 'Silhouette luma threshold'),
  silhouetteForegroundPolarity: localized('輪郭の前景極性', 'Silhouette foreground polarity'),
  darkOnLight: localized('明背景の暗い形', 'Dark on light'),
  lightOnDark: localized('暗背景の明るい形', 'Light on dark'),
  alphaOnly: localized('アルファのみ', 'Alpha only'),
  silhouetteCropROI: localized('シルエットの切り抜き範囲', 'Silhouette crop ROI'),
  silhouetteCropROI2: localized('輪郭クロップ範囲', 'Silhouette crop ROI'),
  useCrop: localized('クロップを使用', 'Use crop'),
  resetToFullImage: localized('画像全体へ戻す', 'Reset to full image'),
  silhouetteOrientation: localized('輪郭画像の向き', 'Silhouette orientation'),
  resetOrientation: localized('向きをリセット', 'Reset orientation'),
  silhouetteMirror: localized('シルエットの反転', 'Silhouette mirror'),
  silhouetteMirror2: localized('輪郭画像の反転', 'Silhouette mirror'),
  mirrorHorizontally: localized('左右反転', 'Mirror horizontally'),
  mirrorVertically: localized('上下反転', 'Mirror vertically'),
  resetMirror: localized('反転をリセット', 'Reset mirror'),
  boundedPNGOrJPEGInputProducesAReadOnlyOutline: localized(
    '認識結果は読取専用の案です。編集欄へコピーしても、保存するまでプロジェクトは変更されません。',
    'Bounded PNG or JPEG input produces a read-only outline proposal. It grants no automatic design authority; copying remains unsaved until you save.',
  ),
  showOutlineCandidates: localized('複数の輪郭候補を表示', 'Show outline candidates'),
  readOnlyOutlineCandidates: localized('読み取り専用の輪郭候補', 'Read-only outline candidates'),
  candidatesExposeOnlyBoundsAreaAndReasonTheyGrantNo: localized(
    '候補は境界・面積・判定理由だけを示し、自動生成の権限を与えません。',
    'Candidates expose only bounds, area, and reason. They grant no generation authority.',
  ),
  areaAreaPxBoundsMinXMinYMaxXMaxYReasonReason: localized(
    '面積 {area}px・境界 ({minX},{minY})–({maxX},{maxY})・理由 {reason}',
    'Area {area}px · bounds ({minX},{minY})–({maxX},{maxY}) · reason {reason}',
  ),
  solidComponent: localized('十分な連結領域', 'solid component'),
  smallComponent: localized('小さい連結領域', 'small component'),
  confirmAndCopyToTarget: localized('確認して目標へコピー', 'Confirm and copy to target'),
  suggestParts: localized('部位候補を提案', 'Suggest parts'),
  explicitPartAssignments: localized('部位の明示割当', 'Explicit part assignments'),
  candidateId: localized('候補 {id}', 'Candidate {id}'),
  torso2: localized('胴体', 'Torso'),
  head2: localized('頭', 'Head'),
  leg2: localized('脚', 'Leg'),
  wing2: localized('翼', 'Wing'),
  fin2: localized('ひれ', 'Fin'),
  ear2: localized('耳', 'Ear'),
  horn2: localized('角', 'Horn'),
  antenna2: localized('触角', 'Antenna'),
  tail2: localized('尾', 'Tail'),
  verticalSplitPositionXPx: localized('縦分割位置 X (px)', 'Vertical split position X (px)'),
  excludeAsImageNoise: localized('ノイズ候補として除外', 'Exclude as image noise'),
  excludedImageCandidates: localized('除外した画像候補', 'Excluded image candidates'),
  restoredCandidatesRemainSemanticallyUnconfirmedAndCannotGenerateADesign: localized(
    '復帰しても部位の意味は未確認のままです。確認するまで生成には使われません。',
    'Restored candidates remain semantically unconfirmed and cannot generate a design until you confirm the assignments.',
  ),
  restoreCandidateIdWithItsOriginalOutlineEvidence: localized(
    '候補 {id} を元の輪郭証拠付きで復帰',
    'Restore candidate {id} with its original outline evidence',
  ),
  outlineComponentEditProposal: localized('輪郭成分の編集案', 'Outline component edit proposal'),
  splitAndMergeEditsAreNonAuthoritativeProposalsBoundTo: localized(
    '分割・結合は元画像digestに束縛された非権威的な案です。確認するまで生成へ反映されません。',
    'Split and merge edits are non-authoritative proposals bound to the source-image digest. They affect generation only after explicit confirmation.',
  ),
  splitFirstPartCandidate: localized('最初の部位候補を二分割', 'Split first part candidate'),
  mergeFirstTwoPartCandidates: localized('最初の二部位候補を結合', 'Merge first two part candidates'),
  theImageProvesOnlyEachCandidateOutlinePartMeaningsCome: localized(
    '画像は各候補の輪郭だけを証明します。部位の意味は、ここで確認した割当だけを使用します。',
    'The image proves only each candidate outline. Part meanings come only from the assignments you confirm here.',
  ),
  confirmTargetParts: localized('確認して目標部位へ反映', 'Confirm target parts'),
  recognitionProposalPreview: localized('認識案のプレビュー', 'Recognition proposal preview'),
  imageWidthHeightPxPartsPartsSegmentsSkeletonBars: localized(
    '画像 {width} × {height} px・部品 {parts} 個・骨格 {segments} 本',
    'Image {width} × {height} px · {parts} parts · {segments} skeleton bars',
  ),
  recognizedShapeBoundsAndSkeleton: localized(
    '認識された形状範囲と骨格',
    'Recognized shape bounds and skeleton',
  ),
  copyToEditableFields: localized('編集欄へコピー', 'Copy to editable fields'),
  recognizedContoursBodyBodyPointsAndLocalLocalContoursConfirmation: localized(
    '認識輪郭: 胴体 {body} 点・局所 {local} 件（コピー前に確認します）',
    'Recognized contours: {body} body points and {local} local contours; confirmation is required before copying.',
  ),
  contourConfidenceScore100ReasonsReasons: localized(
    '輪郭信頼度 {score}/100・理由 {reasons}',
    'Contour confidence {score}/100 · reasons {reasons}',
  ),
  skeletonProposalQuality: localized('骨格候補の品質', 'Skeleton proposal quality'),
  skeletonQualityScore100FullyOfflineDistanceAxisApproximationLimit: localized(
    '骨格品質 {score}/100・完全オフライン距離軸近似・最大 {limit} 本',
    'Skeleton quality {score}/100 · fully offline distance-axis approximation · {limit} bars maximum',
  ),
  insufficiencyReasonsReasons: localized('不足理由: {reasons}', 'Insufficiency reasons: {reasons}'),
  confirmRecognizedProtrusions: localized('認識部位の確認', 'Confirm recognized protrusions'),
  protrusionIdLocalContourPointsPoints: localized(
    '部位 {id}・局所輪郭 {points}点',
    'Protrusion {id} · local contour {points} points',
  ),
  targetShapeParts: localized('目標形状の部品', 'Target shape parts'),
  legs: localized('脚', 'Legs'),
  horns: localized('角', 'Horns'),
  ears: localized('耳', 'Ears'),
  wings: localized('翼', 'Wings'),
  tails: localized('尾', 'Tails'),
  targetBodySizeOptional: localized('胴体の目標寸法（任意）', 'Target body size (optional)'),
  bodyWidthMm: localized('胴体幅 (mm)', 'Body width (mm)'),
  bodyHeightMm: localized('胴体高さ (mm)', 'Body height (mm)'),
  leaveBothFieldsBlankForNoBodySizeTargetA: localized(
    '幅と高さを両方空欄にすると、胴体寸法を指定しません。片方だけの指定は保存しません。',
    'Leave both fields blank for no body-size target. A partial size is not saved.',
  ),
  totalPartsTotal32: localized('部品合計: {total} / 32', 'Total parts: {total} / 32'),
  oneHeadAndOneTorsoAreRequiredEachPartIs: localized(
    '頭と胴体は各1個必須です。各部品は最大8個、合計32個までです。入力した部品だけを生成条件に使います。',
    'One head and one torso are required. Each part is limited to 8 and the total to 32. Only entered parts are used for generation.',
  ),
  stickSkeleton: localized('棒状骨格', 'Stick skeleton'),
  startXMm: localized('始点X (mm)', 'Start X (mm)'),
  startYMm: localized('始点Y (mm)', 'Start Y (mm)'),
  lengthMm: localized('長さ (mm)', 'Length (mm)'),
  thicknessMm: localized('太さ (mm)', 'Thickness (mm)'),
  addSkeletonBar: localized('骨格の棒を追加', 'Add skeleton bar'),
  stickSkeletonPreview: localized('棒状骨格プレビュー', 'Stick skeleton preview'),
  skeletonBarList: localized('骨格の棒一覧', 'Skeleton bar list'),
  thicknessThicknessMm: localized('太さ {thickness} mm', 'thickness {thickness} mm'),
  startX: localized('始点 X', 'Start X'),
  startY: localized('始点 Y', 'Start Y'),
  endX: localized('終点 X', 'End X'),
  endY: localized('終点 Y', 'End Y'),
  thickness: localized('太さ', 'Thickness'),
  skeletonBarSegmentIdLabelMm: localized(
    '骨格バー {segmentId} {label} (mm)',
    'Skeleton bar {segmentId} {label} (mm)',
  ),
  remove: localized('削除', 'Remove'),
  upTo64BarsAreStoredAt01Mm: localized(
    '0.1 mm単位で最大64本です。長さと太さを明示した棒だけを生成条件に使います。',
    'Up to 64 bars are stored at 0.1 mm precision. Only bars with explicit length and thickness are used for generation.',
  ),
  skeletonTreeConfirmedPointsJointsAndEdgesBranchesCandidateGeneration: localized(
    '骨格tree確認済み: {points}節点・{edges}枝。候補生成でbranch→crease権限を再検証します。',
    'Skeleton tree confirmed: {points} joints and {edges} branches. Candidate generation revalidates branch-to-crease authority.',
  ),
  skeletonTreeUnconfirmedReasonCyclesDuplicateEdgesAndDisconnectedSkeleton: localized(
    '骨格tree未確認 ({reason})。閉路・重複枝・非連結骨格はSIM証明なしに候補生成できません。',
    'Skeleton tree unconfirmed ({reason}). Cycles, duplicate edges, and disconnected skeletons cannot generate candidates without a simulation proof.',
  ),
  protrusionTargets: localized('突起目標', 'Protrusion targets'),
  count: localized('個数', 'Count'),
  finalPositionXMm: localized('最終位置 X (mm)', 'Final position X (mm)'),
  finalPositionYMm: localized('最終位置 Y (mm)', 'Final position Y (mm)'),
  finalPositionZMm: localized('最終位置 Z (mm)', 'Final position Z (mm)'),
  directionX: localized('向き X', 'Direction X'),
  directionY: localized('向き Y', 'Direction Y'),
  directionZ: localized('向き Z', 'Direction Z'),
  curvatureDegrees: localized('曲率 (度)', 'Curvature (degrees)'),
  motionMinimumDegrees: localized('可動範囲の最小 (度)', 'Motion minimum (degrees)'),
  motionMaximumDegrees: localized('可動範囲の最大 (度)', 'Motion maximum (degrees)'),
  priority: localized('優先度', 'Priority'),
  rootWidthMmOptional: localized('根元幅 (mm、任意)', 'Root width (mm, optional)'),
  tipWidthMmOptional: localized('先端幅 (mm、任意)', 'Tip width (mm, optional)'),
  symmetry: localized('対称性', 'Symmetry'),
  bilateral: localized('左右対称', 'Bilateral'),
  radial: localized('放射対称', 'Radial'),
  joint: localized('関節', 'Joint'),
  fixed: localized('固定', 'Fixed'),
  hinge: localized('ヒンジ', 'Hinge'),
  ball: localized('球関節', 'Ball'),
  side: localized('表裏', 'Side'),
  front: localized('表', 'Front'),
  back: localized('裏', 'Back'),
  either: localized('どちらでも', 'Either'),
  addProtrusionTarget: localized('突起目標を追加', 'Add protrusion target'),
  createEmptyGenericTarget: localized('空の汎用目標を新規作成', 'Create empty generic target'),
  featureConstraintComparison: localized('特徴制約の比較', 'Feature constraint comparison'),
  feature: localized('特徴', 'Feature'),
  motion: localized('可動範囲', 'Motion'),
  side2: localized('面', 'Side'),
  protrusionTargetList: localized('突起目標一覧', 'Protrusion target list'),
  explicitlySetsCountDimensionsFinalPositionDirectionSymmetryCurvatureJoin: localized(
    '本数、寸法、完成位置、向き、対称性、曲がり、関節、可動範囲、表裏、優先度を明示します。保存するまでプロジェクトは変更されません。',
    'Explicitly sets count, dimensions, final position, direction, symmetry, curvature, joint, motion range, side, and priority. The project is unchanged until saved.',
  ),
  text3dBulgeTargets: localized('3D膨らみ目標', '3D bulge targets'),
  selectedFaceId: localized('選択面: {id}', 'Selected face: {id}'),
  selectATargetFaceInThe2DOr3DView: localized(
    '2Dまたは3D表示で対象面を選択してください。',
    'Select a target face in the 2D or 3D view.',
  ),
  addBulgeTargetForSelectedFace: localized('選択面の膨らみ目標を追加', 'Add bulge target for selected face'),
  text3dBulgeTargetList: localized('3D膨らみ目標一覧', '3D bulge target list'),
  faceFaceAmountAmountMm: localized('面 {face}・量 {amount} mm', 'Face {face} · amount {amount} mm'),
  storesOnlyTheBoundedRangeDirectionAndAmountBoundTo: localized(
    '現在のプロジェクトと折りモデル指紋に結び付けて範囲、方向、量だけを保存します。弾性は計算せず、保存前に編集できます。',
    'Stores only the bounded range, direction, and amount bound to the current project and fold-model fingerprint. Elasticity is not computed, and values remain editable before save.',
  ),
  maximumSteps: localized('最大工程数', 'Maximum steps'),
  partDetail: localized('部位の細かさ', 'Part detail'),
  simple: localized('簡潔', 'Simple'),
  standard: localized('標準', 'Standard'),
  detailed: localized('詳細', 'Detailed'),
  allowedFoldTechniques: localized('利用可能な折り技法', 'Allowed fold techniques'),
  insideReverseFold: localized('中割り折り', 'Inside reverse fold'),
  outsideReverseFold: localized('かぶせ折り', 'Outside reverse fold'),
  squashFold: localized('つぶし折り', 'Squash fold'),
  petalFold: localized('花弁折り', 'Petal fold'),
  sinkFold: localized('沈め折り', 'Sink fold'),
  crimpFold: localized('段折り', 'Crimp fold'),
  holdCtrlOrCommandToSelectMultipleTechniquesSelectAt: localized(
    'CtrlキーまたはCommandキーを押しながら複数選択できます。少なくとも1つ選択してください。',
    'Hold Ctrl or Command to select multiple techniques. Select at least one.',
  ),
  petalFoldIsADesignPreferenceOnlyItsPhysicalMotion: localized(
    '花弁折りは設計上の指定だけで、物理運動は未証明です。',
    'Petal fold is a design preference only; its physical motion is not certified.',
  ),
  saveDesignPriorities: localized('評価方針を保存', 'Save design priorities'),
  theStackedFoldWasAppliedAtomicallyUndoRestoresTheWhole: localized(
    '折り重ねを原子的に適用しました。Undoで全体を戻せます。',
    'The stacked fold was applied atomically. Undo restores the whole change.',
  ),
  geometryValidation: localized('幾何検証', 'Geometry validation'),
  noIssuesWereFound: localized('問題は見つかりませんでした。', 'No issues were found.'),
  countIssuesWereFound: localized('{count}件の問題が見つかりました。', '{count} issues were found.'),
  localFlatFoldabilityConditions: localized('局所平坦折り条件', 'Local flat-foldability conditions'),
  coverageASingleInteriorVertexZeroThicknessModelFoldDegree: localized(
    '対応範囲: 紙内部の単一頂点・ゼロ厚モデル、折り線次数{degree}以下',
    'Coverage: a single interior vertex, zero-thickness model, fold degree {degree} or less',
  ),
  vertexCountsByLocalFlatFoldabilityResult: localized(
    '局所平坦折り条件の頂点別件数',
    'Vertex counts by local flat-foldability result',
  ),
  satisfied: localized('成立', 'Satisfied'),
  violated: localized('不成立', 'Violated'),
  notApplicable: localized('対象外', 'Not applicable'),
  indeterminate2: localized('判定不能', 'Indeterminate'),
  theAllVertexLocalSufficiencySummaryIsUnavailable: localized(
    '全頂点の局所十分性summaryを取得できませんでした。',
    'The all-vertex local-sufficiency summary is unavailable.',
  ),
  allVertexLocalSufficiencySummary: localized(
    '全頂点の局所十分性summary',
    'All-vertex local-sufficiency summary',
  ),
  necessaryConditionFailureProvenSufficiencyAndIndeterminateAreSeparatePas: localized(
    '必要条件不成立・十分性証明済み・判定不能を区別します。必要条件の通過だけを証明とは扱いません。',
    'Necessary-condition failure, proven sufficiency, and indeterminate are separate. Passing necessary conditions alone is not treated as proof.',
  ),
  necessaryFailed: localized('必要条件不成立', 'Necessary failed'),
  sufficiencyProven: localized('局所十分性を証明', 'Sufficiency proven'),
  localConditionsForSelectedVertex: localized('選択頂点の局所条件', 'Local conditions for selected vertex'),
  overall: localized('総合', 'Overall'),
  kawasakiCondition: localized('川崎条件', 'Kawasaki condition'),
  maekawaCondition: localized('前川条件', 'Maekawa condition'),
  foldDegree: localized('折り線次数', 'Fold degree'),
  mountainValley: localized('山折り / 谷折り', 'Mountain / valley'),
  verticesRequiringReview: localized('確認が必要な頂点', 'Vertices requiring review'),
  vertexOrdinalLocalNecessaryConditionVerdictKawasakiConditionKawasakiMaek: localized(
    '頂点{ordinal}、局所必要条件{verdict}。川崎条件{kawasaki}、前川条件{maekawa}。{reason}',
    'Vertex {ordinal}: local necessary condition {verdict}. Kawasaki condition {kawasaki}; Maekawa condition {maekawa}. {reason}',
  ),
  vertexOrdinal: localized('頂点 {ordinal}', 'Vertex {ordinal}'),
  kawasakiKawasakiMaekawaMaekawa: localized(
    '川崎 {kawasaki}・前川 {maekawa}',
    'Kawasaki {kawasaki} · Maekawa {maekawa}',
  ),
  countMoreVerticesSelectAVertexToReviewItsResult: localized(
    'ほか{count}頂点。頂点を選択すると個別結果を確認できます。',
    '{count} more vertices. Select a vertex to review its result.',
  ),
  satisfiedMeansOnlyThatTheLocalNecessaryConditionsWereVerified: localized(
    '成立はこのモデルで確認した局所必要条件だけを表します。展開図全体が平坦に折り畳めることや、実際の折り経路は保証しません。',
    'Satisfied means only that the local necessary conditions were verified by this model. It does not guarantee that the entire pattern can fold flat or that a physical folding path exists.',
  ),
  paper: localized('紙', 'Paper'),
  thickness2: localized('厚さ', 'Thickness'),
  frontColor: localized('表色', 'Front color'),
  backColor: localized('裏色', 'Back color'),
  frontPattern: localized('表の模様', 'Front pattern'),
  noneSolid: localized('なし（単色）', 'None (solid)'),
  dots: localized('ドット', 'Dots'),
  grid2: localized('格子', 'Grid'),
  stripes: localized('縞', 'Stripes'),
  importedImage: localized('読み込んだ画像', 'Imported image'),
  importImage: localized('画像を読み込む…', 'Import image…'),
  backPattern: localized('裏の模様', 'Back pattern'),
  allowCutting: localized('切断を許可', 'Allow cutting'),
  updatePaperSettings: localized('紙設定を更新', 'Update paper settings'),
  paperSize: localized('用紙サイズ', 'Paper size'),
  width: localized('幅', 'Width'),
  paperWidthUnit: localized('用紙の幅 ({unit})', 'Paper width ({unit})'),
  height: localized('高さ', 'Height'),
  paperHeightUnit: localized('用紙の高さ ({unit})', 'Paper height ({unit})'),
  paperThatIsNotRecognizedAsAnAxisAlignedRectangle: localized(
    '軸平行な長方形として判定できない紙は、この画面ではサイズ変更できません。',
    'Paper that is not recognized as an axis-aligned rectangle cannot be resized here.',
  ),
  resizingProportionallyTransformsEveryVertexIncludingFoldLinesFromThe: localized(
    'サイズ変更時は、折り線を含むすべての頂点を左上基準で比例変換します。',
    'Resizing proportionally transforms every vertex, including fold lines, from the top-left origin.',
  ),
  forAPaperEdgeRatioAxisRemainsReadOnlyAt: localized(
    '紙辺比では基準辺と平行な{axis}は 1 のまま読み取り専用です。直交する寸法だけを変更し、基準辺の物理長は維持します。',
    'For a paper-edge ratio, {axis} remains read-only at 1. Only the perpendicular dimension changes, preserving the physical length of the reference edge.',
  ),
  width2: localized('幅', 'width'),
  height2: localized('高さ', 'height'),
  resizePaper: localized('用紙サイズを変更', 'Resize paper'),
  editHistory: localized('編集履歴', 'Edit history'),
  theUndoRedoHistoryLimitCouldNotBeChecked: localized(
    'Undo・Redo履歴の上限を確認できませんでした。',
    'The undo/redo history limit could not be checked.',
  ),
  retry: localized('再試行', 'Retry'),
  historyLimitSettingsAreAvailableInTheDesktopApp: localized(
    '履歴上限の設定はデスクトップ版で利用できます。',
    'History limit settings are available in the desktop app.',
  ),
  checkingHistoryLimit: localized('履歴上限を確認しています…', 'Checking history limit…'),
  namedFoldTechniques: localized('名前付き折り技法', 'Named fold techniques'),
  createAndShareMultipleInstructionStepsAsDeclarativeDataThis: localized(
    '複数の説明手順を宣言データとして作成・共有します。折り操作、プロジェクト変更、外部取得は自動実行しません。中割り・かぶせ・沈め折り・層選択運動は現在未対応の物理操作としてファイル内に明示します。',
    'Create and share multiple instruction steps as declarative data. This never auto-runs folds, changes the project, or fetches external resources. Inside reverse, outside reverse, sink, and layer-selective motions are explicitly stored as unsupported physical operations.',
  ),
  packageID: localized('パッケージID', 'Package ID'),
  techniques: localized('技法数', 'Techniques'),
  shareState: localized('共有状態', 'Share state'),
  changedSaveAsRequired: localized('変更あり・別名保存が必要', 'Changed · Save as required'),
  saved: localized('保存済み', 'Saved'),
  techniqueToAddToTimeline: localized('タイムラインへ追加する技法', 'Technique to add to timeline'),
  create: localized('新規作成', 'Create'),
  importFile: localized('ファイル取込', 'Import file'),
  edit: localized('編集', 'Edit'),
  buildTimelineProposal: localized('折り手順案を作成', 'Build timeline proposal'),
  processingTheFoldTechniqueFile: localized(
    '折り技法ファイルを処理しています…',
    'Processing the fold-technique file…',
  ),
  safeFileSelectionAndAtomicSavingAreAvailableInThe: localized(
    '安全なファイル選択と原子的保存はデスクトップ版で利用できます。',
    'Safe file selection and atomic saving are available in the desktop app.',
  ),
  snap: localized('スナップ', 'Snap'),
  snapSettings: localized('スナップ設定', 'Snap settings'),
  dividePaperIntoN: localized('用紙のN等分グリッド', 'Divide paper into N'),
  auto: localized('自動', 'Auto'),
  leaveBlankForAutomaticSpacingUse3ForThirdsOr: localized(
    '空欄は自動。3で三等分、8で八等分します。',
    'Leave blank for automatic spacing; use 3 for thirds or 8 for eighths.',
  ),
  paperDiagonals: localized('用紙の対角線', 'Paper diagonals'),
  angleSnap: localized('角度スナップ', 'Angle snap'),
  preset: localized('プリセット', 'Preset'),
  customAngle: localized('任意角', 'Custom angle'),
  enterAnAngleGreaterThan0AndNoMoreThan: localized(
    '角度は0より大きく90以下で入力してください。最後の正常値を使用します。',
    'Enter an angle greater than 0 and no more than 90. The last valid value will be used.',
  ),
  reference: localized('基準', 'Reference'),
  angleSnapReference: localized('角度スナップの基準', 'Angle snap reference'),
  directionReferenceEdge: localized('方向参照辺', 'Direction reference edge'),
  currentAngleReference: localized('現在: {angle}°・{reference}', 'Current: {angle}° · {reference}'),
  horizontalReference: localized('水平基準', 'horizontal reference'),
  directionEdgeReference: localized('方向参照辺基準', 'direction edge reference'),
  selectALineAndSetItAsTheDirectionReference: localized(
    '線を選択して方向参照に設定してください。暗黙に水平基準へは切り替えません。',
    'Select a line and set it as the direction reference. The app will not silently switch to horizontal.',
  ),
  directionReferenceParallelAndAngleKind: localized(
    '方向参照（平行・角度）: {kind}',
    'Direction reference (parallel and angle): {kind}',
  ),
  clearReference: localized('参照を解除', 'Clear reference'),
  selectALineAndChooseSetAsDirectionReferenceTo: localized(
    '線を選択して「方向参照に設定」を押すと、平行・角度スナップの基準にできます。',
    'Select a line and choose “Set as direction reference” to use it for parallel and angle snapping.',
  ),
  startFromOneSheet: localized('一枚紙から開始', 'Start from one sheet'),
  newProject: localized('新しいプロジェクト', 'New project'),
  close: localized('閉じる', 'Close'),
  projectName: localized('作品名', 'Project name'),
  untitledWork: localized('無題の作品', 'Untitled work'),
  paperWidthExpressionMm: localized('用紙の幅の式 (mm)', 'Paper width expression (mm)'),
  paperHeightExpressionMm: localized('用紙の高さの式 (mm)', 'Paper height expression (mm)'),
  materialSettings: localized('材料設定', 'Material settings'),
  paperThickness: localized('紙厚', 'Paper thickness'),
  allowCutLinesInThisProject: localized('この作品で切断線の作成を許可する', 'Allow cut lines in this project'),
  createsRectangularPaperWithItsTopLeftAt00: localized(
    '左上を (0, 0) mm とする長方形の用紙と、4本の輪郭線を作成します。',
    'Creates rectangular paper with its top-left at (0, 0) mm and four boundary edges.',
  ),
  creating: localized('作成中…', 'Creating…'),
  create2: localized('作成', 'Create'),
  toolTool: localized('ツール: {tool}', 'Tool: {tool}'),
  benchmarkSelection: localized('性能テスト選択', 'Benchmark selection'),
  snapStatus: localized('スナップ: {status}', 'Snap: {status}'),
  diagnostics: localized('診断情報', 'Diagnostics'),
  loading: localized('読込中…', 'Loading…'),
  returnToNormalPattern: localized('通常図へ戻る', 'Return to normal pattern'),
  text10000EdgeTest: localized('10,000本テスト', '10,000-edge test'),
  boundaryEdge: localized('輪郭線', 'Boundary edge'),
  cutLine: localized('切断線', 'Cut line'),
  unknownSize: localized('サイズ不明', 'Unknown size'),
  unknownTool: localized('不明なツール', 'Unknown tool'),
  nonFiniteVertexCoordinates: localized('有限でない頂点座標', 'Non-finite vertex coordinates'),
  duplicateVerticesAtTheSamePosition: localized(
    '同じ位置の重複頂点',
    'Duplicate vertices at the same position',
  ),
  lineReferencesAMissingEndpoint: localized('存在しない端点を参照する線', 'Line references a missing endpoint'),
  zeroLengthLine: localized('長さ0の線', 'Zero-length line'),
  unsplitIntersectionOrOverlap: localized('分割されていない交差・重なり', 'Unsplit intersection or overlap'),
  intersectionCalculationFailed: localized('交差計算に失敗', 'Intersection calculation failed'),
  paperThicknessIsNotFinite: localized('紙の厚さが有限値ではありません', 'Paper thickness is not finite'),
  paperThicknessMustBeAtLeast0Mm: localized(
    '紙の厚さは0 mm以上にする必要があります',
    'Paper thickness must be at least 0 mm',
  ),
  paperBoundaryNeedsAtLeastThreeVertices: localized(
    '紙の輪郭には3つ以上の頂点が必要です',
    'Paper boundary needs at least three vertices',
  ),
  paperBoundaryContainsADuplicateVertex: localized(
    '紙の輪郭に同じ頂点が重複しています',
    'Paper boundary contains a duplicate vertex',
  ),
  paperBoundaryReferencesAMissingVertex: localized(
    '紙の輪郭が存在しない頂点を参照しています',
    'Paper boundary references a missing vertex',
  ),
  paperBoundaryVertexCoordinatesAreNotFinite: localized(
    '紙の輪郭頂点の座標が有限値ではありません',
    'Paper boundary vertex coordinates are not finite',
  ),
  paperBoundaryEdgesAreMissing: localized('紙の輪郭線が不足しています', 'Paper boundary edges are missing'),
  paperBoundaryContainsADuplicateEdge: localized(
    '紙の輪郭線が重複しています',
    'Paper boundary contains a duplicate edge',
  ),
  paperBoundaryContainsAnUnexpectedEdge: localized(
    '紙の輪郭に余分な輪郭線があります',
    'Paper boundary contains an unexpected edge',
  ),
  paperBoundaryContainsAZeroLengthEdge: localized(
    '紙の輪郭に長さ0の辺があります',
    'Paper boundary contains a zero-length edge',
  ),
  paperBoundaryIntersectsItself: localized('紙の輪郭が自己交差しています', 'Paper boundary intersects itself'),
  paperBoundaryIntersectionTestFailed: localized(
    '紙の輪郭の交差判定に失敗しました',
    'Paper boundary intersection test failed',
  ),
  paperBoundaryHasZeroArea: localized('紙の輪郭の面積が0です', 'Paper boundary has zero area'),
  paperBoundaryAreaCalculationFailed: localized(
    '紙の輪郭の面積計算に失敗しました',
    'Paper boundary area calculation failed',
  ),
  unknownGeometryValidationIssue: localized('不明な幾何検証問題', 'Unknown geometry validation issue'),
  aVertexIDIsDuplicated: localized('頂点IDが重複しています。', 'A vertex ID is duplicated.'),
  aLineIDIsDuplicated: localized('線IDが重複しています。', 'A line ID is duplicated.'),
  thePaperBoundaryOrPropertiesAreInvalid: localized(
    '用紙の輪郭または属性が不正です。',
    'The paper boundary or properties are invalid.',
  ),
  theCreasePatternGeometryIsInvalid: localized(
    '展開図の幾何が不正です。',
    'The crease-pattern geometry is invalid.',
  ),
  aLineKindCannotBeConvertedTo3D: localized(
    '3D化できない線種が含まれています。',
    'A line kind cannot be converted to 3D.',
  ),
  theActiveFoldCountExceedsTheSupportedLimit: localized(
    '有効な折り線が処理上限を超えています。',
    'The active fold count exceeds the supported limit.',
  ),
  aFoldLineLiesOutsideThePaper: localized('折り線が用紙の外側にあります。', 'A fold line lies outside the paper.'),
  theFoldGraphIsDisconnected: localized('折り構造が分断されています。', 'The fold graph is disconnected.'),
  aFoldLineDoesNotSeparateTwoFaces: localized(
    '折り線が面を2つに分離していません。',
    'A fold line does not separate two faces.',
  ),
  theFoldGraphIsUnsupportedByTheCurrent3DModel: localized(
    '現在の3Dモデルで扱えない折り構造です。',
    'The fold graph is unsupported by the current 3D model.',
  ),
  aLineHasInvalidFaceIncidence: localized('線に接する面の構成が不正です。', 'A line has invalid face incidence.'),
  aFoldEndpointIsNotOnThePaperBoundary: localized(
    '折り線の端点が用紙輪郭上にありません。',
    'A fold endpoint is not on the paper boundary.',
  ),
  aBoundaryAdjacentFoldIsUnsupported: localized(
    '輪郭に隣接する折り線を3D化できません。',
    'A boundary-adjacent fold is unsupported.',
  ),
  thisFoldOnANonConvexSheetIsUnsupported: localized(
    '非凸用紙上のこの折り線を3D化できません。',
    'This fold on a non-convex sheet is unsupported.',
  ),
  aFoldLineProducesADegenerateFace: localized(
    '折り線から面を構成できません。',
    'A fold line produces a degenerate face.',
  ),
  aFaceAreaCannotBeRepresentedSafely: localized(
    '面積を安全に表現できません。',
    'A face area cannot be represented safely.',
  ),
  facesCouldNotBeResolvedFromThePaperBoundary: localized(
    '用紙輪郭から面を確定できません。',
    'Faces could not be resolved from the paper boundary.',
  ),
  localResultUnavailable: localized('局所判定結果を確認不能', 'Local result unavailable'),
  localAnalysisBlockedByGeometryIssues: localized(
    '局所判定を前段の幾何問題で遮断',
    'Local analysis blocked by geometry issues',
  ),
  localNecessaryConditionsSatisfiedAtCountVertices: localized(
    '局所必要条件が{count}頂点で成立',
    'Local necessary conditions satisfied at {count} vertices',
  ),
  noVerticesEligibleForLocalAnalysis: localized(
    '局所判定の対象頂点なし',
    'No vertices eligible for local analysis',
  ),
  localNecessaryConditionsViolatedAtCountVertices: localized(
    '局所必要条件に不成立{count}頂点',
    'Local necessary conditions violated at {count} vertices',
  ),
  localResultIndeterminateAtCountVertices: localized(
    '局所判定不能{count}頂点',
    'Local result indeterminate at {count} vertices',
  ),
  indeterminateBecauseTheFoldDegreeExceedsTheExactLimitLimit: localized(
    '',
    'Indeterminate because the fold degree exceeds the exact limit ({limit}).',
  ),
  theLocalFlatFoldabilityResultCouldNotBeVerifiedAnd: localized(
    '局所平坦折り条件の結果を確認できませんでした。成立とは扱いません。',
    'The local flat-foldability result could not be verified and is not treated as satisfied.',
  ),
  localFlatFoldabilityWasNotEvaluatedBecauseThePrecedingGeometry: localized(
    '前段の幾何構造に問題があるため、局所平坦折り条件は判定していません。',
    'Local flat-foldability was not evaluated because the preceding geometry has issues.',
  ),
  satisfiedSatisfiedViolatedViolatedNotApplicableNotApplicableIndeterminat: localized(
    '成立{satisfied}、不成立{violated}、対象外{notApplicable}、判定不能{indeterminate}',
    'satisfied {satisfied}, violated {violated}, not applicable {notApplicable}, indeterminate {indeterminate}',
  ),
  localNecessaryConditionsAreSatisfiedWithinTheSupportedScopeDetail: localized(
    '対応範囲内の局所必要条件が成立しました（{detail}）。',
    'Local necessary conditions are satisfied within the supported scope ({detail}).',
  ),
  noVerticesAreEligibleForTheCurrentLocalConditionsDetail: localized(
    '現在の局所条件を適用できる頂点がありません（{detail}）。',
    'No vertices are eligible for the current local conditions ({detail}).',
  ),
  someVerticesViolateTheLocalNecessaryConditionsDetail: localized(
    '局所必要条件に不成立の頂点があります（{detail}）。',
    'Some vertices violate the local necessary conditions ({detail}).',
  ),
  someVerticesHaveIndeterminateLocalNecessaryConditionsDetail: localized(
    '局所必要条件を判定できない頂点があります（{detail}）。',
    'Some vertices have indeterminate local necessary conditions ({detail}).',
  ),
  unavailable2: localized('計測不可', 'Unavailable'),
  theWidthOrHeightExpressionIsEmptyOrExceedsAn: localized(
    '幅または高さの式が空か、入力上限を超えています。',
    'The width or height expression is empty or exceeds an input limit.',
  ),
  theWidthOrHeightExpressionCouldNotBeParsed: localized(
    '幅または高さの式を解釈できません。',
    'The width or height expression could not be parsed.',
  ),
  evaluationStoppedBecauseTheWidthOrHeightExpressionIsToo: localized(
    '幅または高さの式が複雑すぎるため評価を中止しました。',
    'Evaluation stopped because the width or height expression is too complex.',
  ),
  theWidthOrHeightCannotBeSafelyUsedAsA: localized(
    '幅または高さを正のmm値として安全に採用できません。',
    'The width or height cannot be safely used as a positive millimetre value.',
  ),
  creatingAProjectFromExpressionsIsAvailableInTheDesktop: localized(
    '式を使った新規作成はデスクトップ版で利用できます。',
    'Creating a project from expressions is available in the desktop app.',
  ),
  theEvaluatedWidthOrHeightResultCouldNotBeUsed: localized(
    '幅または高さの評価結果を採用できませんでした。',
    'The evaluated width or height result could not be used.',
  ),
  expressionInputIsAvailableInTheDesktopApp: localized(
    '数式入力はデスクトップ版で利用できます。',
    'Expression input is available in the desktop app.',
  ),
  evaluationStoppedBecauseTheExpressionIsTooComplex: localized(
    '数式が複雑すぎるため評価を中止しました。',
    'Evaluation stopped because the expression is too complex.',
  ),
  enterAFiniteExpressionUsingDecimalsFractionsSquareRootsPi: localized(
    '小数・分数・平方根・π・四則演算・括弧を使った有限の数式を入力してください。',
    'Enter a finite expression using decimals, fractions, square roots, pi, operators, or parentheses.',
  ),
})
