import { invoke } from '@tauri-apps/api/core'

export type PatternResponse = {
  vertex_count: number
  edge_count: number
}

export async function generateBenchmarkPattern(edgeCount: number): Promise<PatternResponse> {
  if ('__TAURI_INTERNALS__' in window) {
    return invoke<PatternResponse>('generate_benchmark_pattern', { edgeCount })
  }

  // Browser-only development fallback. Production data is generated by Rust.
  const side = Math.max(2, Math.ceil(Math.sqrt(edgeCount / 2)))
  return { vertex_count: side * side, edge_count: edgeCount }
}
