import { invoke } from '@tauri-apps/api/core'

export type PatternResponse = {
  vertex_count: number
  edge_count: number
}

export type ProjectSnapshot = {
  revision: number
  crease_pattern: {
    vertices: Array<{ id: string; position: { x: number; y: number } }>
    edges: Array<{ id: string; start: string; end: string; kind: string }>
  }
  can_undo: boolean
  can_redo: boolean
}

export function isNativeCoreAvailable() {
  return '__TAURI_INTERNALS__' in window
}

export async function generateBenchmarkPattern(edgeCount: number): Promise<PatternResponse> {
  if (isNativeCoreAvailable()) {
    return invoke<PatternResponse>('generate_benchmark_pattern', { edgeCount })
  }

  // Browser-only development fallback. Production data is generated by Rust.
  const side = Math.max(2, Math.ceil(Math.sqrt(edgeCount / 2)))
  return { vertex_count: side * side, edge_count: edgeCount }
}

export function getProjectSnapshot() {
  return invoke<ProjectSnapshot>('project_snapshot')
}

export function addVertex(expectedRevision: number, x: number, y: number) {
  return invoke<ProjectSnapshot>('add_vertex', { expectedRevision, x, y })
}

export function undo(expectedRevision: number) {
  return invoke<ProjectSnapshot>('undo', { expectedRevision })
}

export function redo(expectedRevision: number) {
  return invoke<ProjectSnapshot>('redo', { expectedRevision })
}
