import type { LocalizedText } from './i18n.ts'

function localized(ja: string, en: string): LocalizedText {
  return Object.freeze({ ja, en })
}

export const STACKED_FOLD_PANEL_TEXT = Object.freeze({
  theContinuousPathIsNotCollisionCertified: localized(
    '連続経路の無衝突証明がありません。',
    'The continuous path is not collision-certified.',
  ),
  theTargetLayerOrderIsNotCertified: localized(
    '折り後の層順序を証明できません。',
    'The target layer order is not certified.',
  ),
  techniquePalette: localized('技法パレット', 'Technique palette'),
  chooseATechniqueReviewItsSafetyPreviewThenApplyIt: localized(
    '技法を選び、安全プレビューを確認してから明示的に適用します。',
    'Choose a technique, review its safety preview, then apply it explicitly.',
  ),
  unsupportedAsACertifiedPhysicalOperation: localized(
    '安全な物理操作として未対応です。',
    'Unsupported as a certified physical operation.',
  ),
  straightLineStackedFold: localized('一直線の折り重ね', 'Straight-line stacked fold'),
  theSelectedLineIsUsedAsTheAxisForA: localized(
    '選択中の線を折り軸としてnative証明を作成します。',
    'The selected line is used as the axis for a native proof.',
  ),
  selectAFoldAxisLineOnThe2DCanvas: localized(
    '2Dキャンバスで折り軸にする線を選択してください。',
    'Select a fold-axis line on the 2D canvas.',
  ),
  noSavedCompilerProofInformation: localized(
    '保存済みcompiler証明情報なし',
    'No saved compiler proof information',
  ),
  hingeAngleCandidate: localized('ヒンジ角度候補', 'Hinge angle candidate'),
  initialAngleReadOnly: localized('初期角度（読み取り専用）', 'Initial angle (read only)'),
  initialAngle: localized('初期角度', 'Initial angle'),
  requestedAngle: localized('要求角度', 'Requested angle'),
  automaticEvenCycleCandidates: localized('偶数単頂点の自動候補', 'Automatic even-cycle candidates'),
  sameAssignmentOppositeAxes: localized('同一割当・反対軸', 'same assignment, opposite axes'),
  candidateSearchExceededItsResourceBound: localized(
    '候補探索の上限を超えました。',
    'Candidate search exceeded its resource bound.',
  ),
  noMatchingOppositeHingePairExists: localized(
    '適合する反対ヒンジ対はありません。',
    'No matching opposite hinge pair exists.',
  ),
  theCurrentShapeIsNotASupportedEvenSingleVertex: localized(
    '現在の形状は対応する偶数単頂点サイクルではありません。',
    'The current shape is not a supported even single-vertex cycle.',
  ),
  fixedSide: localized('固定側', 'Fixed side'),
  leftOfLine: localized('線の左側', 'Left of line'),
  rightOfLine: localized('線の右側', 'Right of line'),
  cyclePathDefinitionJSONCyclicPatternsOnly: localized(
    '閉路経路定義（JSON、閉路パターンのみ）',
    'Cycle path definition (JSON, cyclic patterns only)',
  ),
  version1HalfAngleRationalScheduleCyclesWithoutOneCannot: localized(
    'version 1 の半角有理スケジュール。未入力の閉路は安全のため適用できません。',
    'Version 1 half-angle rational schedule. Cycles without one cannot be applied.',
  ),
  invalidScheduleDenominatorsMustBePositiveIntegersCoefficients19: localized(
    'scheduleが不正です。分母は正整数、係数は各1〜9個、角度は0〜180度です。',
    'Invalid schedule. Denominators must be positive integers, coefficients 1–9 each, and angles 0–180°.',
  ),
  rotationDirection: localized('回転方向', 'Rotation direction'),
  positive: localized('正方向', 'Positive'),
  negative: localized('負方向', 'Negative'),
  angleDegrees: localized('角度（度）', 'Angle (degrees)'),
  proving: localized('証明中…', 'Proving…'),
  verifySafety: localized('安全性を確認', 'Verify safety'),
  currentPoseCyclePreview: localized('現在姿勢の循環折りプレビュー', 'Current-pose cycle preview'),
  currentPoseCycle: localized('現在姿勢の循環折り', 'Current-pose cycle'),
  provingPath: localized('経路を証明中…', 'Proving path…'),
  proveFromCurrentPose: localized('現在姿勢から証明', 'Prove from current pose'),
  generateAndProveKawasakiLinkage: localized(
    '川崎リンクを自動生成して証明',
    'Generate and prove Kawasaki linkage',
  ),
  closureCertified: localized('閉路証明済み', 'Closure certified'),
  collisionCertified: localized('衝突証明済み', 'Collision certified'),
  collisionUncertified: localized('衝突未認証', 'Collision uncertified'),
  searchingPaths: localized('経路探索中…', 'Searching paths…'),
  searchBoundedDyadicPaths: localized('有界dyadic経路を探索', 'Search bounded dyadic paths'),
  dyadicLevels: localized('dyadic段階数', 'Dyadic levels'),
  cancelSearch: localized('探索を中止', 'Cancel search'),
  issueReadOnlyPreview: localized('読取専用プレビューを発行', 'Issue read-only preview'),
  applyAuthenticatedPath: localized('認証済み経路を適用', 'Apply authenticated path'),
  cancelCycleProof: localized('循環経路の証明を中止', 'Cancel cycle proof'),
  cycleProofCancelledYouCanRetry: localized(
    '循環経路の証明を中止しました。再試行できます。',
    'Cycle proof cancelled. You can retry.',
  ),
  theCyclePathCouldNotBeAuthenticatedTheProjectWas: localized(
    '循環経路を認証できませんでした。プロジェクトは変更されていません。',
    'The cycle path could not be authenticated. The project was not changed.',
  ),
  closureIntervals: localized('閉包区間数', 'Closure intervals'),
  maximumProofDepth: localized('証明の最大深さ', 'Maximum proof depth'),
  allHingesCovered: localized('全ヒンジ検証', 'All hinges covered'),
  continuousPath: localized('連続経路', 'Continuous path'),
  certified: localized('認証済み', 'Certified'),
  targetRevision: localized('適用後リビジョン', 'Target revision'),
  thisPreviewIsReadOnlyTheProjectIsUnchangedUntil: localized(
    'この表示は読み取り専用です。下の適用操作まで作品は変更されません。',
    'This preview is read-only. The project is unchanged until you explicitly apply it.',
  ),
  applyCertifiedCycleFold: localized('認証済み循環折りを適用', 'Apply certified cycle fold'),
  cancelPreview: localized('プレビューを取り消す', 'Cancel preview'),
  appliedLayerOrderViewer: localized('適用済み層順ビューアー', 'Applied layer-order viewer'),
  appliedLayerOrderProof: localized('適用済み層順証明', 'Applied layer-order proof'),
  transitions: localized('遷移数', 'Transitions'),
  pairs: localized('層順ペア数', 'Pairs'),
  proofHash: localized('証明ハッシュ', 'Proof hash'),
  canonicalProofPairsLowerToUpper: localized(
    '正規順の証明ペア（下層から上層）',
    'Canonical proof pairs (lower to upper)',
  ),
  thisIsAReadOnlyViewOfTheProofPersisted: localized(
    'これは適用済みタイムライン手順に保存された証明の読み取り専用表示です。',
    'This is a read-only view of the proof persisted by the applied timeline step.',
  ),
  thisViewShowsOnlyThePersistedProofItDoesNot: localized(
    'この表示は保存された証明だけを示します。一般の多ブロック層搬送は保証しません。',
    'This view shows only the persisted proof; it does not prove general multi-block layer transport.',
  ),
  theProjectChangedVerifyAgain: localized(
    '編集内容が変わりました。もう一度確認してください。',
    'The project changed. Verify again.',
  ),
  theCyclicHingeEndpointDoesNotCloseSoApplyIs: localized(
    '循環hingeの終端が閉じないため適用できません。',
    'The cyclic hinge endpoint does not close, so apply is disabled.',
  ),
  theCyclicEndpointClosesButItsContinuousPathIsUncertified: localized(
    '循環hingeの終端は閉じますが、連続経路を証明できないため適用できません。',
    'The cyclic endpoint closes, but its continuous path is uncertified, so apply is disabled.',
  ),
  staticReasonTheHingeGraphAndScheduleDoNotMatch: localized(
    '静的理由: ヒンジグラフとスケジュールが、証明済みの格子・対称セクタ・対向軸直線折りクラスのいずれにも一致しません。適用は無効です。',
    'Static reason: the hinge graph and schedule do not match a certified grid, symmetric-sector, or opposite-axis straight-fold class. Apply is disabled.',
  ),
  theBoundedProofReachedItsResourceLimitThisDoesNot: localized(
    '有界証明の資源上限に達しました。安全または不可能とは判定せず、適用を無効にします。',
    'The bounded proof reached its resource limit. This does not claim safety or impossibility, so apply is disabled.',
  ),
  noPathToTheTargetWasFoundUsingCertifiedTransitions: localized(
    '証明済み遷移だけでは目標への経路が見つかりませんでした。不可能とは判定しません。',
    'No path to the target was found using certified transitions only. This does not claim impossibility.',
  ),
  theBoundedPathAnalysisWasCancelledNoPartialCertificateWas: localized(
    '有界経路解析を中止しました。部分的な証明は公開していません。',
    'The bounded path analysis was cancelled. No partial certificate was published.',
  ),
  theScheduledContinuousPathCouldNotReceiveACollisionClearance: localized(
    '予定された連続経路の衝突なし証明を取得できませんでした。適用は無効です。',
    'The scheduled continuous path could not receive a collision-clearance certificate, so apply is disabled.',
  ),
  applyFailedThePreviewIsNoLongerTrusted: localized(
    '適用できませんでした。プレビューは失効しました。',
    'Apply failed; the preview is no longer trusted.',
  ),
  aNativeProofCouldNotBeCompletedForThisInput: localized(
    'この入力ではnative証明を完成できませんでした。',
    'A native proof could not be completed for this input.',
  ),
  cancelPathAnalysis: localized('経路解析を中止', 'Cancel path analysis'),
  theStackedFoldWasAppliedButTheRefreshedProjectCould: localized(
    '折り重ねは適用済みですが、最新表示を取得できませんでした。',
    'The stacked fold was applied, but the refreshed project could not be loaded.',
  ),
  theSpeculativeApplyOutcomeCouldNotBeConfirmed: localized(
    '投機的適用の成否を確認できません。適用を再実行せず、最新表示を再取得してください。',
    'The speculative Apply outcome could not be confirmed. Do not retry Apply; reload the latest project state.',
  ),
  retryRefresh: localized('最新表示を再取得', 'Retry refresh'),
  editingARequestedAngleBuildsCanonicalLinearCandidateV1InternallyNativeRe: localized(
    '要求角度を変更すると、正規順序のlinearCandidateV1が内部で構築されます。初期角度はnative姿勢へbit単位で再検証されます。',
    'Editing a requested angle builds canonical linearCandidateV1 internally. Native revalidates initial angles bit-for-bit.',
  ),
  targetFaces: localized('対象面', 'Target faces'),
  creases: localized('折り線', 'Creases'),
  targetHinges: localized('対象hinge', 'Target hinges'),
  endpointCollision: localized('終端衝突', 'Endpoint collision'),
  blocked: localized('停止', 'Blocked'),
  clear: localized('なし', 'Clear'),
  certified2: localized('証明済み', 'Certified'),
  uncertified: localized('未証明', 'Uncertified'),
  firstProvenBlockingSample: localized('最初の停止確認角', 'First proven blocking sample'),
  none: localized('なし', 'None'),
  pathCertificateModel: localized('経路証明モデル', 'Path certificate model'),
  intervalLeaves: localized('区間leaf数', 'Interval leaves'),
  intervalPairWork: localized('区間pair work', 'Interval pair work'),
  positiveThicknessCandidates: localized('正厚候補', 'Positive-thickness candidates'),
  positiveThicknessExactCalls: localized('正厚exact呼出', 'Positive-thickness exact calls'),
  candidateLimit: localized('候補上限', 'Candidate limit'),
  closureLeaves: localized('閉路leaf数', 'Closure leaves'),
  closurePairWork: localized('閉路pair work', 'Closure pair work'),
  firstClosureFailureAngle: localized('最初の閉路失敗角', 'First closure failure angle'),
  certifiedThickness: localized('証明済み紙厚', 'Certified thickness'),
  layerOrder: localized('層順序', 'Layer order'),
  addedVerticesEdges: localized('追加頂点 / 辺', 'Added vertices / edges'),
  certifiedCandidatePath: localized('証明済み候補経路', 'Certified candidate path'),
  scheduleCertificate: localized('スケジュール証明', 'Schedule certificate'),
  collisionCertificate: localized('衝突証明', 'Collision certificate'),
  closureCertificate: localized('閉路証明', 'Closure certificate'),
  selectRelatedHinge: localized('関連ヒンジを選択', 'Select related hinge'),
  thisCertificateCoversOnlyTheDisplayedThicknessTwoTriangularFaces: localized(
    'この証明は表示された紙厚・2三角形・1ヒンジ・90度以下だけを対象とします。一般の多面、別の紙厚、工作性は保証しません。',
    'This certificate covers only the displayed thickness, two triangular faces, one hinge, and a path up to 90°. It does not guarantee general multi-face folds, another thickness, or physical manufacturability.',
  ),
  applyFailedYouCanRetryWithTheSameCertifiedPreview: localized(
    '適用できませんでした。同じ証明済みpreviewで再試行できます。',
    'Apply failed. You can retry with the same certified preview.',
  ),
  namedBasicFoldTimelinePreview: localized(
    '名前付き基本折りの手順preview',
    'Named basic-fold timeline preview',
  ),
  previewCertifiedTimeline: localized('認証済み手順をpreview', 'Preview certified timeline'),
  buildingCertifiedTimeline: localized('認証済み手順を作成中…', 'Building certified timeline…'),
  certifiedTimelineStepPlayer: localized('認証済み手順step再生', 'Certified timeline step player'),
  readOnlyPreviewNoMutationAuthorityIsIncluded: localized(
    '読取専用previewです。適用権限は含みません。',
    'Read-only preview; no mutation authority is included.',
  ),
  step: localized('step', 'Step'),
  previousStep: localized('前のstep', 'Previous step'),
  nextStep: localized('次のstep', 'Next step'),
  stepDetailPreview: localized('step詳細preview', 'Step detail preview'),
  fixedFace: localized('固定面', 'Fixed face'),
  hingeCount: localized('ヒンジ数', 'Hinge count'),
  pathProof: localized('経路証明', 'Path proof'),
  referenced: localized('参照あり', 'Referenced'),
  couldNotBuildACertifiedTimelineTreeStaleCancelledOr: localized(
    '認証済み手順を作成できません。Tree・古い・取消済み・改変されたtokenは拒否されます。',
    'Could not build a certified timeline. Tree, stale, cancelled, or tampered tokens are rejected.',
  ),
  missingPetalFoldProofPremises: localized('花弁折りの不足証明premise', 'Missing petal-fold proof premises'),
  requiredGraphSegmentsAtLeast3InOneGraphChain: localized(
    '必要Graph区間: 3以上（同一Graph chain）',
    'Required Graph segments: at least 3 in one Graph chain',
  ),
  liftedFlapTopologyAuthority: localized('持ち上げるflapの位相権限', 'Lifted-flap topology authority'),
  adjacentFaceOpeningPathAuthority: localized('隣接面を開く経路権限', 'Adjacent-face opening path authority'),
  finalFlatteningEndpointAuthority: localized(
    '最終平坦化のendpoint権限',
    'Final-flattening endpoint authority',
  ),
  continuousLayerOrderAuthorityAcrossEverySegment: localized(
    '全区間を通したlayer順序権限',
    'Continuous layer-order authority across every segment',
  ),
  v1CertificatesDoNotBindThesePremisesTogetherSoNo: localized(
    '現V1 certificateはこれらを結合しないためpreview/apply tokenを発行しません。',
    'V1 certificates do not bind these premises together, so no preview or apply token is issued.',
  ),
  iReviewedTheCertifiedChanges: localized('証明済みの変更内容を確認しました。', 'I reviewed the certified changes.'),
  applying: localized('適用中…', 'Applying…'),
  applyNamedLayerTechnique: localized('名前付き層選択技法を適用', 'Apply named layer technique'),
  applyNamedSinkFold: localized('名前付き沈め折りを適用', 'Apply named sink fold'),
  applyNamedAccordionFold: localized('名前付き蛇腹折りを適用', 'Apply named accordion fold'),
  applyNamedReverseFold: localized('名前付き逆折りを適用', 'Apply named reverse fold'),
  applyNamedBookFold: localized('名前付き二つ折りを適用', 'Apply named book fold'),
  applyStackedFold: localized('折り重ねを適用', 'Apply stacked fold'),
  applyIsDisabledBecauseTheCaseIsNotFullyCertified: localized(
    '未証明のため適用は無効です。',
    'Apply is disabled because the case is not fully certified.',
  ),
  text3dLayerOrderViewer: localized('3D層順ビューア', '3D layer-order viewer'),
  overlapCellsAndLayerOrder: localized('重なりセルと層順', 'Overlap cells and layer order'),
  readOnlyViewOfTheAuthenticatedCurrentPoseAndLayer: localized(
    '認証済みの現在poseと層順を読み取り専用で表示します。',
    'Read-only view of the authenticated current pose and layer order.',
  ),
  cell: localized('セル', 'Cell'),
  explodedFrontBackLayerStack: localized('front/back層の分解表示', 'Exploded front/back layer stack'),
  backBottom: localized('裏面 / 最下層', 'Back / bottom'),
  frontTop: localized('表面 / 最上層', 'Front / top'),
  middle: localized('中間層', 'Middle'),
  face: localized('面', 'Face'),
  positiveThicknessContinuousPathCertificate: localized(
    '正厚の連続経路証明',
    'Positive-thickness continuous-path certificate',
  ),
  zeroThicknessContinuousPathCertificate: localized(
    '厚さゼロの連続経路証明',
    'Zero-thickness continuous-path certificate',
  ),
  savedCompilerProvenance: localized(
    '保存済みcompiler provenance（読み取り専用）: {kind} / {count} steps',
    'Saved compiler provenance (read only): {kind} / {count} steps',
  ),
  boundedSchedule: localized(
    '有界schedule: {count}/64 hinge、係数は各9以下',
    'Bounded schedule: {count}/64 hinges; at most 9 coefficients each',
  ),
  cyclePathProgress: localized(
    '循環経路の状態 {states}/{stateLimit}、遷移 {transitions}/{transitionLimit}',
    'Cycle states {states}/{stateLimit}; transitions {transitions}/{transitionLimit}',
  ),
  persistedLayerPairsOmitted: localized(
    '先頭{visible}件を表示し、残り{remaining}件を省略しています。',
    'Showing the first {visible}; {remaining} more are omitted.',
  ),
  searchPathProgress: localized(
    '探索済み状態 {states}/{stateLimit}、遷移 {transitions}/{transitionLimit}',
    'Explored states {states}/{stateLimit}; transitions {transitions}/{transitionLimit}',
  ),
  certifiedPathTransitionCount: localized(
    '{count} 遷移。read-only previewであり、作品変更を許可しません。',
    '{count} transition(s). This read-only preview does not authorize project mutation.',
  ),
  transitionIndex: localized('遷移 {index}', 'Transition {index}'),
  namedTechniqueWillBeSaved: localized(
    '名前付き技法「{name}」として認証済み姿勢を手順へ保存します。PDF/SVG折り図にも同じ手順が使われます。',
    'The certified pose will be saved as the named technique “{name}”. The same step is used by PDF/SVG instruction exports.',
  ),
  petalFoldUnsupported: localized(
    '花弁折りは持ち上げ・隣接面の開き・最終平坦化を同時に証明できないため適用できません。',
    'Petal fold remains unsupported because lift, adjacent-face opening, and final flattening are not jointly certified.',
  ),
  basicFoldKindUnsupported: localized(
    'この基本折りには認証済みの山折り・谷折り種別がないため適用できません。',
    'This basic fold has no certified mountain/valley kind and cannot be applied.',
  ),
  backBottomFaceIndex: localized(
    '裏面・最下層、面 {index}',
    'Back, bottom, face {index}',
  ),
  frontTopFaceIndex: localized(
    '表面・最上層、面 {index}',
    'Front, top, face {index}',
  ),
  middleLayerFaceIndex: localized(
    '中間層、面 {index}',
    'Middle layer, face {index}',
  ),
})
