import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const client = readFileSync(new URL('../src/lib/coreClient.ts', import.meta.url), 'utf8')
const app = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')
const completeAnimalBindingList = readFileSync(new URL('../src/components/CompleteAnimalBindingList.tsx', import.meta.url), 'utf8')
const native = readFileSync(new URL('../src-tauri/src/lib.rs', import.meta.url), 'utf8')

test('AUT-106 candidate reads bind instance, project, and revision without mutation', () => {
  assert.match(native, /fn evaluate_beginner_candidates/)
  assert.match(native, /ensure_expected_project\([\s\S]*expected_project_instance_id[\s\S]*expected_project_id[\s\S]*expected_revision/)
  assert.match(client, /invoke<unknown>\('evaluate_beginner_candidates'/)
  assert.match(client, /response\.candidates\.length > 3/)
})

test('candidate admission requires ordered bounded explainable scores', () => {
  assert.match(client, /record\.rank !== index \+ 1/)
  assert.match(client, /Number\(score\) > 100/)
  assert.match(client, /record\.target_approximation_score/)
  assert.match(client, /admitted\[index - 1\]\.total_score < candidate\.total_score/)
  assert.match(app, /candidate\.shape_score/)
  assert.match(app, /candidate\.target_approximation_score/)
  assert.match(app, /Target-shape approximation/)
  assert.match(app, /candidate\.paper_efficiency_score/)
})

test('asymmetric fish plans require four ordered semantic ray bindings end to end', () => {
  assert.match(client, /'asymmetric_fish_landmark_base'/)
  assert.match(client, /\['head', 'tail', 'fin_left', 'fin_right'\]/)
  assert.match(client, /\(semanticRoles !== null\) !== \(semantic !== null\)/)
  assert.match(client, /semanticBindings\.length !== semanticRoles\?\.length/)
  assert.match(client, /rayDigests\?\.length !== 4/)
  assert.match(app, /頭・尾・左右のひれを証明済み4放射へ結合します。/)
  assert.match(app, /Bind the head, tail, and left\/right fins to the certified four-ray base\./)
})

test('candidate UI is bilingual, accessible, single-flight, and rejects stale ABA results', () => {
  assert.match(app, /設計候補の比較/)
  assert.match(app, /Compare design candidates/)
  assert.match(app, /aria-describedby="beginner-candidate-description"/)
  assert.match(app, /if \(beginnerCandidateBusy\) return/)
  assert.match(app, /latestSnapshotRef\.current !== current/)
})

test('AUT-107 fixes the initial bulge and elasticity policy in native, IPC, and UI', () => {
  assert.match(native, /TargetShapeApproximation/)
  assert.match(native, /BeginnerElasticityModelV1::NotComputed/)
  assert.match(client, /response\.bulge_treatment !== 'target_shape_approximation'/)
  assert.match(client, /response\.elasticity_model !== 'not_computed'/)
  assert.match(app, /膨らみを目標形状への近似として扱い/)
  assert.match(app, /does not compute paper elasticity/)
  assert.match(app, /role="note"/)
})

test('AUT-101 exposes bounded generated crease patterns and instructions as read-only previews', () => {
  assert.match(native, /generate_beginner_plans_v1/)
  assert.match(client, /response\.generated_plans\.length > 3/)
  assert.match(client, /record\.kind === 'composite_horn_tail_ear_base' \? 7/u)
  assert.match(client, /record\.kind === 'composite_horn_tail_ear_base' \? 6/u)
  assert.match(client, /record\.kind === 'composite_complete_insect_base' \? 21/u)
  assert.match(client, /record\.kind === 'composite_complete_insect_base' \? 20/u)
  assert.match(client, /record\.kind === 'composite_complete_animal_base' \? 11/u)
  assert.match(client, /record\.kind === 'composite_complete_animal_base' \? 10/u)
  assert.match(client, /record\.kind === 'composite_complete_winged_animal_base' \? 15/u)
  assert.match(client, /record\.kind === 'composite_complete_winged_animal_base' \? 14/u)
  assert.match(client, /vertexIds\.has\(edge\.start\)/)
  assert.match(client, /new Set\(admittedEdges\.map\(\(edge\) => edge\.id\)\)/)
  assert.match(app, /Candidate crease-pattern preview/)
  assert.match(app, /Candidate folding instructions/)
  assert.match(app, /read-only candidate/)
  assert.match(app, /plan\.crease_pattern\.edges\.map/)
  assert.match(app, /cancelBeginnerCandidates/)
  assert.match(app, /beginnerCandidateRequestRef\.current !== requestId/)
})

test('AUT-101 admits only explicit symmetric animal and insect templates', () => {
  assert.match(client, /'symmetric_four_leg_base'/)
  assert.match(client, /'symmetric_wing_base'/)
  assert.match(client, /'composite_complete_insect_base'/)
  assert.match(client, /'composite_complete_animal_base'/)
  assert.match(native, /UnsupportedAnimalTemplate/)
  assert.match(native, /UnsupportedInsectTemplate/)
  assert.match(native, /insect_complete_bindings_v1/)
  assert.match(native, /animal_complete_bindings_v1/)
  assert.match(app, /bilateral four-part protrusion target/)
  assert.match(app, /bilateral two-part protrusion target/)
  assert.match(app, /Create the symmetric four-leg base/)
  assert.match(app, /Create the bilateral wing base/)
  assert.match(app, /翅・触角・六脚の完全複合昆虫ベース/)
  assert.match(app, /Complete composite insect base/)
  assert.match(app, /角・尾・耳・四脚の完全複合動物ベース/)
  assert.match(app, /Complete composite animal base/)
  assert.match(completeAnimalBindingList, /protrusions\.length === 5 \? '五' : '四'/)
  assert.match(completeAnimalBindingList, /'Five' : 'Four'/)
  assert.match(client, /protrusions\.length !== \(completeAnimalHasWings \? 5 : 4\)/)
  assert.match(client, /protrusions\[4\]\?\.count !== 2/)
  assert.match(client, /protrusions\[3\]\?\.count !== 4/)
  assert.match(completeAnimalBindingList, /length \$\{target\.length_tenths_mm\} · thickness \$\{target\.thickness_tenths_mm\}/)
})

test('AUT-106 presents one recommendation first and adds bounded candidates on demand', () => {
  assert.match(native, /requested_candidate_count: u8/)
  assert.match(native, /candidates\.truncate\(usize::from\(requested_candidate_count\)\)/)
  assert.match(client, /response\.candidates\.length !== requestedCandidateCount/)
  assert.match(client, /requestedCandidateCount > 3/)
  assert.match(app, /requestBeginnerCandidates\(1\)/)
  assert.match(app, /requested_candidate_count \+ 1/)
  assert.match(app, /Generate and compare another candidate/)
  assert.match(app, /追加候補を生成して比較/)
})

test('generated candidates are geometry-gated with explicit local proof scope', () => {
  assert.match(native, /fn assess_beginner_generated_plan/)
  assert.match(native, /validate_crease_pattern\(&candidate_pattern\)/)
  assert.match(native, /analyze_local_flat_foldability\(paper, &candidate_pattern\)/)
  assert.match(native, /if !assessment\.apply_allowed/)
  assert.match(client, /response\.plan_assessments\.length !== response\.generated_plans\.length/)
  assert.match(client, /record\.expected_candidate_edge_id !== plan\.crease_pattern\.edges\[0\]/)
  assert.match(client, /'necessary', 'sufficient', 'indeterminate'/)
  assert.match(app, /候補の検証結果/)
  assert.match(app, /Warning: applying it does not guarantee flat foldability/)
  assert.match(app, /!assessment\.apply_allowed/)
})

test('generated candidates receive bounded global proof outcomes before apply', () => {
  assert.match(native, /MAX_CANDIDATE_GLOBAL_RECORDS/)
  assert.match(native, /analyze_global_flat_foldability/)
  assert.match(native, /GlobalFlatFoldabilityOutcome::Possible/)
  assert.match(native, /GlobalFlatFoldabilityOutcome::Impossible/)
  assert.match(native, /global_flat_foldability_impossible/)
  assert.match(client, /global_flat_foldability_proven/)
  assert.match(client, /global_resource_limit/)
  assert.match(app, /大域平坦折り可能性が証明されました/)
  assert.match(app, /Global validation is indeterminate because its resource limit was reached/)
})

test('GLB-backed candidates expose read-only quantized shape comparison', () => {
  assert.match(native, /compare_plan_to_reference_model_v1/)
  assert.match(native, /shape_approximation_score/)
  assert.match(native, /crease_preview_has_no_surface_mesh/)
  assert.match(client, /record\.shape_approximation_score/)
  assert.match(client, /record\.shape_difference_reason/)
  assert.match(app, /Read-only shape approximation to reference GLB/)
  assert.match(app, /the crease candidate has no surface mesh/)
})

test('AUT-101 apply rebinds candidate authority natively and requires confirmation', () => {
  assert.match(native, /fn apply_beginner_generated_plan/)
  assert.match(native, /expected_profile: ori_domain::BeginnerDesignProfileV1/)
  assert.match(native, /expected_candidate_edge_id: EdgeId/)
  assert.match(native, /generated candidate identity changed before apply/)
  assert.match(native, /Command::ApplyStackedFoldDocument/)
  assert.match(native, /SymmetricFourLegBase/)
  assert.match(native, /SymmetricWingBase/)
  assert.match(client, /invoke<ProjectSnapshot>\('apply_beginner_generated_plan'/)
  assert.match(client, /isCanonicalNonNilUuid\(expectedCandidateEdgeId\)/)
  assert.match(app, /window\.confirm/)
  assert.match(app, /Review and apply this candidate/)
  assert.match(app, /対角折り候補を確認して適用/)
})
