import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const app = source('../src/App.tsx')
const protrusionEditor = source('../src/components/ProtrusionDimensionEditor.tsx')
const client = source('../src/lib/coreClient.ts')
const native = source('../src-tauri/src/lib.rs')
const domain = source('../../../crates/ori-domain/src/beginner_design.rs')
const generation = source('../../../crates/ori-domain/src/beginner_generation.rs')
const generator = source('../../../crates/ori-domain/src/beginner_generator.rs')
const editor = source('../../../crates/ori-core/src/editor.rs')
const formats = source('../../../crates/ori-formats/src/lib.rs')

test('AUT-103 and AUT-104 expose three bounded on-device scoring presets', () => {
  assert.match(domain, /BEGINNER_DESIGN_PROFILE_SCHEMA_VERSION_V1: u32 = 1/u)
  assert.match(domain, /Balanced[\s\S]*ShapePriority[\s\S]*FoldabilityPriority/u)
  assert.match(domain, /== 100/u)
  assert.match(app, /Beginner design priorities/u)
  assert.match(app, /Shape fidelity priority/u)
  assert.match(app, /Foldability priority/u)
  assert.match(app, /It does not change the current crease pattern/u)
})

test('the profile crosses strict IPC and one native history command', () => {
  assert.match(client, /normalizeBeginnerDesignProfile/u)
  assert.match(client, /exactCoreDataRecord\(value, \[[\s\S]*?'schema_version'/u)
  assert.match(client, /update_beginner_design_profile/u)
  assert.match(native, /fn update_beginner_design_profile/u)
  assert.match(native, /expected_project_instance_id/u)
  assert.match(editor, /Command::UpdateBeginnerDesignProfile/u)
  assert.match(editor, /Inverse::RestoreBeginnerDesignProfile/u)
})

test('the versioned profile is project-saved and recovery-visible', () => {
  assert.match(formats, /pub beginner_design_profile: ori_domain::BeginnerDesignProfileV1/u)
  assert.match(native, /beginner_design_profile: self\.editor\.beginner_design_profile\(\)\.clone\(\)/u)
  assert.match(native, /saved\.beginner_design_profile != \*self\.editor\.beginner_design_profile\(\)/u)
  assert.match(app, /aria-describedby="beginner-design-weights"/u)
})

test('AUT-105 generation constraints share the profile history and strict project boundary', () => {
  assert.match(generation, /pub maximum_steps: u16/u)
  assert.match(generation, /pub detail_level: BeginnerDetailLevelV1/u)
  assert.match(generation, /pub allowed_techniques: Vec<BeginnerFoldTechniqueV1>/u)
  assert.match(client, /'maximum_steps',/u)
  assert.match(client, /record\.allowed_techniques\.length > 8/u)
  assert.match(app, /name="maximum_steps"/u)
  assert.match(app, /name="detail_level"/u)
  assert.match(app, /name="allowed_techniques"/u)
  assert.match(app, /利用可能な折り技法/u)
  assert.match(app, /Allowed fold techniques/u)
})

test('AUT-001 admits only the three versioned target categories and connects them to generation', () => {
  assert.match(generation, /enum BeginnerTargetCategoryV1[\s\S]*Animal[\s\S]*Insect[\s\S]*CustomObject/u)
  assert.match(client, /record\.target_category !== 'animal'/u)
  assert.match(client, /record\.target_category !== 'insect'/u)
  assert.match(client, /record\.target_category !== 'custom_object'/u)
  assert.match(app, /name="target_category"/u)
  assert.match(app, /初版で対応する目標形状は動物と昆虫だけ/u)
  assert.match(app, /Animal and insect use named templates/u)
})

test('custom object is versioned, bounded, and routed only to the generic tree candidate', () => {
  assert.match(generation, /BEGINNER_CUSTOM_OBJECT_DISPLAY_NAME_V1: &str = "Custom object"/u)
  assert.match(generation, /MAX_BEGINNER_CUSTOM_OBJECT_DISPLAY_NAME_CHARS_V1: usize = 64/u)
  assert.match(generator, /BeginnerTargetCategoryV1::CustomObject =>[\s\S]*CompositeGenericTargetBase/u)
  assert.match(generator, /target_category == BeginnerTargetCategoryV1::CustomObject[\s\S]*return Ok\(vec!\[template\]\)/u)
  assert.match(app, /<option value="custom_object">/u)
  assert.match(app, /Custom object is routed only to the bounded generic-tree candidate/u)
  assert.match(client, /normalizeCustomObjectDisplayName/u)
  assert.match(client, /\.trim\(\)\.normalize\('NFC'\)/u)
  assert.match(client, /\\u202A-\\u202E\\u2066-\\u2069/u)
  assert.match(app, /name="custom_object_display_name"/u)
  assert.match(app, /does not affect generator authority or candidate scoring/u)
  assert.match(native, /custom_object_display_name_v1\(&profile\.generation_constraints\)/u)
})

test('AUT-002 composes a bounded explicit target from supported parts', () => {
  assert.match(generation, /Head[\s\S]*Torso[\s\S]*Leg[\s\S]*Horn[\s\S]*Ear[\s\S]*Wing[\s\S]*Tail/u)
  assert.match(generation, /MAX_BEGINNER_TARGET_PARTS_TOTAL_V1: u16 = 32/u)
  assert.match(client, /record\.target_parts\.length > 8/u)
  assert.doesNotMatch(client, /partKinds\.has/u)
  assert.match(client, /partTotal > 32/u)
  assert.match(app, /name=\{`target_part_\$\{kind\}`\}/u)
  assert.match(app, /One head and one torso are required/u)
  assert.match(app, /Total parts: \{total\} \/ 32/u)
  assert.match(app, /候補に使用した目標部品/u)
})

test('AUT-003 stores and previews bounded stick skeleton bars with explicit dimensions', () => {
  assert.match(generation, /MAX_BEGINNER_SKELETON_SEGMENTS_V1: usize = 64/u)
  assert.match(generation, /pub thickness_tenths_mm: u16/u)
  assert.match(client, /record\.skeleton_segments\.length > 64/u)
  assert.match(client, /Math\.abs\(Number\(coordinate\)\) > 100_000/u)
  assert.match(app, /name="skeleton_length_mm"/u)
  assert.match(app, /name="skeleton_thickness_mm"/u)
  assert.match(app, /Stick skeleton preview/u)
  assert.match(app, /Only bars with explicit length and thickness are used for generation/u)
})

test('AUT-004 binds passive image and GLB references without granting generation authority', () => {
  assert.match(generation, /BeginnerTargetAssetReferenceV1/u)
  assert.match(client, /candidate\?\.kind === 'reference_image'/u)
  assert.match(client, /asset\.kind !== 'reference_model'/u)
  assert.match(client, /isCanonicalNonNilUuid\(asset\.underlay_id\)/u)
  assert.match(client, /isCanonicalNonNilUuid\(asset\.asset_id\)/u)
  assert.match(app, /name="target_reference_underlay"/u)
  assert.match(app, /Image contents are not inferred/u)
  assert.match(app, /grants no automatic recognition or fold-generation authority/u)
  assert.match(app, /selected project reference image as target input/u)
})

test('AUT-004 preview is bounded, project-bound, and stale-safe', () => {
  assert.match(client, /record\.positions\.length > 20_000/u)
  assert.match(client, /record\.triangle_indices\.length > 40_000/u)
  assert.match(client, /record\.project_instance_id !== expectedProjectInstanceId/u)
  assert.match(client, /record\.revision !== expectedRevision/u)
  assert.match(app, /beginnerReferenceRequestRef\.current/u)
  assert.match(app, /latest\.project_instance_id === geometry\.project_instance_id/u)
  assert.match(app, /Read-only 3D reference model/u)
})

test('AUT-004 retains multiple GLB references and switches exact active asset authority', () => {
  assert.match(native, /struct ReferenceModelAssetSummaryV1/u)
  assert.match(native, /sha256: sha2::Sha256::digest\(&asset\.bytes\)/u)
  assert.match(native, /fn activate_beginner_reference_model_asset/u)
  assert.match(native, /reference_model_asset_stale/u)
  assert.match(native, /Command::UpdateBeginnerDesignProfile \{\s*profile: Box::new\(profile\),?\s*\}/u)
  assert.match(client, /activate_beginner_reference_model_asset/u)
  assert.match(client, /reference_model_assets/u)
  assert.match(app, /Project 3D reference assets/u)
  assert.match(app, /Activate this reference/u)
  assert.match(app, /Active reference/u)
})

test('AUT-004 archives references without deleting bytes and keeps the transition undoable', () => {
  assert.match(native, /fn archive_beginner_reference_model_asset/u)
  assert.match(native, /archived_reference_model_asset_ids/u)
  assert.match(native, /profile\.generation_constraints\.target_asset = None/u)
  assert.match(native, /Command::UpdateBeginnerDesignProfile \{\s*profile: Box::new\(profile\),?\s*\}/u)
  assert.match(client, /archive_beginner_reference_model_asset/u)
  assert.match(client, /archived_reference_model_asset_ids/u)
  assert.match(app, /Archive reference without deleting bytes/u)
  assert.match(app, /Restore archived reference/u)
})

test('AUT-004 proposes only deterministic safe GLB geometry ranges and applies atomically', () => {
  assert.match(native, /derive_reference_model_suggestion_v1/u)
  assert.match(native, /bounded_bbox_area_normal_v1/u)
  assert.match(native, /surface_area_milli/u)
  assert.match(native, /dominant_normal_milli/u)
  assert.match(native, /reference_model_suggestion_matches_live_v1\(&expected_suggestion, &live\)/u)
  assert.match(native, /Command::UpdateBeginnerDesignProfile \{\s*profile: Box::new\(profile\),?\s*\}/u)
  assert.match(client, /suggest_beginner_reference_model_features/u)
  assert.match(client, /apply_beginner_reference_model_features/u)
  assert.match(app, /This is not 3D recognition/u)
  assert.match(app, /Confirm and apply suggested ranges/u)
  assert.match(app, /window\.confirm/u)
  assert.match(native, /reference_model_surface_selection_confirmation_required/u)
  assert.match(native, /reference_model_surface_selection_tampered/u)
  assert.match(native, /reference_model_surface_selection_matches_live_v1/u)
  assert.match(native, /struct BeginnerReferenceSurfaceRangeV1/u)
  assert.match(native, /digest_sha256: sha2::Sha256::digest/u)
  assert.match(native, /triangle_indices: vec!/u)
  assert.match(native, /reference_model_surface_range_is_connected_v1/u)
  assert.match(client, /surface_ranges: readonly Readonly/u)
  assert.match(client, /surfaceAssignments/u)
  assert.match(app, /Explicitly assign measured surface ranges to 2–8 parts/u)
  assert.match(app, /Duplicate, unconfirmed, or tampered ranges are rejected natively/u)
  assert.match(native, /struct BeginnerReferenceSurfaceEditV1/u)
  assert.match(native, /base_digest_sha256 == live_range\.digest_sha256/u)
  assert.match(native, /reference_model_surface_range_is_connected_v1\(&edited_range, geometry\)/u)
  assert.match(native, /triangles\.insert\(\*triangle\)/u)
  assert.match(client, /invalid reference model surface edit/u)
  assert.match(app, /Triangle indices \(add\/remove adjacent faces only\)/u)
})

test('general GLB target proposal is offline bounded read-only and explicitly copied', () => {
  assert.match(native, /general_protrusion_candidates: Vec<ori_domain::BeginnerProtrusionTargetV1>/u)
  assert.match(
    native,
    /candidate_points[\s\S]*?\.into_iter\(\)[\s\S]*?\.take\(if inferred_component_bridges \{ 8 \} else \{ 32 \}\)/u,
  )
  assert.match(native, /principal_axis_extents_tenths_mm/u)
  assert.match(native, /struct BeginnerReferenceStickBarV1/u)
  assert.match(native, /strict_glb_vertex_index_bounds/u)
  assert.match(client, /generalProtrusions\.length > 32/u)
  assert.match(client, /stickBars\.length !== 3/u)
  assert.match(app, /General 3D proposal: quality/u)
  assert.match(app, /Review and copy general 3D proposal to editor/u)
  assert.match(app, /setBeginnerSkeletonSegments\(suggestion\.stick_bars/u)
  assert.match(app, /setBeginnerProtrusions\(suggestion\.general_protrusion_candidates/u)
})

test('disconnected GLB components form only one bounded custom tree proposal', () => {
  assert.match(native, /fn disconnected_glb_stick_tree_v1/u)
  assert.match(native, /grouped\.len\(\) > 8/u)
  assert.match(native, /edges\.sort_unstable\(\)/u)
  assert.match(native, /bridges\.len\(\) \+ 1 != bounds\.len\(\)/u)
  assert.match(native, /raw\.len\(\) > 16/u)
  assert.match(native, /reference_model_component_projection_crossing/u)
  assert.match(native, /component_bridges_are_estimated/u)
  assert.match(client, /inferred_component_bridges/u)
  assert.match(app, /Bridges between disconnected 3D components are estimated/u)
  assert.match(app, /category\.value = 'custom_object'/u)
})

test('AUT-006 stores every bounded protrusion target attribute in profile history', () => {
  assert.match(generation, /struct BeginnerProtrusionTargetV1/u)
  for (const field of [
    'count', 'length_tenths_mm', 'thickness_tenths_mm', 'position_tenths_mm',
    'root_width_tenths_mm', 'tip_width_tenths_mm', 'local_outline_tenths_mm',
    'direction_milli', 'symmetry', 'curvature_degrees', 'joint',
    'motion_degrees', 'side', 'priority',
  ]) assert.match(generation, new RegExp(`pub ${field}:`, 'u'))
  assert.match(generation, /MAX_BEGINNER_PROTRUSIONS_V1/u)
  assert.match(client, /'protrusions'/u)
  assert.match(client, /protrusionIds/u)
  assert.match(app, /Protrusion targets/u)
  assert.match(app, /Add protrusion target/u)
  assert.match(app, /The project is unchanged until saved/u)
  assert.match(app, /onSubmit=\{submitBeginnerDesignProfile\}/u)
  assert.match(editor, /Command::UpdateBeginnerDesignProfile/u)
  assert.match(formats, /beginner_design_profile/u)
  assert.match(generation, /pub generic_body_size_tenths_mm: Option<\[u32; 2\]>/u)
  assert.match(client, /generic_body_size_tenths_mm\?: \[number, number\]/u)
  assert.match(app, /name="generic_body_width_mm"/u)
  assert.match(app, /name="generic_body_height_mm"/u)
  assert.match(app, /generic_body_size_tenths_mm: bodySize/u)
  assert.match(app, /name="protrusion_root_width_mm"/u)
  assert.match(app, /name="protrusion_tip_width_mm"/u)
  assert.match(app, /root_width_tenths_mm: Math\.round\(rootWidth \* 10\)/u)
  assert.match(app, /tip_width_tenths_mm: Math\.round\(tipWidth \* 10\)/u)
  assert.match(generation, /pub generic_body_outline_tenths_mm: Option<Vec<\[i32; 2\]>>/u)
  assert.match(client, /isCanonicalGenericBodyOutline/u)
  assert.match(app, /generic_body_outline_tenths_mm: beginnerBodyOutline/u)
  assert.match(generation, /enum BeginnerBodyOutlineModeV1[\s\S]*Symmetric[\s\S]*General/u)
  assert.match(client, /generic_body_outline_mode\?: 'symmetric' \| 'general'/u)
  assert.match(app, /generic_body_outline_mode: beginnerBodyOutlineMode/u)
  assert.match(client, /local_outline_tenths_mm\?: Array<\[number, number\]>/u)
  assert.match(client, /item\.symmetry === 'bilateral' \? 'symmetric_ccw' : 'general'/u)
  assert.match(app, /BeginnerShapeCanvasPreview/u)
  assert.match(app, /bodyOutline=\{beginnerBodyOutline\}/u)
  assert.match(app, /protrusions=\{beginnerProtrusions\}/u)
  assert.match(app, /onBodyOutlineChange=\{setBeginnerBodyOutline\}/u)
  assert.match(app, /onProtrusionChange=\{\(changed\)/u)
})

test('feature constraints remain individually editable and comparable before generation', () => {
  assert.match(app, /Feature constraint comparison/u)
  assert.match(app, /target\.motion_degrees\.join/u)
  assert.match(protrusionEditor, /Curvature binding/u)
  assert.match(protrusionEditor, /Motion minimum binding/u)
  assert.match(protrusionEditor, /Motion maximum binding/u)
  assert.match(protrusionEditor, /Joint binding/u)
  assert.match(protrusionEditor, /Side binding/u)
  assert.match(protrusionEditor, /Priority binding/u)
})

test('AUT-007 binds bounded 3D face ranges and bulge direction without elasticity', () => {
  assert.match(generation, /struct BeginnerBulgeTargetV1/u)
  assert.match(generation, /pub face_ids: Vec<FaceId>/u)
  assert.match(generation, /pub range_min_tenths_mm: \[i32; 3\]/u)
  assert.match(generation, /pub direction_milli: \[i16; 3\]/u)
  assert.match(generation, /pub amount_tenths_mm: u32/u)
  assert.match(native, /bulge_targets[\s\S]*source_fold_model_fingerprint != live_fingerprint/u)
  assert.match(client, /'bulge_targets'/u)
  assert.match(app, /3D bulge targets/u)
  assert.match(app, /selectedFaceId/u)
  assert.match(app, /Elasticity is not computed/u)
  assert.match(generation, /BeginnerReferenceSurfaceBindingV1/u)
  assert.match(generation, /range_digest_sha256: \[u8; 32\]/u)
  assert.match(native, /bulge_direction_milli != \[0, 0, 0\]/u)
  assert.match(native, /reference_surface_binding: Some/u)
  assert.match(native, /range_digest_sha256: edit\.base_digest_sha256/u)
  assert.match(client, /reference_surface_binding/u)
  assert.match(client, /bulge_amount_tenths_mm/u)
  assert.match(app, /Bulge direction \$\{axis\}/u)
  assert.match(app, /Bulge amount \(mm\)/u)
})

test('symmetric parameter estimates are bounded, stale-safe, and explicitly saved', () => {
  assert.match(client, /get_beginner_symmetric_parameter_estimate/u)
  assert.match(client, /apply_beginner_symmetric_parameters/u)
  assert.match(client, /Number\(estimate\.scale_percent\) < 10/u)
  assert.match(app, /Estimate symmetric parameters/u)
  assert.match(app, /Confirm design parameters/u)
  assert.match(app, /This does not start generation/u)
  assert.match(client, /record\.candidates\.length !== 3/u)
  assert.match(client, /approximation_score/u)
  assert.match(client, /complexity_score/u)
  assert.match(app, /Select this candidate/u)
})

function source(relativePath: string) {
  return readFileSync(new URL(relativePath, import.meta.url), 'utf8')
}
