import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const app = source('../src/App.tsx')
const client = source('../src/lib/coreClient.ts')
const native = source('../src-tauri/src/beginner_recognition.rs')
const domain = source('../../../crates/ori-domain/src/beginner_recognition.rs')
const designDomain = source('../../../crates/ori-domain/src/beginner_design.rs')

test('AUT-005 recognizes only bounded CRC-checked RGBA marker PNG data', () => {
  assert.match(native, /png::Decoder/u)
  assert.match(native, /next_frame/u)
  assert.match(native, /ColorType::Rgba/u)
  assert.match(native, /BitDepth::Eight/u)
  assert.match(native, /MAX_BEGINNER_RECOGNITION_DIMENSION_V1/u)
  assert.match(native, /MAX_BEGINNER_RECOGNITION_PIXELS_V1/u)
  assert.match(domain, /BeginnerRecognitionFormatV1[\s\S]*MarkerPngV1/u)
  assert.match(domain, /collect_component/u)
})

test('recognition is bound to the project instance, revision, underlay, asset, and bytes', () => {
  assert.match(native, /ensure_expected_project/u)
  assert.match(native, /underlay\.id == request\.underlay_id && underlay\.asset == request\.asset_id/u)
  assert.match(native, /Sha256::digest\(&bytes\)/u)
  assert.match(native, /live_hash != source_sha256/u)
  assert.match(client, /exactCoreDataRecord\(value, \[[\s\S]*?'source_sha256'/u)
  assert.match(client, /record\.source_underlay_id !== expectedUnderlayId/u)
  assert.match(client, /record\.source_asset_id !== expectedAssetId/u)
})

test('the read-only proposal is stale-safe, single-flight, and copied before normal save', () => {
  assert.match(app, /beginnerRecognitionRequestRef/u)
  assert.match(app, /beginnerRecognitionBusy/u)
  assert.match(app, /latest\.revision !== binding\.revision/u)
  assert.match(app, /Recognition proposal preview/u)
  assert.match(app, /Copy to editable fields/u)
  assert.match(app, /setBeginnerSkeletonSegments/u)
  assert.match(app, /input\[name\^="target_part_"\]/u)
  assert.match(app, /read-only outline proposal/u)
  assert.match(app, /no automatic design authority/u)
  assert.match(app, /onSubmit=\{submitBeginnerDesignProfile\}/u)
})

test('bounded PNG or JPEG silhouette recognition fails closed without inferred parts', () => {
  assert.match(domain, /SilhouettePngV1/u)
  assert.match(domain, /AmbiguousSilhouette/u)
  assert.match(domain, /UnsupportedSilhouette/u)
  assert.match(domain, /target_parts: Vec::new\(\)/u)
  assert.match(native, /recognition_ambiguous_silhouette/u)
  assert.match(native, /live_hash != source_sha256/u)
  assert.match(client, /recognize_beginner_silhouette/u)
  assert.match(client, /'silhouette_png_v1'/u)
  assert.match(native, /decode_general_jpeg/u)
  assert.match(native, /MAX_BEGINNER_RECOGNITION_PIXELS_V1/u)
  assert.match(app, /Recognize outline from image/u)
  assert.match(app, /read-only outline proposal/u)
  assert.match(app, /proposal\.target_parts\.length > 0/u)
  assert.match(client, /generic_body_outline_tenths_mm\?: Array<\[number, number\]>/u)
  assert.match(client, /protrusions\?: BeginnerGenerationConstraintsV1\['protrusions'\]/u)
  assert.match(app, /setBeginnerBodyOutline\(proposal\.generic_body_outline_tenths_mm/u)
  assert.match(app, /underlay\.asset === proposal\.source_asset_id/u)
  assert.match(app, /RecognitionContourCopyAction/u)
})

test('multiple silhouettes form one bounded custom tree only through inferred MST bridges', () => {
  assert.match(domain, /MAX_BEGINNER_MULTI_SILHOUETTE_COMPONENTS_V1: usize = 8/u)
  assert.match(domain, /MAX_BEGINNER_MULTI_SILHOUETTE_BARS_V1: usize = 16/u)
  assert.match(domain, /candidates\.sort_unstable\(\)/u)
  assert.match(domain, /bridges\.len\(\) \+ 1 != components\.len\(\)/u)
  assert.match(domain, /inferred_aabb_kruskal_mst_bridges/u)
  assert.match(domain, /component_bridges_are_estimated/u)
  assert.match(domain, /explicit_override_required: inferred_component_bridges/u)
  assert.match(client, /aabb_squared_distance_v1/u)
  assert.match(app, /=== 'aabb_squared_distance_v1' \? 'custom_object'/u)
})

test('multiple outline candidates stay strict, stale-safe, and read-only', () => {
  assert.match(client, /record\.candidates\.length > 16/u)
  assert.match(client, /'id', 'bounds', 'area_pixels', 'confidence_reason'/u)
  assert.match(client, /record\.project_instance_id !== expectedProjectInstanceId/u)
  assert.match(app, /Show outline candidates/u)
  assert.match(app, /Read-only outline candidates/u)
  assert.match(app, /They grant no generation authority/u)
  assert.match(app, /requestId === beginnerRecognitionRequestRef\.current/u)
})

test('an explicitly confirmed outline is revalidated and copied as one history command', () => {
  assert.match(native, /candidates\.get\(usize::from\(request\.candidate\.id\)\)/u)
  assert.match(native, /outline_candidate_stale/u)
  assert.match(native, /UpdateBeginnerDesignProfile/u)
  assert.match(client, /apply_beginner_outline_candidate/u)
  assert.match(client, /!confirmed \|\| !proposal\.candidates\.includes\(candidate\)/u)
  assert.match(app, /Confirm and copy to target/u)
  assert.match(app, /This does not start generation/u)
})

test('part suggestions require explicit assignment and one confirmed history command', () => {
  assert.match(native, /part_suggestion_ambiguous/u)
  assert.match(native, /part_assignment_stale/u)
  assert.match(native, /UpdateBeginnerDesignProfile/u)
  assert.match(client, /recognize_beginner_part_suggestions/u)
  assert.match(client, /apply_beginner_part_assignments/u)
  assert.match(app, /Explicit part assignments/u)
  assert.match(app, /Confirm target parts/u)
  assert.match(app, /This does not start generation/u)
  assert.match(app, /<option value="fin">/u)
  assert.match(app, /<option value="ear">/u)
  assert.match(app, /<option value="horn">/u)
  assert.match(app, /<option value="antenna">/u)
  assert.match(app, /<option value="tail">/u)
  assert.match(app, /image proves only each candidate outline/u)
  assert.match(app, /Exclude as image noise/u)
  assert.match(app, /assignment\.kind === 'torso'/u)
  assert.match(app, /beginnerPartAssignments\.length <= 2/u)
  assert.match(app, /items\.filter\(\(item\) => item\.candidate_id !== assignment\.candidate_id\)/u)
  assert.match(app, /Excluded image candidates/u)
  assert.match(app, /Restore candidate \{id\} with its original outline evidence/u)
  assert.match(app, /Restored candidates remain semantically unconfirmed/u)
  assert.match(app, /Outline component edit proposal/u)
  assert.match(app, /Split first part candidate/u)
  assert.match(app, /Merge first two part candidates/u)
  assert.match(native, /part_assignment_edit_digest_tampered/u)
  assert.match(native, /part_assignment_split_semantics_unconfirmed/u)
  assert.match(native, /part_assignment_split_boundary_tampered/u)
  assert.match(native, /crosses_outline/u)
  assert.match(app, /Vertical split position X \(px\)/u)
  assert.match(client, /split_x\?: number/u)
  assert.match(client, /sourceSha256: \[\.\.\.outline\.source_sha256\]/u)
  assert.match(app, /left\.candidate_id - right\.candidate_id/u)
  assert.match(native, /!specialized && \(2\.\.=8\)\.contains\(&feature_parts\.len\(\)\)/u)
  assert.match(native, /part_assignment_generic_binding_invalid/u)
  assert.match(native, /matches!\(count, 3 \| 5 \| 7 \| 8\)/u)
  assert.match(native, /repeated_single_rank/u)
  assert.match(native, /candidate\.bounds\.min_y, candidate\.bounds\.min_x, candidate\.id/u)
})

test('confirmed outline split and merge provenance persists with the editable profile', () => {
  assert.match(designDomain, /BeginnerOutlineEditAuthorityV1/u)
  assert.match(designDomain, /SplitVertical[\s\S]*source_candidate_id[\s\S]*split_x[\s\S]*fragment_kinds/u)
  assert.match(designDomain, /Merge[\s\S]*source_candidate_ids[\s\S]*merged_kind/u)
  assert.match(native, /profile\.outline_edit_authority/u)
  assert.match(native, /source_asset_id: request\.asset_id/u)
  assert.match(native, /source_sha256: request\.source_sha256/u)
  assert.match(client, /'reference_surface_landmarks_tenths_mm', 'outline_edit_authority'/u)
  assert.match(client, /JSON\.stringify\(profile\.outline_edit_authority\)/u)
  assert.match(app, /Saved outline edit authority/u)
})

test('recognized skeleton bars remain directly correctable before save and synthesis', () => {
  assert.match(domain, /MAX_BEGINNER_MEDIAL_AXIS_BARS_V1: usize = 32/u)
  assert.match(domain, /offline_manhattan_distance_ridges/u)
  assert.match(domain, /deterministic_axis_spans/u)
  assert.match(client, /expectedFormat === 'silhouette_png_v1' && constraints\.skeleton_segments\.length > 32/u)
  assert.match(client, /'score', 'reasons', 'insufficiency_reasons', 'distance_metric', 'bar_limit'/u)
  assert.match(app, /骨格候補の品質/u)
  assert.match(app, /Insufficiency reasons/u)
  assert.match(app, /Skeleton bar \$\{segment\.id\} \$\{label\} \(mm\)/u)
  assert.match(app, /setBeginnerSkeletonSegments\(\(segments\) => segments\.map/u)
  assert.match(app, /changed\.start\.x_tenths_mm === changed\.end\.x_tenths_mm/u)
  assert.match(app, /field === 'thickness_tenths_mm'/u)
  assert.match(app, /onSubmit=\{submitBeginnerDesignProfile\}/u)
})

test('explicit animal or insect parts feed the existing read-only symmetric plan evaluation', () => {
  assert.match(native, /BeginnerTargetCategoryV1::Insect/u)
  assert.match(native, /BeginnerTargetPartKindV1::Wing/u)
  assert.match(app, /<option value="wing">/u)
  assert.match(app, /evaluateBeginnerCandidates/u)
  assert.match(app, /Generated crease-pattern and instruction candidates/u)
  assert.match(app, /confirmAndApplyBeginnerPlan/u)
})

function source(relativePath: string) {
  return readFileSync(new URL(relativePath, import.meta.url), 'utf8')
}
