import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'

const client = readFileSync('src/lib/coreClient.ts', 'utf8')
const app = readFileSync('src/App.tsx', 'utf8')
const native = readFileSync('src-tauri/src/lib.rs', 'utf8')
const browser = readFileSync('scripts/generic-target-browser-e2e.mjs', 'utf8')
const browserHarness = readFileSync('scripts/generic-target-browser-harness.tsx', 'utf8')
const generator = readFileSync('../../crates/ori-domain/src/beginner_generator.rs', 'utf8')
const skeletonTree = readFileSync('src/lib/genericSkeletonTree.ts', 'utf8')

test('generic feature bindings cross the exact frontend DTO boundary', () => {
  assert.match(client, /generic_feature_bindings: ReadonlyArray/u)
  assert.match(client, /'crease_authority_sha256', 'skeleton_segment_id', 'skeleton_endpoint'/u)
  assert.match(client, /featureBindings\.length < 2/u)
  assert.match(client, /!\[1, 2, 4\]\.includes\(Number\(binding\.endpoint_count\)\)/u)
  assert.match(client, /Number\(binding\.crease_start\) \+ Number\(binding\.endpoint_count\)/u)
  assert.match(client, /normalizedPlans\.generated_plans\[index\]\.kind === 'composite_generic_target_base'/u)
})

test('generic feature topology is visible and browser-covered through persistence', () => {
  assert.match(app, /汎用部位topology証明/u)
  assert.match(app, /Generic feature topology witness/u)
  assert.match(app, /→skeleton/u)
  assert.match(native, /append_generic_tree_instruction_proposal/u)
  assert.match(native, /generic_tree_instruction_confirmation_required/u)
  assert.match(app, /Read-only folding instruction proposal/u)
  assert.match(browser, /Try tampered generic feature binding/u)
  assert.match(browser, /Generated generic feature instruction steps/u)
  assert.match(browser, /Undo generic target/u)
  assert.match(browser, /Redo generic target/u)
  assert.match(browser, /Save and reopen generic target/u)
})

test('3D generalization stays bounded to confirmed semantic parts', () => {
  assert.match(client, /protrusions\.length < 1 \|\| protrusions\.length > 8/u)
  assert.match(client, /semantic[\s\S]*remain the user's current target_parts/u)
  assert.match(app, /geometry evidence only; part meanings come from the parts you confirmed/u)
  assert.match(native, /four explicit generic features remain a bounded candidate/u)
  assert.match(native, /reference_model_suggestion_confirmation_required/u)
  assert.match(native, /reference_model_suggestion_matches_live_v1/u)
})

test('confirmed image and 3D generic candidates retain vertical proof coverage', () => {
  assert.match(browser, /Image meanings unconfirmed: generic topology candidate blocked/u)
  assert.match(browser, /Confirm explicit image part meanings/u)
  assert.match(browser, /Exclude unconfirmed image noise/u)
  assert.match(browser, /Restore excluded image candidate/u)
  assert.match(browser, /retained unique ID and outline evidence/u)
  assert.match(browser, /meaning remains unconfirmed/u)
  assert.match(browser, /Confirm GLB surface assignments/u)
  assert.match(browser, /tampered triangle range/u)
  assert.match(browser, /GLB surface meanings unconfirmed/u)
  assert.match(browser, /Split image outline component/u)
  assert.match(browser, /Outline edit unconfirmed/u)
  assert.match(browser, /source digest or component IDs tampered/u)
  assert.match(browser, /split line misses foreground contour/u)
  assert.match(native, /crease_authority_sha256/u)
  assert.match(native, /grid_candidate_feature_crease_authority_stale/u)
  assert.match(native, /canonical_targets\.sort_unstable_by_key/u)
  assert.match(client, /crease_authority_sha256: ReadonlyArray<number>/u)
  assert.match(browser, /feature ID changed during reorder/u)
  assert.match(native, /BeginnerSkeletonBranchBindingWitness/u)
  assert.match(native, /skeleton_tree_authority_sha256/u)
  assert.match(native, /segments\.len\(\) != skeleton_points\.len\(\)\.saturating_sub\(1\)/u)
  assert.match(client, /skeleton_branch_bindings: ReadonlyArray/u)
  assert.match(app, /Confirmed tree skeleton/u)
  assert.match(browser, /Try tampered skeleton branch graph/u)
  assert.match(app, /analyzeGenericSkeletonTree/u)
  assert.match(app, /Cycles, duplicate edges, and disconnected skeletons cannot generate candidates/u)
  assert.match(app, /beginnerSkeletonTree\.status !== 'tree'/u)
  assert.match(browser, /Applied image outline evidence \+ 2 explicitly confirmed part meanings/u)
  assert.match(browserHarness, /Global flat-foldability proven/u)
  assert.match(browserHarness, /Native foldability admission: global proof \+ bounded fold path certificate/u)
  assert.match(browserHarness, /Generated generic feature instruction steps/u)
  assert.match(browser, /Undo generic target/u)
  assert.match(browser, /Redo generic target/u)
  assert.match(browser, /Save and reopen generic target/u)
})

test('image and GLB skeletons admit only bounded acyclic river-axial proposals', () => {
  assert.match(generator, /fn bounded_tree_skeleton_length_ratios/u)
  assert.match(generator, /MAX_BEGINNER_GENERIC_TREE_BARS_V1: usize = 16/u)
  assert.match(generator, /MAX_BEGINNER_GENERIC_TREE_INTERSECTION_PAIRS_V1: usize = 120/u)
  assert.match(generator, /MAX_BEGINNER_GENERIC_TREE_NODES_V1: usize = 17/u)
  assert.match(generator, /points\.len\(\) != segments\.len\(\) \+ 1/u)
  assert.match(generator, /bounded_tree_river_axial_v1/u)
  assert.match(generator, /fn append_bounded_radial_tree_graph/u)
  assert.match(generator, /bounded-tree-node:/u)
  assert.match(generator, /bounded-tree-river:/u)
  assert.match(generator, /bounded_tree_branch_topology_v1/u)
  assert.match(generator, /o1\.signum\(\) != o2\.signum\(\)/u)
  assert.match(generator, /\(min_x\.\.=max_x\)\.contains\(&position\.x\)/u)
  assert.match(generator, /saturating_mul\(1_000_000\)/u)
  assert.match(skeletonTree, /segments\.length > 16/u)
  assert.match(native, /validate_beginner_manufacturability_v1/u)
  assert.match(native, /assess_beginner_generated_plan_with_deadline/u)
  assert.match(native, /beginner_plan_paper_efficiency_score_v1/u)
  assert.match(native, /MAX_BEGINNER_GENERIC_TREE_ORIENTATIONS_V1: usize = 2/u)
  assert.match(native, /MAX_BEGINNER_GENERIC_TREE_PRIMARY_WORK_V1/u)
  assert.match(native, /bounded_tree_paper_orientation_v1:horizontal/u)
  assert.match(native, /bounded_tree_paper_orientation_v1:vertical/u)
  assert.match(native, /\.take\(MAX_BEGINNER_GENERIC_TREE_ORIENTATIONS_V1\)/u)
  assert.match(app, /beginnerSkeletonTree\.status !== 'tree'/u)
})

test('applied generic trees persist inert versioned source provenance', () => {
  assert.match(native, /BeginnerGenericTreeSourceV1::ImageSilhouette/u)
  assert.match(native, /BeginnerGenericTreeSourceV1::GlbGeometry/u)
  assert.match(native, /BeginnerGenericTreeSourceV1::ManualSkeleton/u)
  assert.match(native, /asset_content_sha256/u)
  assert.match(native, /grid_candidate_tree_ratio_provenance_invalid/u)
  assert.match(native, /generator_version: 1/u)
  assert.match(native, /authorizes_apply: false/u)
  assert.match(client, /generic_tree/u)
  assert.match(client, /genericTree\.generator_version !== 1 \|\| genericTree\.authorizes_apply !== false/u)
  assert.match(app, /display only; no apply authority/u)
  assert.doesNotMatch(app, /asset_content_sha256.*slice/u)
  assert.match(native, /live_asset_sha256 != tree\.asset_content_sha256/u)
  assert.match(native, /proposal\.authorizes_apply \|\| proposal\.physical_motion_proof/u)
  assert.match(native, /Command::AppendInstructionSteps \{ steps \}/u)
  assert.match(app, /Confirm and append to instructions/u)
})
