import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {afterEach,expect,it,vi} from 'vitest'
import type {ProjectSnapshot} from '../src/lib/coreClient.ts'
const A='a0000000-0000-4000-8000-000000000001',B='a0000000-0000-4000-8000-000000000002',E='b0000000-0000-4000-8000-000000000001'
const snapshot={project_instance_id:'11111111-1111-4111-8111-111111111111',project_id:'22222222-2222-4222-8222-222222222222',name:'Array',memo:'',current_path:null,revision:7,saved_revision:7,is_dirty:false,crease_pattern:{vertices:[{id:A,position:{x:10,y:20}},{id:B,position:{x:20,y:20}}],edges:[{id:E,start:A,end:B,kind:'mountain'}]},paper:{boundary_vertices:[],thickness_mm:.1,length_display_unit:'mm',cutting_allowed:false,front:{color:{red:255,green:255,blue:255,alpha:255},texture_asset:null},back:{color:{red:248,green:248,blue:245,alpha:255},texture_asset:null}},instruction_timeline:{steps:[]},numeric_expressions:{},geometric_constraints:{schema_version:1,constraints:[]},beginner_design_profile:{schema_version:1,preset:'balanced',shape_fidelity_weight:35,foldability_weight:35,step_count_weight:15,paper_efficiency_weight:15,generation_constraints:{schema_version:1,maximum_steps:60,detail_level:'standard',target_category:null,target_parts:[],skeleton_segments:[],protrusions:[],bulge_targets:[],target_asset:null,allowed_techniques:['valley_fold','mountain_fold']}},project_layers:{schema_version:1,layers:[{id:'00000000-0000-4000-8000-000000000001',name:'Crease Pattern',content_kind:'crease_pattern',visible:true,locked:false,opacity:1}],edge_assignments:[]},element_metadata:{vertices:[],edges:[],faces:[]},annotations:{schema_version:1,annotations:[]},underlays:{schema_version:1,underlays:[]},fold_model_fingerprint:'a'.repeat(64),can_undo:false,can_redo:false,cutting_allowed:false} as ProjectSnapshot
const previewResult={version:1 as const,project_instance_id:snapshot.project_instance_id,project_id:snapshot.project_id,revision:7,request_sha256:'c'.repeat(64),source_vertex_count:2,source_edge_count:1,additional_copies:1,generated_vertex_count:2,generated_edge_seed_count:1,authorizes_project_mutation:false as const}
const mocks=vi.hoisted(()=>({preview:vi.fn(),confirm:vi.fn(),get:vi.fn(),recovery:vi.fn()}))
vi.mock('../src/lib/coreClient',async i=>({...await i<typeof import('../src/lib/coreClient.ts')>(),previewLinearArray:mocks.preview,confirmLinearArray:mocks.confirm,getProjectSnapshot:mocks.get}))
vi.mock('../src/lib/recoveryClient',async i=>({...await i<typeof import('../src/lib/recoveryClient.ts')>(),getRecoveryCandidate:mocks.recovery}))
vi.mock('@tauri-apps/api/window',()=>({getCurrentWindow:()=>({onCloseRequested:async()=>()=>{},close:async()=>{}})}));vi.mock('@tauri-apps/api/event',()=>({listen:async()=>()=>{}}))
vi.mock('../src/components/CreaseCanvas',()=>({CreaseCanvas:({onSelectLine}:{onSelectLine?:(id:string)=>void})=><button data-testid="line" onClick={()=>onSelectLine?.(E)}>line</button>}));vi.mock('../src/components/FoldPreview',()=>({FoldPreview:()=> <div/>}));vi.mock('../src/components/InstructionTimelinePanel',()=>({InstructionTimelinePanel:()=> <div/>}));vi.mock('../src/components/GlobalFlatFoldabilityPanel',()=>({GlobalFlatFoldabilityPanel:()=> <div/>}));vi.mock('../src/components/WorkspaceLayoutSeparator',()=>({WorkspaceLayoutSeparator:()=> <div/>}))
import App from '../src/App.tsx'
afterEach(()=>{cleanup();Reflect.deleteProperty(window,'__TAURI_INTERNALS__');vi.clearAllMocks()})
async function setup(){Object.defineProperty(window,'__TAURI_INTERNALS__',{configurable:true,value:{}});mocks.get.mockResolvedValue(snapshot);mocks.recovery.mockResolvedValue({schema_version:1,status:'none'});render(<App/>);await waitFor(()=>expect(mocks.get).toHaveBeenCalled());await waitFor(()=>expect(document.querySelector('main')?.hasAttribute('inert')).toBe(false));fireEvent.click(screen.getByTestId('line'));return screen.findByTestId('linear-array-panel')}
function submit(copies='1',dx='10',dy='0'){fireEvent.change(document.querySelector('input[name="linear_array_copies"]')!,{target:{value:copies}});fireEvent.change(document.querySelector('input[name="linear_array_dx"]')!,{target:{value:dx}});fireEvent.change(document.querySelector('input[name="linear_array_dy"]')!,{target:{value:dy}});fireEvent.click(screen.getByTestId('preview-linear-array'))}
it('previews exact payload and confirms the same request and digest',async()=>{await setup();mocks.preview.mockResolvedValue(previewResult);mocks.confirm.mockRejectedValue(new Error('captured'));submit();await screen.findByTestId('linear-array-preview');const request={vertices:[A,B].sort(),edges:[E],additional_copies:1,delta:{x:10,y:0}};expect(mocks.preview).toHaveBeenCalledWith(snapshot.project_id,7,snapshot.project_instance_id,request);fireEvent.click(screen.getByTestId('confirm-linear-array'));await waitFor(()=>expect(mocks.confirm).toHaveBeenCalledWith(snapshot.project_id,7,snapshot.project_instance_id,request,'c'.repeat(64)))})
it('rejects authorizing preview, invalid input, and cancellation without confirm',async()=>{await setup();mocks.preview.mockResolvedValue({...previewResult,authorizes_project_mutation:true});submit();await waitFor(()=>expect(mocks.preview).toHaveBeenCalledTimes(1));expect(screen.queryByTestId('linear-array-preview')).toBeNull();submit('0','0','0');expect(mocks.preview).toHaveBeenCalledTimes(1);mocks.preview.mockResolvedValue(previewResult);submit();await screen.findByTestId('linear-array-preview');fireEvent.click(screen.getByRole('button',{name:'キャンセル'}));expect(mocks.confirm).not.toHaveBeenCalled()})
it('ignores out-of-order and valid-then-invalid preview responses',async()=>{await setup();let resolveFirst!:(value:typeof previewResult)=>void;mocks.preview.mockImplementationOnce(()=>new Promise(resolve=>{resolveFirst=resolve})).mockResolvedValueOnce({...previewResult,request_sha256:'d'.repeat(64),additional_copies:2,generated_vertex_count:4,generated_edge_seed_count:2});submit('1','10','0');submit('2','20','0');await screen.findByTestId('linear-array-preview');resolveFirst(previewResult);await Promise.resolve();expect(screen.getByTestId('linear-array-preview').textContent).toContain('4');let resolveThird!:(value:typeof previewResult)=>void;mocks.preview.mockImplementationOnce(()=>new Promise(resolve=>{resolveThird=resolve}));submit('1','10','0');fireEvent.input(document.querySelector('input[name="linear_array_copies"]')!,{target:{value:'0'}});await waitFor(()=>expect(screen.queryByTestId('linear-array-preview')).toBeNull());resolveThird(previewResult);await Promise.resolve();expect(screen.queryByTestId('linear-array-preview')).toBeNull()})
