import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {afterEach,expect,it,vi} from 'vitest'
import type {ProjectSnapshot} from '../src/lib/coreClient.ts'
const V='a0000000-0000-4000-8000-000000000005'
const DEFAULT_LAYER='00000000-0000-4000-8000-000000000001'
const WRITABLE_LAYER='b0000000-0000-4000-8000-000000000001'
const OTHER_VERTEX='c0000000-0000-4000-8000-000000000001'
const WRITABLE_EDGE='d0000000-0000-4000-8000-000000000001'
const LOCKED_OTHER_VERTEX='e0000000-0000-4000-8000-000000000001'
const DEFAULT_EDGE='f0000000-0000-4000-8000-000000000001'
const snapshot={project_instance_id:'11111111-1111-4111-8111-111111111111',project_id:'22222222-2222-4222-8222-222222222222',name:'Ray',memo:'',current_path:null,revision:7,saved_revision:7,is_dirty:false,crease_pattern:{vertices:[{id:V,position:{x:10,y:25}}],edges:[]},paper:{boundary_vertices:[],thickness_mm:.1,length_display_unit:'mm',cutting_allowed:false,front:{color:{red:255,green:255,blue:255,alpha:255},texture_asset:null},back:{color:{red:248,green:248,blue:245,alpha:255},texture_asset:null}},instruction_timeline:{steps:[]},numeric_expressions:{},geometric_constraints:{schema_version:1,constraints:[]},beginner_design_profile:{schema_version:1,preset:'balanced',shape_fidelity_weight:35,foldability_weight:35,step_count_weight:15,paper_efficiency_weight:15,generation_constraints:{schema_version:1,maximum_steps:60,detail_level:'standard',target_category:null,target_parts:[],skeleton_segments:[],protrusions:[],bulge_targets:[],target_asset:null,allowed_techniques:['valley_fold','mountain_fold']}},project_layers:{schema_version:1,layers:[{id:'00000000-0000-4000-8000-000000000001',name:'Crease Pattern',content_kind:'crease_pattern',visible:true,locked:false,opacity:1}],edge_assignments:[]},element_metadata:{vertices:[],edges:[],faces:[]},annotations:{schema_version:1,annotations:[]},underlays:{schema_version:1,underlays:[]},fold_model_fingerprint:'a'.repeat(64),can_undo:false,can_redo:false,cutting_allowed:false} as ProjectSnapshot
function lockedDefaultWritableSnapshot(){return {...snapshot,crease_pattern:{vertices:[...snapshot.crease_pattern.vertices,{id:OTHER_VERTEX,position:{x:20,y:25}},{id:LOCKED_OTHER_VERTEX,position:{x:10,y:35}}],edges:[{id:WRITABLE_EDGE,start:V,end:OTHER_VERTEX,kind:'mountain' as const},{id:DEFAULT_EDGE,start:V,end:LOCKED_OTHER_VERTEX,kind:'valley' as const}]},project_layers:{schema_version:1 as const,layers:[{...snapshot.project_layers.layers[0],locked:true},{id:WRITABLE_LAYER,name:'Writable',content_kind:'crease_pattern' as const,visible:true,locked:false,opacity:1}],edge_assignments:[{edge:WRITABLE_EDGE,layer:WRITABLE_LAYER}]}} as ProjectSnapshot}
const mocks=vi.hoisted(()=>({add:vi.fn(),connected:vi.fn(),get:vi.fn(),recovery:vi.fn()}))
vi.mock('../src/lib/coreClient',async i=>({...await i<typeof import('../src/lib/coreClient.ts')>(),addConnectedVertex:mocks.connected,addRayToFirstTarget:mocks.add,getProjectSnapshot:mocks.get}))
vi.mock('../src/lib/recoveryClient',async i=>({...await i<typeof import('../src/lib/recoveryClient.ts')>(),getRecoveryCandidate:mocks.recovery}))
vi.mock('../src/lib/numericExpressionNative',async i=>({...await i<typeof import('../src/lib/numericExpressionNative.ts')>(),evaluateFiniteNumericExpression:async(source:string)=>({value:Number(source)})}))
vi.mock('@tauri-apps/api/window',()=>({getCurrentWindow:()=>({onCloseRequested:async()=>()=>{},close:async()=>{}})}));vi.mock('@tauri-apps/api/event',()=>({listen:async()=>()=>{}}))
vi.mock('../src/components/CreaseCanvas',()=>({CreaseCanvas:({onSelectVertex}:{onSelectVertex?:(id:string)=>void})=><button data-testid="source" onClick={()=>onSelectVertex?.(V)}>source</button>}));vi.mock('../src/components/FoldPreview',()=>({FoldPreview:()=> <div/>}));vi.mock('../src/components/InstructionTimelinePanel',()=>({InstructionTimelinePanel:()=> <div/>}));vi.mock('../src/components/GlobalFlatFoldabilityPanel',()=>({GlobalFlatFoldabilityPanel:()=> <div/>}));vi.mock('../src/components/WorkspaceLayoutSeparator',()=>({WorkspaceLayoutSeparator:()=> <div/>}))
import App from '../src/App.tsx'
afterEach(()=>{cleanup();Reflect.deleteProperty(window,'__TAURI_INTERNALS__');vi.clearAllMocks()})
async function setup(cutting=false,current=snapshot){Object.defineProperty(window,'__TAURI_INTERNALS__',{configurable:true,value:{}});mocks.get.mockResolvedValue({...current,cutting_allowed:cutting,paper:{...current.paper,cutting_allowed:cutting}});mocks.recovery.mockResolvedValue({schema_version:1,status:'none'});render(<App/>);await waitFor(()=>expect(mocks.get).toHaveBeenCalled());expect(mocks.recovery).toHaveBeenCalled();await waitFor(()=>expect(document.querySelector('main')?.hasAttribute('inert')).toBe(false));fireEvent.click(screen.getByTestId('source'));const button=await screen.findByTestId('draw-ray-to-first-target') as HTMLButtonElement;await waitFor(()=>expect(button.disabled).toBe(false));return button}
function submitWithButton(button:HTMLButtonElement){const form=button.form;expect(form).not.toBeNull();fireEvent(form!,new SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:button}))}
it('invokes with exact bindings, microdegrees, and resolved layer',async()=>{mocks.add.mockRejectedValue(new Error('captured'));const b=await setup();fireEvent.change(screen.getByLabelText('始点からの角度 (度)'),{target:{value:'12.345678'}});submitWithButton(b);await waitFor(()=>expect(mocks.add).toHaveBeenCalledTimes(1));expect(mocks.add.mock.calls[0]).toEqual([snapshot.project_id,7,snapshot.project_instance_id,V,12345678,'mountain',DEFAULT_LAYER]);await waitFor(()=>expect(b.disabled).toBe(false))})
it('allows a locked-layer vertex to start a ray on the writable crease layer',async()=>{mocks.add.mockRejectedValue(new Error('captured'));const b=await setup(false,lockedDefaultWritableSnapshot());expect((document.querySelector('input[name="x_display"]') as HTMLInputElement).disabled).toBe(true);expect((document.querySelector('button[value="polar_endpoint"]') as HTMLButtonElement).disabled).toBe(false);submitWithButton(b);await waitFor(()=>expect(mocks.add).toHaveBeenCalledTimes(1));expect(mocks.add.mock.calls[0]?.at(-1)).toBe(WRITABLE_LAYER)})
it('allows the same locked-layer vertex to start a polar endpoint on the writable crease layer',async()=>{mocks.connected.mockRejectedValue(new Error('captured'));await setup(false,lockedDefaultWritableSnapshot());const b=document.querySelector('button[value="polar_endpoint"]') as HTMLButtonElement;expect(b.disabled).toBe(false);submitWithButton(b);await waitFor(()=>expect(mocks.connected).toHaveBeenCalledTimes(1));expect(mocks.connected.mock.calls[0]?.at(-1)).toBe(WRITABLE_LAYER)})
it.each(['12.3456789','360'])('rejects %s',async value=>{const b=await setup();fireEvent.change(document.querySelector('input[name="polar_angle_degrees"]')!,{target:{value}});submitWithButton(b);expect(await screen.findByText(/小数6桁以内/u,{}, {timeout:5000})).toBeTruthy();expect(mocks.add).not.toHaveBeenCalled()},15000)
it('rejects a forged cut selection while cutting is disabled',async()=>{const b=await setup(false);expect(screen.queryByRole('option',{name:'切断線'})).toBeNull();const select=document.querySelector('select[name="polar_edge_kind"]')!;const forged=document.createElement('option');forged.value='cut';forged.textContent='forged cut';select.append(forged);fireEvent.change(select,{target:{value:'cut'}});submitWithButton(b);expect(await screen.findByText(/利用可能な線種/u)).toBeTruthy();expect(mocks.add).not.toHaveBeenCalled()})
