import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {afterEach,expect,it,vi} from 'vitest'
import type {ProjectSnapshot} from '../src/lib/coreClient.ts'
const V='a0000000-0000-4000-8000-000000000005'
const snapshot={project_instance_id:'11111111-1111-4111-8111-111111111111',project_id:'22222222-2222-4222-8222-222222222222',name:'Ray',memo:'',current_path:null,revision:7,saved_revision:7,is_dirty:false,crease_pattern:{vertices:[{id:V,position:{x:10,y:25}}],edges:[]},paper:{boundary_vertices:[],thickness_mm:.1,length_display_unit:'mm',cutting_allowed:false,front:{color:{red:255,green:255,blue:255,alpha:255},texture_asset:null},back:{color:{red:248,green:248,blue:245,alpha:255},texture_asset:null}},instruction_timeline:{steps:[]},numeric_expressions:{},geometric_constraints:{schema_version:1,constraints:[]},beginner_design_profile:{schema_version:1,preset:'balanced',shape_fidelity_weight:35,foldability_weight:35,step_count_weight:15,paper_efficiency_weight:15,generation_constraints:{schema_version:1,maximum_steps:60,detail_level:'standard',target_category:null,target_parts:[],skeleton_segments:[],protrusions:[],bulge_targets:[],target_asset:null,allowed_techniques:['valley_fold','mountain_fold']}},project_layers:{schema_version:1,layers:[{id:'00000000-0000-4000-8000-000000000001',name:'Crease Pattern',content_kind:'crease_pattern',visible:true,locked:false,opacity:1}],edge_assignments:[]},element_metadata:{vertices:[],edges:[],faces:[]},annotations:{schema_version:1,annotations:[]},underlays:{schema_version:1,underlays:[]},fold_model_fingerprint:'a'.repeat(64),can_undo:false,can_redo:false,cutting_allowed:false} as ProjectSnapshot
const mocks=vi.hoisted(()=>({add:vi.fn(),get:vi.fn(),recovery:vi.fn()}))
vi.mock('../src/lib/coreClient',async i=>({...await i<typeof import('../src/lib/coreClient.ts')>(),addRayToFirstTarget:mocks.add,getProjectSnapshot:mocks.get}))
vi.mock('../src/lib/recoveryClient',async i=>({...await i<typeof import('../src/lib/recoveryClient.ts')>(),getRecoveryCandidate:mocks.recovery}))
vi.mock('../src/lib/numericExpressionNative',async i=>({...await i<typeof import('../src/lib/numericExpressionNative.ts')>(),evaluateFiniteNumericExpression:async(source:string)=>({value:Number(source)})}))
vi.mock('@tauri-apps/api/window',()=>({getCurrentWindow:()=>({onCloseRequested:async()=>()=>{},close:async()=>{}})}));vi.mock('@tauri-apps/api/event',()=>({listen:async()=>()=>{}}))
vi.mock('../src/components/CreaseCanvas',()=>({CreaseCanvas:({onSelectVertex}:{onSelectVertex?:(id:string)=>void})=><button data-testid="source" onClick={()=>onSelectVertex?.(V)}>source</button>}));vi.mock('../src/components/FoldPreview',()=>({FoldPreview:()=> <div/>}));vi.mock('../src/components/InstructionTimelinePanel',()=>({InstructionTimelinePanel:()=> <div/>}));vi.mock('../src/components/GlobalFlatFoldabilityPanel',()=>({GlobalFlatFoldabilityPanel:()=> <div/>}));vi.mock('../src/components/WorkspaceLayoutSeparator',()=>({WorkspaceLayoutSeparator:()=> <div/>}))
import App from '../src/App.tsx'
afterEach(()=>{cleanup();Reflect.deleteProperty(window,'__TAURI_INTERNALS__');vi.clearAllMocks()})
async function setup(cutting=false){Object.defineProperty(window,'__TAURI_INTERNALS__',{configurable:true,value:{}});mocks.get.mockResolvedValue({...snapshot,cutting_allowed:cutting,paper:{...snapshot.paper,cutting_allowed:cutting}});mocks.recovery.mockResolvedValue({schema_version:1,status:'none'});render(<App/>);await waitFor(()=>expect(mocks.get).toHaveBeenCalled());expect(mocks.recovery).toHaveBeenCalled();await waitFor(()=>expect(document.querySelector('main')?.hasAttribute('inert')).toBe(false));fireEvent.click(screen.getByTestId('source'));return screen.findByTestId('draw-ray-to-first-target')}
it('invokes with exact bindings and microdegrees',async()=>{mocks.add.mockRejectedValue(new Error('captured'));const b=await setup();fireEvent.change(screen.getByLabelText('始点からの角度 (度)'),{target:{value:'12.345678'}});fireEvent.click(b);await waitFor(()=>expect(mocks.add).toHaveBeenCalledTimes(1));expect(mocks.add.mock.calls[0]).toEqual([snapshot.project_id,7,snapshot.project_instance_id,V,12345678,'mountain'])})
it.each(['12.3456789','360'])('rejects %s',async value=>{const b=await setup();fireEvent.change(document.querySelector('input[name="polar_angle_degrees"]')!,{target:{value}});fireEvent.click(b);expect(await screen.findByText(/小数6桁以内/u)).toBeTruthy();expect(mocks.add).not.toHaveBeenCalled()})
it('rejects a forged cut selection while cutting is disabled',async()=>{const b=await setup(false);expect(screen.queryByRole('option',{name:'切断線'})).toBeNull();const select=document.querySelector('select[name="polar_edge_kind"]')!;const forged=document.createElement('option');forged.value='cut';forged.textContent='forged cut';select.append(forged);fireEvent.change(select,{target:{value:'cut'}});fireEvent.click(b);expect(await screen.findByText(/利用可能な線種/u)).toBeTruthy();expect(mocks.add).not.toHaveBeenCalled()})
