//! Phase 3K join for canonical binary64 representation-boundary pose transforms.
//!
//! This promotion consumes Phase 3J and separately issued kinematics evidence
//! for the exact same two pose objects. It proves only that the two scheduled
//! representation-boundary angle carriers with positive thickness also carry
//! the deterministic binary64 transforms regenerated by the production
//! spanning-tree solver. Caller-tolerance closure is not strengthened into
//! mathematical exact closure.

use ori_kinematics::{
    CanonicalBinary64PosePairTransformRealizationErrorV2,
    CanonicalBinary64PosePairTransformRealizationEvidenceV2,
    CanonicalBinary64PosePairTransformRealizationInputV2,
    CanonicalBinary64PosePairTransformRealizationLimitsV2,
    CanonicalBinary64PosePairTransformRealizationStopV2, ClosedMaterialHingeGraphPose,
    MaterialHingeGraphGeometry,
};
use thiserror::Error;

use super::{
    CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseAngleIdentityPositiveThicknessPrerequisiteErrorV2,
    CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseAngleIdentityPositiveThicknessPrerequisiteRevalidationInputV2,
    CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseAngleIdentityPositiveThicknessPrerequisiteStopV2,
    CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseAngleIdentityPositiveThicknessPrerequisiteV2,
};

pub const COMMON_ARTICULATION_DYNAMIC_GENERAL_N_CLOSED_DYADIC_REPRESENTATION_BOUNDARY_POSE_CANONICAL_BINARY64_TRANSFORM_POSITIVE_THICKNESS_PREREQUISITE_MODEL_ID_V2: &str =
    "common_articulation_dynamic_general_n_closed_dyadic_representation_boundary_pose_canonical_binary64_transform_positive_thickness_prerequisite_v2";

pub(crate) const COMPOSITION_WORKSPACE_BYTES_V2: usize = 512;

#[path = "closed_dyadic_representation_boundary_pose_canonical_binary64_transform_positive_thickness/binding.rs"]
mod binding;
#[path = "closed_dyadic_representation_boundary_pose_canonical_binary64_transform_positive_thickness/resources.rs"]
mod resources;
#[path = "closed_dyadic_representation_boundary_pose_canonical_binary64_transform_positive_thickness/validation.rs"]
mod validation;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteStopV2
{
    Cancelled,
    DeadlineExceeded,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
pub enum CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteErrorV2
{
    #[error("the Phase 3K canonical binary64 pose join exceeds its finite resource envelope")]
    ResourceLimit,
    #[error("the retained Phase 3J prerequisite does not replay: {0}")]
    PoseAngleIdentityPositiveThickness(
        CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseAngleIdentityPositiveThicknessPrerequisiteErrorV2,
    ),
    #[error("the retained canonical binary64 pose-transform evidence does not replay: {0}")]
    CanonicalBinary64Transform(CanonicalBinary64PosePairTransformRealizationErrorV2),
    #[error("the Phase 3K canonical binary64 pose join does not match the live replay")]
    CertificateBindingMismatch,
    #[error("the Phase 3K canonical binary64 pose join was cancelled")]
    Cancelled,
    #[error("the Phase 3K canonical binary64 pose join deadline elapsed")]
    DeadlineExceeded,
}

/// Replay-bound policy for the Phase 3J proof and canonical binary64 verifier.
///
/// Count, retained-byte, workspace, publication and aggregate fields are upper
/// caps retained as exact replay-policy values. Canonical logical work is an
/// exact identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteLimitsV2
{
    pub max_blocks: usize,
    pub max_faces: usize,
    pub max_hinges: usize,
    pub max_pose_pair_deep_retained_bytes: usize,
    pub max_canonical_transform_logical_work: usize,
    pub max_canonical_transform_workspace_bytes: usize,
    pub max_retained_phase3j_prerequisite_bytes: usize,
    pub max_retained_transform_realization_evidence_bytes: usize,
    pub max_publication_bytes: usize,
    pub max_aggregate_peak_bytes: usize,
}

/// Consuming proof-to-proof promotion input. Borrowed objects are used only to
/// prove that both opaque inputs name the exact same live pose instances.
pub struct CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteInputV2<
    'a,
> {
    pub phase3j:
        CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseAngleIdentityPositiveThicknessPrerequisiteV2,
    pub transform_realization: CanonicalBinary64PosePairTransformRealizationEvidenceV2,
    pub geometry: &'a MaterialHingeGraphGeometry,
    pub lower_pose: &'a ClosedMaterialHingeGraphPose,
    pub upper_pose: &'a ClosedMaterialHingeGraphPose,
    pub limits:
        CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteLimitsV2,
}

/// Complete live replay input. The kinematics verifier is reconstructed from
/// the exact geometry, audit and pose references nested in `phase3j_replay`.
pub struct CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteRevalidationInputV2<
    'a,
> {
    pub phase3j_replay:
        CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseAngleIdentityPositiveThicknessPrerequisiteRevalidationInputV2<'a>,
    pub transform_realization_limits: CanonicalBinary64PosePairTransformRealizationLimitsV2,
    pub limits:
        CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteLimitsV2,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct Phase3KResourcesV2 {
    retained_phase3j_prerequisite_bytes: usize,
    retained_transform_realization_evidence_bytes: usize,
    pose_pair_deep_retained_bytes_cap: usize,
    canonical_transform_logical_work: usize,
    canonical_transform_workspace_bytes: usize,
    delegated_phase3j_replay_peak_bytes: usize,
    composition_workspace_bytes: usize,
    publication_bytes: usize,
    aggregate_peak_bytes: usize,
}

/// Opaque proof of the narrow Phase 3K join.
///
/// It deliberately implements neither `Clone`, serde, `Deref`, raw nested
/// evidence access nor downgrade conversions.
///
/// ```compile_fail
/// use ori_collision::CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2;
/// fn require_clone<T: Clone>() {}
/// require_clone::<CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2>();
/// ```
///
/// ```compile_fail
/// use ori_collision::CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2;
/// fn require_serialize<T: serde::Serialize>() {}
/// require_serialize::<CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2>();
/// ```
///
/// ```compile_fail
/// use ori_collision::CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2;
/// fn require_deref<T: std::ops::Deref>() {}
/// require_deref::<CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2>();
/// ```
///
/// ```compile_fail
/// use ori_collision::CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2;
/// fn require_deserialize<'de, T: serde::Deserialize<'de>>() {}
/// require_deserialize::<CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2>();
/// ```
///
/// ```compile_fail
/// use ori_collision::CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2;
/// fn fabricate() -> CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2 {
///     CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2 {}
/// }
/// ```
///
/// ```compile_fail
/// use ori_collision::CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2;
/// fn expose(value: &CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2) {
///     let _ = &value.transform_realization;
/// }
/// ```
///
/// ```compile_fail
/// use ori_collision::{CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseAngleIdentityPositiveThicknessPrerequisiteV2, CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2};
/// fn downgrade(value: CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2) -> CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseAngleIdentityPositiveThicknessPrerequisiteV2 {
///     value.into()
/// }
/// ```
pub struct CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2
{
    phase3j:
        CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseAngleIdentityPositiveThicknessPrerequisiteV2,
    transform_realization: CanonicalBinary64PosePairTransformRealizationEvidenceV2,
    resources: Phase3KResourcesV2,
    limits:
        CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteLimitsV2,
    binding_fingerprint: [u8; 32],
}

impl std::fmt::Debug
    for CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2
{
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2")
            .field("model", &self.model_id_v2())
            .field("actual_block_count", &self.actual_block_count_v2())
            .field("face_count", &self.face_count_v2())
            .field("hinge_count", &self.hinge_count_v2())
            .field("canonical_binary64_realized_pose_count", &2usize)
            .field("publication_bytes", &self.publication_bytes_v2())
            .field(
                "aggregate_peak_bytes",
                &self.aggregate_peak_bytes_upper_bound_v2(),
            )
            .finish_non_exhaustive()
    }
}

impl CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2
{
    #[must_use]
    pub const fn model_id_v2(&self) -> &'static str {
        COMMON_ARTICULATION_DYNAMIC_GENERAL_N_CLOSED_DYADIC_REPRESENTATION_BOUNDARY_POSE_CANONICAL_BINARY64_TRANSFORM_POSITIVE_THICKNESS_PREREQUISITE_MODEL_ID_V2
    }

    #[must_use]
    pub const fn actual_block_count_v2(&self) -> usize { self.phase3j.actual_block_count_v2() }

    #[must_use]
    pub const fn face_count_v2(&self) -> usize { self.transform_realization.face_count_v2() }

    #[must_use]
    pub const fn hinge_count_v2(&self) -> usize { self.transform_realization.hinge_count_v2() }

    #[must_use]
    pub fn matches_pose_instances_v2(
        &self,
        lower_pose: &ClosedMaterialHingeGraphPose,
        upper_pose: &ClosedMaterialHingeGraphPose,
    ) -> bool {
        self.phase3j.matches_pose_instances_v2(lower_pose, upper_pose)
            && self
                .transform_realization
                .matches_pose_instances_v2(lower_pose, upper_pose)
    }

    #[must_use]
    pub const fn publication_bytes_v2(&self) -> usize { self.resources.publication_bytes }

    #[must_use]
    pub const fn retained_phase3j_prerequisite_bytes_v2(&self) -> usize {
        self.resources.retained_phase3j_prerequisite_bytes
    }

    #[must_use]
    pub const fn retained_transform_realization_evidence_bytes_v2(&self) -> usize {
        self.resources
            .retained_transform_realization_evidence_bytes
    }

    #[must_use]
    pub const fn canonical_transform_logical_work_v2(&self) -> usize {
        self.resources.canonical_transform_logical_work
    }

    #[must_use]
    pub const fn canonical_transform_workspace_bytes_upper_bound_v2(&self) -> usize {
        self.resources.canonical_transform_workspace_bytes
    }

    #[must_use]
    pub const fn aggregate_peak_bytes_upper_bound_v2(&self) -> usize {
        self.resources.aggregate_peak_bytes
    }

    #[must_use]
    pub const fn proves_both_scheduled_representation_boundary_pose_objects_have_positive_thickness_and_canonical_binary64_transform_realization_v2(
        &self,
    ) -> bool {
        self.phase3j
            .both_scheduled_angle_representation_points_have_positive_thickness_v2()
            && self
                .transform_realization
                .proves_both_pose_instances_are_canonical_binary64_transform_realizations_v2()
    }

    pub fn revalidate_v2(
        &self,
        input: CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteRevalidationInputV2<'_>,
    ) -> Result<(), CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteErrorV2> {
        self.revalidate_with_checkpoint_v2(input, || Ok(()))
    }

    pub fn revalidate_with_checkpoint_v2(
        &self,
        input: CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteRevalidationInputV2<'_>,
        mut checkpoint: impl FnMut() -> Result<
            (),
            CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteStopV2,
        >,
    ) -> Result<(), CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteErrorV2> {
        validation::revalidate_v2(self, input, &mut checkpoint)
    }

    #[must_use] pub const fn authorizes_source_target_identity(&self) -> bool { false }
    #[must_use] pub const fn authorizes_current_requested_identity(&self) -> bool { false }
    #[must_use] pub const fn authorizes_application_parameter_identity(&self) -> bool { false }
    #[must_use] pub const fn authorizes_direction(&self) -> bool { false }
    #[must_use] pub const fn authorizes_layer_order(&self) -> bool { false }
    #[must_use] pub const fn authorizes_exact_closure(&self) -> bool { false }
    #[must_use] pub const fn authorizes_transform_realization(&self) -> bool { false }
    #[must_use] pub const fn authorizes_pose_realization(&self) -> bool { false }
    #[must_use] pub const fn authorizes_continuous_motion(&self) -> bool { false }
    #[must_use] pub const fn authorizes_collision_clearance(&self) -> bool { false }
    #[must_use] pub const fn authorizes_layer_transport(&self) -> bool { false }
    #[must_use] pub const fn authorizes_project_mutation(&self) -> bool { false }
    #[must_use] pub const fn authorizes_apply(&self) -> bool { false }
    #[must_use] pub const fn authorizes_viewer(&self) -> bool { false }
    #[must_use] pub const fn authorizes_export(&self) -> bool { false }
}

pub fn prove_common_articulation_dynamic_general_n_closed_dyadic_representation_boundary_pose_canonical_binary64_transform_positive_thickness_prerequisite_v2(
    input: CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteInputV2<'_>,
) -> Result<CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2, CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteErrorV2>{
    prove_common_articulation_dynamic_general_n_closed_dyadic_representation_boundary_pose_canonical_binary64_transform_positive_thickness_prerequisite_with_checkpoint_v2(input, || Ok(()))
}

pub fn prove_common_articulation_dynamic_general_n_closed_dyadic_representation_boundary_pose_canonical_binary64_transform_positive_thickness_prerequisite_with_checkpoint_v2(
    input: CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteInputV2<'_>,
    mut checkpoint: impl FnMut() -> Result<
        (),
        CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteStopV2,
    >,
) -> Result<CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteV2, CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteErrorV2>{
    validation::issue_v2(input, &mut checkpoint)
}

fn transform_replay_input_v2<'a>(
    input: &CommonArticulationDynamicGeneralNClosedDyadicRepresentationBoundaryPoseCanonicalBinary64TransformPositiveThicknessPrerequisiteRevalidationInputV2<'a>,
) -> CanonicalBinary64PosePairTransformRealizationInputV2<'a> {
    CanonicalBinary64PosePairTransformRealizationInputV2 {
        geometry: input.phase3j_replay.boundary_configuration_replay.geometry,
        audit: input.phase3j_replay.audit,
        fixed_face: input.phase3j_replay.lower_pose.fixed_face(),
        lower_pose: input.phase3j_replay.lower_pose,
        upper_pose: input.phase3j_replay.upper_pose,
        limits: input.transform_realization_limits,
    }
}

#[cfg(test)]
#[path = "closed_dyadic_representation_boundary_pose_canonical_binary64_transform_positive_thickness/tests.rs"]
mod tests;
